# Contenu des guides. Pour ajouter un lien affilié à un produit : "link": "https://www.amazon.fr/dp/XXXX?tag=VOTRE-TAG-21"

CATEGORIES = [
    {"key": "menage", "name": "Ménage", "pain": "Aspirer, laver les sols, nettoyer les vitres.", "intro": "Robots aspirateurs, aspirateurs sans fil, laveurs de sols et de vitres : tout ce qui fait le ménage à votre place, ou au moins deux fois plus vite."},
    {"key": "linge", "name": "Linge", "pain": "Étendre, sécher, repasser.", "intro": "Sécher sans étendre, défroisser sans planche, laver et sécher dans la même machine : les appareils qui allègent la corvée du linge."},
    {"key": "cuisine", "name": "Cuisine", "pain": "Cuisiner, surveiller, faire la vaisselle.", "intro": "Des repas qui se préparent seuls et une vaisselle qui se lave sans vous : les appareils qui libèrent du temps en cuisine."},
    {"key": "jardin", "name": "Jardin & piscine", "pain": "Tondre, arroser, nettoyer la piscine et la terrasse.", "intro": "Tonte, arrosage, piscine, terrasse, feuilles mortes : les robots et outils qui entretiennent l'extérieur pendant que vous en profitez."},
    {"key": "animaux", "name": "Animaux", "pain": "Litière, repas, eau, poils.", "intro": "Litière, croquettes, eau fraîche, poils sur le canapé : les équipements qui s'occupent du quotidien de votre chat ou de votre chien."},
]

VERIFY = "à vérifier"

GUIDES = [
# ---------------------------------------------------------------- SOLS
{
"slug": "robot-aspirateur-laveur", "cat": "menage", "short": "Robot aspirateur laveur",
"title": "Robot aspirateur laveur 2026 : comparatif et guide d'achat",
"desc": "Quel robot aspirateur laveur choisir ? Station de vidage, lavage des serpillières, tapis, animaux : notre comparatif de 4 modèles et les critères qui comptent.",
"h1": "Robot aspirateur laveur : lequel choisir pour ne plus passer la serpillière",
"lede": "Station de vidage, lavage des serpillières, franchissement des tapis, cartographie : ce qui distingue un robot qui fait vraiment le travail d'un robot qu'il faut surveiller.",
"teaser": "Ne plus toucher ni à l'aspirateur ni à la serpillière.", "read": 10,
"pick": {"why": "Le bon équilibre pour un logement familial : il aspire, lave, puis rince et sèche ses serpillières tout seul. Vous videz l'eau sale de temps en temps, c'est tout.",
         "alts": 'Budget serré ? Voir <a href="#p3">Xiaomi Robot Vacuum</a>. Beaucoup de poils d\'animaux ? Voir <a href="#p2">Dreame L-series</a>.'},
"table_cols": ["Station", "Lavage"],
"products": [
 {"name": "Roborock Qrevo", "brand": "Roborock", "badge": "Meilleur choix", "price": "€€€", "table": ["Vidage + lavage + séchage", "Serpillières rotatives"],
  "for": "les foyers qui veulent ne plus toucher ni à l'aspirateur ni à la serpillière.",
  "pros": ["Station qui vide la poussière et lave les serpillières", "Soulève les serpillières sur les tapis", "Application claire, cartographie fiable"],
  "cons": ["Station encombrante", "Sacs à poussière à racheter"],
  "specs": [("Station", "Tout-en-un"), ("Navigation", "Laser (LiDAR)"), ("Lavage", "2 serpillières rotatives"), ("Surface conseillée", "Grande maison")]},
 {"name": "Dreame L-series", "brand": "Dreame", "badge": "Animaux", "price": "€€€€", "table": ["Vidage + lavage + séchage", "Serpillières rotatives"],
  "for": "les maisons avec chiens ou chats, et beaucoup de tapis.",
  "pros": ["Brosse conçue pour limiter l'emmêlement des poils", "Forte puissance d'aspiration", "Bon franchissement des seuils"],
  "cons": ["Prix élevé sur les modèles récents", "Gamme difficile à suivre"],
  "specs": [("Station", "Tout-en-un"), ("Navigation", "Laser (LiDAR)"), ("Lavage", "2 serpillières rotatives"), ("Surface conseillée", "Grande maison")]},
 {"name": "Xiaomi Robot Vacuum", "brand": "Xiaomi", "badge": "Petit budget", "price": "€", "table": ["Base de charge simple", "Serpillière fixe"],
  "for": "un studio ou un petit appartement, pour se débarrasser de l'aspirateur quotidien.",
  "pros": ["Prix d'entrée bas", "Navigation laser même en entrée de gamme", "Compact, passe sous la plupart des meubles"],
  "cons": ["Bac à vider à la main", "Le lavage reste un simple passage humide"],
  "specs": [("Station", "Charge seule"), ("Navigation", "Laser (LiDAR)"), ("Lavage", "Serpillière fixe"), ("Surface conseillée", "Appartement")]},
 {"name": "Ecovacs Deebot", "brand": "Ecovacs", "badge": "Grandes surfaces", "price": "€€€", "table": ["Vidage + lavage + séchage", "Selon modèle"],
  "for": "les grandes maisons de plain-pied avec beaucoup de carrelage.",
  "pros": ["Bonne autonomie de batterie", "Station complète sur les modèles haut de gamme", "Bon lavage des sols durs"],
  "cons": ["Application moins intuitive", "Assistant vocal intégré peu utile"],
  "specs": [("Station", "Tout-en-un"), ("Navigation", "Laser (LiDAR)"), ("Lavage", "Selon modèle"), ("Surface conseillée", "Grande maison")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Le vrai gain de temps ne vient pas de la puissance d'aspiration, mais de tout ce que le robot fait sans vous.",
"criteria": [
 ("Station de vidage", "Le robot vide-t-il seul son bac ?", "Sans station, il faut vider le bac après presque chaque passage."),
 ("Lavage des serpillières", "La station lave et sèche-t-elle les serpillières ?", "Sinon elles sentent mauvais et il faut les laver à la main."),
 ("Gestion des tapis", "Les serpillières se soulèvent-elles sur un tapis ?", "Évite de mouiller les tapis ou de devoir les retirer."),
 ("Navigation", "Laser (LiDAR) ou caméra, et évitement d'obstacles", "Un robot qui se perd ou avale un câble demande une surveillance."),
 ("Hauteur", "Hauteur du robot comparée à vos meubles", "C'est sous le canapé et le lit que la poussière s'accumule."),
 ("Coût d'usage", "Prix des sacs, filtres, brosses et serpillières", "Sur trois ans, les consommables pèsent dans le budget."),
],
"tip": {"title": "Préparer la maison une seule fois", "steps": [
 "Lancez une première cartographie, portes ouvertes, sans rien programmer.",
 "Rangez ou fixez les câbles et les lacets qui traînent au sol.",
 "Créez des zones interdites autour des gamelles et des tapis à franges.",
 "Programmez un passage quotidien quand personne n'est à la maison."]},
"mistakes": [
 ("Économiser sur la station", "Sans vidage automatique, la corvée change juste de forme. C'est la station qui libère vraiment."),
 ("Choisir à la puissance", "Les chiffres d'aspiration ne disent pas grand-chose. La navigation compte bien plus."),
 ("Oublier la hauteur", "Un robot trop haut ne passe pas sous le lit, là où il serait le plus utile."),
 ("Négliger l'entretien", "Une brosse emmêlée ou un filtre plein réduit l'efficacité. Cinq minutes par semaine suffisent."),
],
"faq": [
 ("Un robot remplace-t-il vraiment l'aspirateur classique ?", "Pour l'entretien quotidien, oui. Il faudra encore un aspirateur à main pour les escaliers, le canapé et les coins difficiles."),
 ("Le lavage est-il aussi bon qu'une serpillière à la main ?", "Pour les traces du quotidien, les modèles à serpillières rotatives s'en approchent. Une tache séchée demandera encore un coup d'éponge."),
 ("Est-ce adapté avec des animaux ?", "Oui, et c'est même là qu'il est le plus utile. Choisissez une brosse anti-emmêlement et un bon évitement d'obstacles."),
 ("Est-ce bruyant ?", "Le robot lui-même est discret, mais le vidage de la station est bruyant quelques secondes. Programmez-le quand vous êtes absent."),
],
},
# ---------------------------------------------------------------- PELOUSE
{
"slug": "robot-tondeuse", "cat": "jardin", "short": "Robot tondeuse",
"title": "Robot tondeuse 2026 : comparatif avec ou sans fil",
"desc": "Robot tondeuse avec fil périmétrique ou GPS RTK ? Surface, pente, bruit, sécurité : notre comparatif de 4 robots tondeuses et nos conseils d'installation.",
"h1": "Robot tondeuse : bien choisir pour ne plus jamais tondre",
"lede": "Surface réelle, pente, passages étroits, fil enterré ou guidage par satellite : ce qui compte pour qu'un robot tonde seul toute la saison.",
"teaser": "Une pelouse nette sans sortir la tondeuse.", "read": 11,
"pick": {"why": "La référence pour une pelouse de taille moyenne avec des recoins : très fiable, silencieuse, et capable de gérer des pentes marquées.",
         "alts": 'Pas envie d\'enterrer un fil ? Voir <a href="#p4">Segway Navimow</a>. Petit jardin et petit budget ? Voir <a href="#p3">Worx Landroid</a>.'},
"table_cols": ["Guidage", "Pentes"],
"products": [
 {"name": "Husqvarna Automower", "brand": "Husqvarna", "badge": "Meilleur choix", "price": "€€€", "table": ["Fil ou RTK selon modèle", "Fortes"],
  "for": "les jardins avec recoins, pentes et passages étroits.",
  "pros": ["Très grande fiabilité sur la durée", "Gère les terrains en pente", "Silencieux, peut tondre la nuit"],
  "cons": ["Prix élevé", "Installation du fil fastidieuse sur les modèles filaires"],
  "specs": [("Guidage", "Fil ou RTK"), ("Pentes", "Fortes"), ("Connexion", "Selon modèle"), ("Jardin", "Petit à très grand")]},
 {"name": "Gardena Sileno", "brand": "Gardena", "badge": "Silencieux", "price": "€€", "table": ["Fil périmétrique", "Moyennes"],
  "for": "les jardins de lotissement où le voisinage compte.",
  "pros": ["Parmi les plus silencieux", "Bon rapport qualité-prix", "Application simple"],
  "cons": ["Moins à l'aise sur les fortes pentes", "Fil périmétrique obligatoire"],
  "specs": [("Guidage", "Fil périmétrique"), ("Pentes", "Moyennes"), ("Connexion", "Bluetooth / appli"), ("Jardin", "Petit à moyen")]},
 {"name": "Worx Landroid", "brand": "Worx", "badge": "Petit budget", "price": "€", "table": ["Fil périmétrique", "Moyennes"],
  "for": "un petit jardin plat, pour se lancer sans trop dépenser.",
  "pros": ["Prix d'entrée accessible", "Coupe en bordure correcte", "Accessoires disponibles (capteurs, modules)"],
  "cons": ["Navigation plus aléatoire", "Plus bruyant que la concurrence"],
  "specs": [("Guidage", "Fil périmétrique"), ("Pentes", "Moyennes"), ("Connexion", "Wi-Fi + appli"), ("Jardin", "Petit à moyen")]},
 {"name": "Segway Navimow", "brand": "Segway", "badge": "Sans fil", "price": "€€€", "table": ["GPS RTK + caméra", "Moyennes"],
  "for": "ceux qui refusent de creuser une tranchée pour un fil.",
  "pros": ["Aucun fil à enterrer", "Tonte en lignes droites, rendu net", "Zones modifiables depuis l'appli"],
  "cons": ["A besoin d'un ciel dégagé pour le signal", "Antenne à installer dans le jardin"],
  "specs": [("Guidage", "GPS RTK"), ("Pentes", "Moyennes"), ("Connexion", "Wi-Fi / 4G selon modèle"), ("Jardin", "Petit à grand")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "La surface annoncée par les fabricants est un maximum théorique. Choisissez toujours un modèle prévu pour un terrain un peu plus grand que le vôtre.",
"criteria": [
 ("Surface", "Surface maximale annoncée", "Prenez une marge de 20 à 30 % : recoins et pentes ralentissent le robot."),
 ("Guidage", "Fil périmétrique ou GPS RTK", "Le RTK évite l'installation du fil, mais demande un ciel dégagé."),
 ("Pente maximale", "Pourcentage de pente accepté", "Un robot qui patine dans une pente laisse des zones non tondues."),
 ("Passages étroits", "Largeur minimale entre deux zones", "Indispensable pour relier un jardin avant et arrière."),
 ("Bruit", "Niveau sonore en décibels", "Permet de tondre tôt, tard, ou la nuit sans gêner."),
 ("Antivol", "Code PIN, alarme, localisation", "Un robot posé dehors toute la saison est une cible."),
],
"tip": {"title": "Réussir l'installation du premier coup", "steps": [
 "Tondez une dernière fois vous-même, assez court, avant d'installer le robot.",
 "Placez la base sur une zone plate, à l'ombre si possible, près d'une prise.",
 "Laissez 30 cm entre le fil (ou la limite virtuelle) et les bordures dures.",
 "Programmez des passages courts et fréquents plutôt qu'une longue tonte hebdomadaire."]},
"mistakes": [
 ("Prendre la surface au plus juste", "Le robot n'aura jamais le temps de tout tondre, surtout au printemps."),
 ("Laisser tourner la nuit avec des hérissons", "Préférez des horaires de journée ou un modèle avec détection d'obstacles."),
 ("Négliger les lames", "Des lames émoussées arrachent l'herbe. Changez-les plusieurs fois par saison."),
 ("Oublier l'hiver", "Rentrez le robot au sec et chargez la batterie avant de le stocker."),
],
"faq": [
 ("Faut-il ramasser l'herbe coupée ?", "Non. Le robot coupe peu à chaque passage, et les brins fins servent d'engrais naturel (mulching)."),
 ("Peut-il tondre sous la pluie ?", "La plupart le peuvent, mais beaucoup de modèles détectent la pluie et rentrent pour ne pas abîmer le gazon."),
 ("Et les bordures ?", "Aucun robot ne coupe parfaitement au ras des murs. Un coup de coupe-bordure reste nécessaire de temps en temps."),
 ("Combien de temps dure l'installation ?", "Comptez une demi-journée pour poser un fil périmétrique, et environ une heure pour un modèle RTK."),
],
},
# ---------------------------------------------------------------- PISCINE
{
"slug": "robot-piscine", "cat": "jardin", "short": "Robot de piscine",
"title": "Robot de piscine 2026 : comparatif électrique et sans fil",
"desc": "Robot de piscine électrique ou sans fil ? Fond, parois, ligne d'eau, filtration : notre comparatif de 4 robots et les critères pour bien choisir.",
"h1": "Robot de piscine : lequel choisir pour une eau propre sans effort",
"lede": "Fond seul ou parois et ligne d'eau, câble ou batterie, filtration fine : ce qui sépare un robot qui nettoie vraiment d'un gadget qui tourne en rond.",
"teaser": "Une eau propre sans passer l'épuisette.", "read": 9,
"pick": {"why": "Le choix le plus sûr pour une piscine enterrée classique : il nettoie fond, parois et ligne d'eau, avec une filtration facile à vider.",
         "alts": 'Pas envie de câble ? Voir <a href="#p3">Aiper</a>. Petit budget ? Voir <a href="#p4">Zodiac</a>.'},
"table_cols": ["Alimentation", "Nettoie"],
"products": [
 {"name": "Dolphin (Maytronics)", "brand": "Maytronics", "badge": "Meilleur choix", "price": "€€€", "table": ["Câble", "Fond, parois, ligne d'eau"],
  "for": "les piscines enterrées familiales, utilisées tout l'été.",
  "pros": ["Nettoyage complet, très régulier", "Filtres faciles d'accès", "Réseau de réparateurs étendu"],
  "cons": ["Câble qui peut s'emmêler", "Robot lourd à sortir de l'eau"],
  "specs": [("Alimentation", "Câble flottant"), ("Nettoie", "Fond + parois + ligne d'eau"), ("Filtration", "Fine, par cartouche"), ("Piscine", "Jusqu'à 12 m")]},
 {"name": "Beatbot", "brand": "Beatbot", "badge": "Haut de gamme", "price": "€€€€", "table": ["Batterie", "Fond, parois, ligne d'eau, surface"],
  "for": "ceux qui veulent le modèle sans fil le plus complet, sans compromis.",
  "pros": ["Sans câble", "Nettoie aussi la surface de l'eau", "Se gare seul au bord pour être récupéré"],
  "cons": ["Prix très élevé", "Marque récente, recul limité"],
  "specs": [("Alimentation", "Batterie"), ("Nettoie", "Fond + parois + surface"), ("Filtration", "Double filtre"), ("Piscine", "Grande")]},
 {"name": "Aiper", "brand": "Aiper", "badge": "Sans fil", "price": "€€", "table": ["Batterie", "Fond, parois selon modèle"],
  "for": "les piscines moyennes, pour en finir avec le câble.",
  "pros": ["Aucun câble à démêler", "Prix raisonnable pour un sans-fil", "Léger à sortir"],
  "cons": ["Autonomie limitée sur les grands bassins", "Entrée de gamme limitée au fond"],
  "specs": [("Alimentation", "Batterie"), ("Nettoie", "Selon modèle"), ("Filtration", "Panier"), ("Piscine", "Petite à moyenne")]},
 {"name": "Zodiac", "brand": "Zodiac", "badge": "Petit budget", "price": "€", "table": ["Câble", "Fond, parois selon modèle"],
  "for": "une piscine hors-sol ou un petit bassin.",
  "pros": ["Prix accessible", "Marque historique, pièces faciles à trouver", "Simple à utiliser"],
  "cons": ["Moins efficace sur la ligne d'eau", "Navigation moins intelligente"],
  "specs": [("Alimentation", "Câble"), ("Nettoie", "Selon modèle"), ("Filtration", "Panier ou sac"), ("Piscine", "Petite à moyenne")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Le premier critère est la forme et le revêtement de votre bassin : un robot excellent dans une piscine rectangulaire peut peiner dans une forme libre.",
"criteria": [
 ("Zones nettoyées", "Fond seul, parois, ligne d'eau", "La ligne d'eau est là où se forme la trace grasse la plus visible."),
 ("Alimentation", "Câble ou batterie", "Le câble offre plus d'autonomie, la batterie plus de confort."),
 ("Filtration", "Finesse du filtre en microns", "Un filtre fin retient le pollen et le sable fin."),
 ("Revêtement", "Liner, carrelage, coque, béton", "Les brosses ne s'accrochent pas de la même façon."),
 ("Poids", "Poids du robot hors de l'eau", "Il faudra le sortir après chaque cycle sur la plupart des modèles."),
 ("Garantie et réparation", "Durée et présence d'un SAV en France", "Un moteur de robot coûte cher à remplacer hors garantie."),
],
"tip": {"title": "Faire durer le robot plusieurs saisons", "steps": [
 "Rincez le filtre à l'eau claire après chaque cycle.",
 "Sortez le robot de l'eau entre deux nettoyages, surtout en cas de traitement choc.",
 "Rangez-le à l'ombre : le soleil abîme le plastique et le câble.",
 "Hivernez-le au sec, batterie chargée à moitié pour les modèles sans fil."]},
"mistakes": [
 ("Ignorer la forme du bassin", "Escaliers et formes libres demandent un robot capable de grimper et de se repérer."),
 ("Laisser le robot dans l'eau", "Le chlore use les joints et le moteur plus vite."),
 ("Négliger le filtre", "Un filtre plein, et le robot ne ramasse plus rien."),
 ("Compter sur lui pour l'eau verte", "Un robot nettoie, il ne traite pas l'eau. La chimie reste nécessaire."),
],
"faq": [
 ("Remplace-t-il la filtration de la piscine ?", "Non. Il complète la filtration en ramassant les dépôts, mais la pompe et le traitement de l'eau restent indispensables."),
 ("Combien de fois le lancer ?", "Deux à trois cycles par semaine suffisent en général, plus en cas de pollen ou après un orage."),
 ("Est-ce compatible avec une piscine hors-sol ?", "Oui pour de nombreux modèles, à condition de vérifier la profondeur minimale et le type de paroi."),
 ("Sans fil ou avec câble ?", "Le sans-fil est plus confortable au quotidien. Le câble reste plus sûr pour les grands bassins et les longs cycles."),
],
},
# ---------------------------------------------------------------- VITRES
{
"slug": "robot-lave-vitres", "cat": "menage", "short": "Robot lave-vitres",
"title": "Meilleur robot lave-vitres 2026 : comparatif et avis",
"desc": "Un robot lave-vitres est-il efficace ? Baies vitrées, fenêtres sans cadre, sécurité : notre comparatif de 3 robots lave-vitres et nos conseils.",
"h1": "Robot lave-vitres : est-ce vraiment efficace, et lequel choisir",
"lede": "Ventouse ou ventilateur, pulvérisation intégrée, câble de sécurité : ce qu'il faut savoir avant de confier vos baies vitrées à un robot.",
"teaser": "Des vitres propres, même en hauteur.", "read": 8,
"pick": {"why": "Le plus abouti pour les grandes baies vitrées : il pulvérise lui-même le produit et trouve seul les bords de la vitre.",
         "alts": 'Fenêtres sans cadre ? Voir <a href="#p2">Hobot</a>. Petit budget ? Voir <a href="#p3">Cecotec Conga WinDroid</a>.'},
"table_cols": ["Adhérence", "Pulvérisation"],
"products": [
 {"name": "Ecovacs Winbot", "brand": "Ecovacs", "badge": "Meilleur choix", "price": "€€€", "table": ["Aspiration", "Intégrée"],
  "for": "les maisons avec de grandes baies vitrées.",
  "pros": ["Pulvérisation automatique selon les modèles", "Détection des bords fiable", "Câble de sécurité fourni"],
  "cons": ["Prix élevé", "Bruyant pendant le nettoyage"],
  "specs": [("Adhérence", "Aspiration"), ("Pulvérisation", "Intégrée (selon modèle)"), ("Batterie de secours", "Oui"), ("Vitre sans cadre", "Selon modèle")]},
 {"name": "Hobot", "brand": "Hobot", "badge": "Sans cadre", "price": "€€", "table": ["Aspiration", "Selon modèle"],
  "for": "les fenêtres et parois de douche sans cadre.",
  "pros": ["Gère les vitres sans cadre", "Format compact", "Plusieurs modes de nettoyage"],
  "cons": ["Lingettes à laver souvent", "Coins parfois moins bien nettoyés"],
  "specs": [("Adhérence", "Aspiration"), ("Pulvérisation", "Selon modèle"), ("Batterie de secours", "Oui"), ("Vitre sans cadre", "Oui")]},
 {"name": "Cecotec Conga WinDroid", "brand": "Cecotec", "badge": "Petit budget", "price": "€", "table": ["Aspiration", "Manuelle"],
  "for": "un appartement avec quelques fenêtres classiques.",
  "pros": ["Prix accessible", "Simple à utiliser", "Télécommande fournie"],
  "cons": ["Produit à pulvériser à la main", "Moins efficace sur les traces tenaces"],
  "specs": [("Adhérence", "Aspiration"), ("Pulvérisation", "Manuelle"), ("Batterie de secours", "Oui"), ("Vitre sans cadre", "Non")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Un robot lave-vitres entretient bien des vitres déjà propres. Pour une vitre très sale, un premier nettoyage à la main reste conseillé.",
"criteria": [
 ("Sécurité", "Câble de sécurité et batterie de secours", "En cas de coupure de courant, le robot ne doit pas tomber."),
 ("Vitres sans cadre", "Détection des bords sans rebord", "Sans cette détection, le robot peut glisser hors de la vitre."),
 ("Pulvérisation", "Intégrée ou à faire soi-même", "Une pulvérisation automatique évite les traces sèches."),
 ("Longueur de câble", "Câble d'alimentation et rallonge", "Détermine la hauteur de vitre atteignable."),
 ("Bruit", "Niveau sonore du ventilateur", "Ces robots sont bruyants, autant le savoir."),
],
"tip": {"title": "Obtenir des vitres sans traces", "steps": [
 "Nettoyez par temps couvert : le soleil sèche le produit trop vite.",
 "Utilisez de l'eau déminéralisée avec très peu de produit.",
 "Attachez toujours le câble de sécurité, même au rez-de-chaussée.",
 "Lavez les lingettes en machine après chaque utilisation."]},
"mistakes": [
 ("L'utiliser sur une vitre très encrassée", "Le robot étale la saleté. Un premier lavage manuel est nécessaire."),
 ("Oublier le câble de sécurité", "C'est ce qui évite une chute de plusieurs étages."),
 ("Mettre trop de produit", "L'excès laisse des traces et fait glisser le robot."),
 ("Choisir un modèle sans détection sans cadre", "Sur une paroi de douche, il risque de tomber."),
],
"faq": [
 ("Peut-on nettoyer l'extérieur d'une fenêtre ?", "Oui, en posant le robot dehors avec le câble de sécurité attaché à l'intérieur. Vérifiez la longueur du câble."),
 ("Est-ce efficace sur une vitre très sale ?", "Moyennement. Il est conçu pour l'entretien régulier, pas pour un premier gros nettoyage."),
 ("Fonctionne-t-il sur du carrelage ou un miroir ?", "Sur un miroir oui. Sur du carrelage mural lisse, c'est possible, mais les joints gênent l'adhérence."),
 ("Est-ce dangereux ?", "Non, tant que le câble de sécurité est attaché. La batterie de secours maintient l'aspiration en cas de coupure."),
],
},
# ---------------------------------------------------------------- LINGE
{
"slug": "seche-linge-pompe-a-chaleur", "cat": "linge", "short": "Sèche-linge pompe à chaleur",
"title": "Sèche-linge pompe à chaleur 2026 : comparatif et guide",
"desc": "Sèche-linge pompe à chaleur : consommation, capacité, bruit, anti-froissage. Notre comparatif de 4 modèles pour ne plus étendre le linge.",
"h1": "Sèche-linge pompe à chaleur : lequel choisir pour ne plus étendre",
"lede": "Consommation, capacité, programmes anti-froissage, bruit : comment choisir un sèche-linge qui consomme peu et évite le repassage.",
"teaser": "Fini d'étendre et de décrocher le linge.", "read": 9,
"pick": {"why": "Très économe, doux avec le linge, et doté de bons programmes anti-froissage : de quoi ne presque plus repasser.",
         "alts": 'Budget serré ? Voir <a href="#p4">Beko</a>. Très grande famille ? Voir <a href="#p3">Samsung</a>.'},
"table_cols": ["Technologie", "Point fort"],
"products": [
 {"name": "Miele (gamme T1)", "brand": "Miele", "badge": "Meilleur choix", "price": "€€€€", "table": ["Pompe à chaleur", "Durabilité"],
  "for": "ceux qui veulent un appareil pour quinze ans.",
  "pros": ["Construction très durable", "Soin du linge excellent", "Très faible consommation"],
  "cons": ["Prix élevé", "Cycles assez longs"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "8 à 9 kg selon modèle"), ("Anti-froissage", "Oui"), ("Classe énergie", "Haute (" + VERIFY + ")")]},
 {"name": "Bosch Série 6", "brand": "Bosch", "badge": "Équilibre", "price": "€€€", "table": ["Pompe à chaleur", "Rapport qualité-prix"],
  "for": "la plupart des familles.",
  "pros": ["Bon équilibre prix et qualité", "Filtres faciles à nettoyer", "Service après-vente répandu"],
  "cons": ["Un peu bruyant en fin de cycle", "Application peu utile"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "8 à 9 kg selon modèle"), ("Anti-froissage", "Oui"), ("Classe énergie", "Haute (" + VERIFY + ")")]},
 {"name": "Samsung (gamme pompe à chaleur)", "brand": "Samsung", "badge": "Grande capacité", "price": "€€€", "table": ["Pompe à chaleur", "Capacité"],
  "for": "les grandes familles qui lavent beaucoup.",
  "pros": ["Grande capacité disponible", "Programmes vapeur anti-plis", "Design soigné"],
  "cons": ["Fiabilité plus variable selon les séries", "Encombrant"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "9 kg et plus"), ("Anti-froissage", "Vapeur selon modèle"), ("Classe énergie", "Haute (" + VERIFY + ")")]},
 {"name": "Beko (gamme pompe à chaleur)", "brand": "Beko", "badge": "Petit budget", "price": "€€", "table": ["Pompe à chaleur", "Prix"],
  "for": "un premier sèche-linge à prix contenu.",
  "pros": ["Prix d'entrée bas pour une pompe à chaleur", "Consommation raisonnable", "Simple à utiliser"],
  "cons": ["Finitions basiques", "Plus bruyant"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "8 kg selon modèle"), ("Anti-froissage", "Oui"), ("Classe énergie", "Bonne (" + VERIFY + ")")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Un sèche-linge pompe à chaleur coûte plus cher à l'achat qu'un modèle à condensation classique, mais consomme environ deux fois moins d'électricité.",
"criteria": [
 ("Technologie", "Pompe à chaleur ou condensation", "La pompe à chaleur consomme beaucoup moins et abîme moins le linge."),
 ("Capacité", "Kilos de linge sec par cycle", "Choisissez au moins la capacité de votre lave-linge."),
 ("Anti-froissage", "Rotation en fin de cycle, vapeur", "C'est ce qui permet d'éviter le repassage."),
 ("Évacuation de l'eau", "Bac ou raccord direct à l'évacuation", "Un raccord direct évite de vider le bac à chaque fois."),
 ("Bruit", "Niveau sonore en décibels", "Important si la machine est près d'une chambre."),
 ("Superposition", "Kit pour l'installer sur le lave-linge", "Gagne de la place dans une petite buanderie."),
],
"tip": {"title": "Ne presque plus repasser", "steps": [
 "Ne remplissez pas le tambour au maximum : le linge doit pouvoir bouger.",
 "Choisissez le programme « prêt à ranger » plutôt que « extra sec ».",
 "Sortez le linge dès la fin du cycle et pliez-le aussitôt.",
 "Nettoyez le filtre à peluches après chaque cycle."]},
"mistakes": [
 ("Choisir un modèle à condensation pour économiser", "L'économie à l'achat est vite perdue sur la facture d'électricité."),
 ("Oublier le filtre", "Un filtre bouché rallonge les cycles et augmente la consommation."),
 ("Trop charger", "Le linge sèche mal et se froisse davantage."),
 ("Négliger la ventilation", "Une pièce fermée et humide réduit l'efficacité de l'appareil."),
],
"faq": [
 ("Combien consomme un sèche-linge pompe à chaleur ?", "Environ deux fois moins qu'un modèle à condensation classique. Le coût exact dépend de votre tarif d'électricité et du nombre de cycles."),
 ("Abîme-t-il le linge ?", "Beaucoup moins qu'un modèle classique, car il sèche à plus basse température."),
 ("Peut-on le mettre dans une pièce froide ?", "Évitez les pièces en dessous de 5 °C environ : la pompe à chaleur devient moins efficace."),
 ("Faut-il une évacuation d'air ?", "Non. Il récupère l'eau dans un bac ou l'évacue par un tuyau, sans sortie d'air vers l'extérieur."),
],
},
# ---------------------------------------------------------------- VAISSELLE
{
"slug": "mini-lave-vaisselle", "cat": "cuisine", "short": "Mini lave-vaisselle",
"title": "Mini lave-vaisselle 2026 : sans raccordement ou compact",
"desc": "Mini lave-vaisselle sans raccordement, compact ou de comptoir : notre comparatif pour les petites cuisines, studios et locations.",
"h1": "Mini lave-vaisselle : la solution pour les cuisines sans place",
"lede": "Réservoir à remplir ou raccordement au robinet, nombre de couverts, taille : comment choisir un lave-vaisselle qui tient sur un plan de travail.",
"teaser": "Pour les cuisines sans place pour un lave-vaisselle.", "read": 8,
"pick": {"why": "Le compact le plus polyvalent : il se raccorde au robinet ou fonctionne avec un réservoir, et tient sur un plan de travail.",
         "alts": 'Location sans travaux ? Voir <a href="#p2">Bob</a>. Besoin de plus de couverts ? Voir <a href="#p3">Candy</a>.'},
"table_cols": ["Raccordement", "Couverts"],
"products": [
 {"name": "Midea compact", "brand": "Midea", "badge": "Meilleur choix", "price": "€€", "table": ["Robinet ou réservoir", "≈ 6"],
  "for": "un couple ou une petite famille dans une cuisine étroite.",
  "pros": ["Réservoir ou raccordement au choix", "Bon lavage pour sa taille", "Prix contenu"],
  "cons": ["Encombrant sur un plan de travail", "Les grandes assiettes rentrent mal"],
  "specs": [("Raccordement", "Les deux"), ("Couverts", "≈ 6"), ("Pose", "Comptoir"), ("Cycle rapide", "Oui")]},
 {"name": "Bob", "brand": "Daan Tech", "badge": "Sans raccordement", "price": "€€", "table": ["Réservoir", "≈ 2"],
  "for": "les studios, les locations et les personnes seules.",
  "pros": ["Aucun raccordement nécessaire", "Très compact et design", "Fonction désinfection"],
  "cons": ["Capacité réduite", "Recharges de produit de la marque"],
  "specs": [("Raccordement", "Réservoir"), ("Couverts", "≈ 2"), ("Pose", "Comptoir"), ("Cycle rapide", "Oui")]},
 {"name": "Candy compact", "brand": "Candy", "badge": "Plus de couverts", "price": "€", "table": ["Raccordement", "≈ 6"],
  "for": "ceux qui ont un raccordement disponible et un petit budget.",
  "pros": ["Prix accessible", "Programmes classiques complets", "Pièces faciles à trouver"],
  "cons": ["Raccordement obligatoire", "Plus bruyant"],
  "specs": [("Raccordement", "Arrivée d'eau"), ("Couverts", "≈ 6"), ("Pose", "Comptoir ou sous évier"), ("Cycle rapide", "Oui")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Avant tout, mesurez la hauteur disponible sous vos placards hauts : c'est souvent ce qui décide du modèle.",
"criteria": [
 ("Raccordement", "Réservoir, robinet ou arrivée d'eau", "Le réservoir évite tous travaux, idéal en location."),
 ("Dimensions", "Hauteur, largeur, profondeur", "Il doit tenir sous les placards avec la porte ouverte."),
 ("Capacité", "Nombre de couverts", "Comptez au moins un couvert et demi par personne et par jour."),
 ("Taille des assiettes", "Diamètre maximal accepté", "Certaines grandes assiettes ne rentrent pas."),
 ("Bruit", "Niveau sonore", "Dans un studio, il tourne souvent à côté du lit."),
],
"tip": {"title": "Bien laver dans un petit volume", "steps": [
 "Raclez les restes, mais ne rincez pas la vaisselle avant.",
 "Placez les verres en haut et les assiettes face au centre.",
 "Utilisez des pastilles adaptées aux petits volumes ou une demi-dose.",
 "Lancez-le le soir pour profiter des heures creuses."]},
"mistakes": [
 ("Oublier de mesurer sous les placards", "Le modèle peut ne pas tenir une fois la porte ouverte."),
 ("Surcharger", "L'eau ne circule plus et la vaisselle reste sale."),
 ("Utiliser une pastille entière", "Trop de produit laisse des traces sur un petit volume."),
 ("Ignorer le calcaire", "Pensez au sel régénérant si l'appareil en accepte."),
],
"faq": [
 ("Un mini lave-vaisselle consomme-t-il beaucoup d'eau ?", "Non. Il consomme en général bien moins d'eau qu'une vaisselle à la main."),
 ("Peut-on l'installer en location ?", "Oui, surtout les modèles à réservoir qui ne demandent aucun raccordement."),
 ("Lave-t-il les casseroles ?", "Les petites oui. Les grandes poêles et faitouts rentrent rarement."),
 ("Est-ce que ça vaut le coup pour une personne ?", "Oui si la vaisselle est une corvée pour vous : un modèle 2 couverts suffit."),
],
},
# ---------------------------------------------------------------- LITIERE
{
"slug": "litiere-autonettoyante", "cat": "animaux", "short": "Litière autonettoyante",
"title": "Litière autonettoyante 2026 : comparatif pour chat",
"desc": "Litière autonettoyante pour chat : poids minimal, taille de l'entrée, sable, odeurs. Notre comparatif de 4 modèles et nos conseils de transition.",
"h1": "Litière autonettoyante : bien choisir sans se tromper de modèle",
"lede": "Taille de l'entrée, poids minimal détecté, type de sable accepté, bruit, application : ce qui sépare une litière qui vous libère d'une litière que votre chat refusera.",
"teaser": "Fini le ramassage quotidien de la litière.", "read": 9,
"pick": {"why": "Le plus abouti pour un foyer avec un ou deux chats adultes : entrée large, détection fiable, bac à déchets qui tient plusieurs jours.",
         "alts": 'Budget plus serré ? Voir <a href="#p3">CATLINK Scooper</a>. Chat méfiant des espaces clos ? Voir <a href="#p4">PetSafe ScoopFree</a>.'},
"table_cols": ["Format", "Application"],
"products": [
 {"name": "Litter-Robot 4", "brand": "Whisker", "badge": "Meilleur choix", "price": "€€€€", "table": ["Globe ouvert à l'avant", "Oui"],
  "for": "les foyers qui veulent la solution la plus fiable et acceptent d'y mettre le prix.",
  "pros": ["Entrée large et basse, rassurante pour la plupart des chats", "Capteurs de présence nombreux, cycle bien sécurisé", "Fonctionne avec un sable agglomérant classique"],
  "cons": ["Prix élevé", "Encombrant en hauteur"],
  "specs": [("Format", "Globe rotatif"), ("Sable", "Agglomérant"), ("Connexion", "Wi-Fi + appli"), ("Chats conseillés", "1 à 3")]},
 {"name": "Petkit Pura Max 2", "brand": "Petkit", "badge": "Anti-odeurs", "price": "€€€", "table": ["Fermé", "Oui"],
  "for": "les appartements où l'odeur est la priorité, avec un chat habitué aux maisons de toilette fermées.",
  "pros": ["Format fermé qui limite les projections", "Diffuseur de désodorisant intégré", "Application complète (passages, poids)"],
  "cons": ["Peut intimider un chat qui n'a jamais connu de litière couverte", "Consommables de la marque recommandés"],
  "specs": [("Format", "Fermé, tambour"), ("Sable", "Agglomérant, tofu"), ("Connexion", "Wi-Fi + appli"), ("Chats conseillés", "1 à 2")]},
 {"name": "CATLINK Scooper", "brand": "CATLINK", "badge": "Rapport qualité-prix", "price": "€€", "table": ["Fermé", "Oui"],
  "for": "ceux qui veulent tester l'automatique sans viser le haut de gamme.",
  "pros": ["Prix d'entrée plus accessible", "Grand bac à déchets", "Plusieurs modes de nettoyage réglables"],
  "cons": ["Finitions moins soignées", "Application moins aboutie"],
  "specs": [("Format", "Fermé, tambour"), ("Sable", "Agglomérant"), ("Connexion", "Wi-Fi + appli"), ("Chats conseillés", "1 à 2")]},
 {"name": "PetSafe ScoopFree", "brand": "PetSafe", "badge": "Chat craintif", "price": "€", "table": ["Bac ouvert à râteau", "Non"],
  "for": "les chats qui fuient tout ce qui bouge autour d'eux, et les petits budgets.",
  "pros": ["Bac ouvert et bas, très peu intimidant", "Râteau discret, aucun tambour qui tourne", "Achat initial modeste"],
  "cons": ["Plateaux de cristaux jetables à racheter", "Moins adapté à plusieurs chats"],
  "specs": [("Format", "Bac ouvert, râteau"), ("Sable", "Cristaux en plateau"), ("Connexion", "Aucune"), ("Chats conseillés", "1")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Une litière autonettoyante se juge moins sur sa fiche technique que sur la façon dont elle s'accorde avec votre chat et votre logement.",
"criteria": [
 ("Poids minimal détecté", "Le poids en dessous duquel l'appareil ne détecte pas le chat", "Un chaton trop léger peut ne pas déclencher les sécurités. Attendez souvent l'âge adulte."),
 ("Taille de l'entrée", "Hauteur et largeur de l'ouverture", "Un grand chat ou un chat âgé doit entrer et se retourner facilement."),
 ("Type de sable", "Agglomérant, tofu, cristaux ou plateau propriétaire", "Le coût réel sur un an dépend surtout des consommables."),
 ("Bac à déchets", "Contenance annoncée en jours pour un chat", "C'est ce qui fixe la fréquence à laquelle vous devrez intervenir."),
 ("Encombrement", "Hauteur totale et place devant l'entrée", "Beaucoup de modèles ne rentrent pas sous un plan de travail."),
 ("Application", "Suivi des passages, poids, alertes", "Utile pour repérer tôt un souci urinaire, mais pas indispensable."),
],
"tip": {"title": "Une transition en douceur, sur deux semaines", "steps": [
 "Installez la nouvelle litière éteinte, à côté de l'ancienne.",
 "Mettez-y une poignée du sable déjà utilisé pour que l'odeur soit familière.",
 "Quand le chat l'utilise de lui-même, activez le nettoyage en mode manuel.",
 "Passez en mode automatique, puis retirez l'ancienne litière quelques jours plus tard."]},
"mistakes": [
 ("Acheter pour un chaton", "La plupart des modèles demandent un poids minimal. Vérifiez-le avant de commander."),
 ("Oublier le coût du sable", "Un plateau propriétaire peut coûter plus cher sur un an que l'appareil lui-même."),
 ("Mesurer seulement l'appareil", "Il faut aussi la place pour que le chat entre et pour vider le bac."),
 ("Brusquer le changement", "Un chat qui a peur une fois peut bouder la litière longtemps."),
],
"faq": [
 ("Tous les chats acceptent-ils une litière automatique ?", "Non. La grande majorité s'y fait avec une transition progressive, mais un chat très craintif préférera un modèle ouvert et silencieux."),
 ("Quel sable utiliser ?", "Celui indiqué par le fabricant. Les modèles à tambour fonctionnent en général avec un sable agglomérant fin."),
 ("Faut-il encore nettoyer à la main ?", "Oui, mais beaucoup moins : vider le bac, compléter le sable, et nettoyer à fond environ une fois par mois."),
 ("Est-ce bruyant ?", "Le cycle dure quelques minutes avec un bruit de moteur modéré. Évitez de l'installer près d'une chambre."),
],
},
# ---------------------------------------------------------------- REPAS
{
"slug": "distributeur-croquettes-automatique", "cat": "animaux", "short": "Distributeur de croquettes",
"title": "Distributeur de croquettes automatique 2026 : comparatif",
"desc": "Distributeur de croquettes automatique programmable ou connecté : notre comparatif de 4 modèles pour nourrir votre animal à heure fixe, même absent.",
"h1": "Distributeur de croquettes automatique : nourrir son animal sans y penser",
"lede": "Programmation, réservoir, batterie de secours, caméra : comment choisir un distributeur qui nourrit votre chat ou votre chien à l'heure, même quand vous n'êtes pas là.",
"teaser": "Des repas à heure fixe, même absent.", "read": 8,
"pick": {"why": "Fiable, simple à nettoyer et pilotable depuis le téléphone : le bon choix pour la plupart des chats et petits chiens.",
         "alts": 'Pas besoin d\'application ? Voir <a href="#p4">Cat Mate</a>. Envie de voir votre animal ? Voir <a href="#p2">modèle avec caméra</a>.'},
"table_cols": ["Programmation", "Secours"],
"products": [
 {"name": "Petkit Fresh Element", "brand": "Petkit", "badge": "Meilleur choix", "price": "€€", "table": ["Application", "Piles"],
  "for": "la plupart des chats et petits chiens.",
  "pros": ["Programmation précise des portions", "Réservoir hermétique, croquettes fraîches", "Fonctionne sur piles en cas de coupure"],
  "cons": ["Croquettes très grosses parfois mal distribuées", "Nécessite le Wi-Fi pour les fonctions avancées"],
  "specs": [("Programmation", "Application"), ("Secours", "Piles"), ("Animaux", "Chat, petit chien"), ("Lavable", "Bol et réservoir")]},
 {"name": "Distributeur avec caméra (Petkit, Catlink…)", "brand": "Plusieurs marques", "badge": "Caméra", "price": "€€€", "table": ["Application", "Piles"],
  "for": "ceux qui partent souvent et veulent vérifier que l'animal mange.",
  "pros": ["Caméra pour voir l'animal", "Alertes si le repas n'est pas mangé", "Programmation complète"],
  "cons": ["Plus cher", "Dépend du Wi-Fi et d'un compte en ligne"],
  "specs": [("Programmation", "Application"), ("Secours", "Selon modèle"), ("Animaux", "Chat, petit chien"), ("Caméra", "Oui")]},
 {"name": "Xiaomi Smart Pet Food Feeder", "brand": "Xiaomi", "badge": "Connecté pas cher", "price": "€", "table": ["Application", "Selon modèle"],
  "for": "un premier distributeur connecté à petit prix.",
  "pros": ["Prix bas pour un modèle connecté", "Application simple", "Design discret"],
  "cons": ["Réservoir plus petit", "Moins de réglages fins"],
  "specs": [("Programmation", "Application"), ("Secours", "Selon modèle"), ("Animaux", "Chat"), ("Lavable", "Bol")]},
 {"name": "Cat Mate (minuterie)", "brand": "Cat Mate", "badge": "Sans application", "price": "€", "table": ["Minuterie", "Piles"],
  "for": "une absence d'un ou deux jours, sans Wi-Fi ni application.",
  "pros": ["Aucune connexion nécessaire", "Accepte aussi la pâtée", "Très simple"],
  "cons": ["Nombre de repas limité", "Pas de suivi à distance"],
  "specs": [("Programmation", "Minuterie"), ("Secours", "Piles"), ("Animaux", "Chat, petit chien"), ("Pâtée", "Oui")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Un distributeur ne remplace pas une visite pendant une longue absence, mais il régularise les repas au quotidien et aide à contrôler le poids.",
"criteria": [
 ("Alimentation de secours", "Piles ou batterie en cas de coupure", "Sans secours, une coupure de courant prive l'animal de repas."),
 ("Taille des croquettes", "Diamètre maximal accepté", "Les grosses croquettes peuvent bloquer le mécanisme."),
 ("Capacité", "Volume du réservoir", "Détermine le nombre de jours d'autonomie."),
 ("Nettoyage", "Bol et réservoir passent-ils au lave-vaisselle ?", "Les graisses des croquettes rancissent dans un réservoir sale."),
 ("Fermeture", "Couvercle verrouillable", "Certains chats apprennent vite à ouvrir le réservoir."),
],
"tip": {"title": "Habituer son animal en une semaine", "steps": [
 "Placez le distributeur à l'endroit habituel des repas, éteint.",
 "Remplissez le bol à la main les premiers jours.",
 "Activez un repas automatique pendant que vous êtes présent.",
 "Ajoutez les autres repas progressivement, en surveillant que tout est mangé."]},
"mistakes": [
 ("Partir une semaine sans test", "Testez le distributeur plusieurs jours avant une absence."),
 ("Oublier l'eau", "Un distributeur de croquettes ne remplace pas une fontaine à eau."),
 ("Ne jamais le laver", "Les résidus gras rancissent et dégoûtent l'animal."),
 ("Ignorer la taille des croquettes", "Des croquettes trop grosses bloquent la distribution."),
],
"faq": [
 ("Peut-on partir en vacances avec un distributeur ?", "Pour un ou deux jours, oui. Au-delà, il faut quelqu'un pour vérifier l'eau, la litière et la santé de l'animal."),
 ("Fonctionne-t-il avec la pâtée ?", "Rarement. Seuls quelques modèles à compartiments réfrigérés ou fermés l'acceptent."),
 ("Et avec deux chats ?", "C'est possible, mais un chat dominant risque de tout manger. Il existe des modèles à puce qui reconnaissent chaque animal."),
 ("Que se passe-t-il si le Wi-Fi coupe ?", "Les bons modèles gardent le programme en mémoire et continuent de distribuer."),
],
},
]

from content2 import GUIDES2
from content3 import GUIDES3
from content4 import GUIDES4, SUBCATS
from content5a import GUIDES5A
from content5b import GUIDES5B
GUIDES = GUIDES + GUIDES2 + GUIDES3 + GUIDES4 + GUIDES5A + GUIDES5B

from verified import apply
apply(GUIDES)
