# Guides « poils de chat », ajoutés le 5 octobre 2026.

GUIDES4 = [
{
"slug": "brosse-anti-poils-chat", "cat": "animaux", "short": "Brosse anti-poils pour chat",
"title": "Brosse anti-poils pour chat 2026 : comparatif et conseils",
"desc": "Quelle brosse pour retirer les poils morts du chat avant qu'ils finissent sur le canapé ? Notre comparatif : brosse à sous-poil, carde autonettoyante, gant, brosse en caoutchouc.",
"h1": "Brosse anti-poils pour chat : retirer les poils morts avant qu'ils tombent partout",
"lede": "Le moyen le plus efficace de limiter les poils dans la maison, c'est de les retirer sur le chat. Brosse à sous-poil, carde, gant ou caoutchouc : laquelle convient à votre chat.",
"teaser": "Moins de poils partout, en brossant cinq minutes.", "read": 7,
"pick": {"why": "Sa lame fine attrape le sous-poil mort que les autres brosses laissent, et un bouton éjecte les poils sans les toucher.",
         "alts": 'Chat qui n\'aime pas être brossé ? Voir <a href="#p3">gant de toilettage</a>. Poil court ? Voir <a href="#p4">brosse en caoutchouc</a>.'},
"table_cols": ["Type", "Pelage"],
"products": [
 {"name": "FURminator (outil de toilettage)", "brand": "FURminator", "badge": "Meilleur choix", "price": "€€", "table": ["Lame à sous-poil", "Court ou long selon taille"],
  "for": "les chats qui perdent beaucoup, surtout pendant la mue.",
  "pros": ["Retire très efficacement le sous-poil mort", "Bouton qui éjecte les poils", "Versions pour poil court et poil long"],
  "cons": ["À utiliser doucement, sans insister au même endroit", "Pas adapté aux peaux sensibles ou abîmées"],
  "specs": [("Type", "Lame à sous-poil"), ("Pelage", "Court ou long (deux versions)"), ("Nettoyage", "Bouton éjecteur"), ("Fréquence", "1 à 2 fois par semaine")]},
 {"name": "Carde autonettoyante (Hertzko et autres)", "brand": "Plusieurs marques", "badge": "Poil long", "price": "€", "table": ["Carde à picots", "Long, mi-long"],
  "for": "les chats à poil long qui font des nœuds.",
  "pros": ["Démêle et retire les poils morts", "Picots rétractables : on vide la brosse en un clic", "Prix bas"],
  "cons": ["Moins efficace sur le sous-poil très dense", "Picots fins à manier avec douceur"],
  "specs": [("Type", "Carde à picots"), ("Pelage", "Long, mi-long"), ("Nettoyage", "Picots rétractables"), ("Fréquence", "Quelques fois par semaine")]},
 {"name": "Gant de toilettage", "brand": "Plusieurs marques", "badge": "Chat craintif", "price": "€", "table": ["Gant à picots souples", "Tous"],
  "for": "les chats qui fuient la brosse mais adorent les caresses.",
  "pros": ["Le chat croit qu'on le caresse", "Aucun risque d'irriter la peau", "Très bon marché"],
  "cons": ["Retire moins de poils qu'une brosse", "Peu efficace sur le sous-poil"],
  "specs": [("Type", "Gant à picots souples"), ("Pelage", "Tous"), ("Nettoyage", "Rinçage à l'eau"), ("Fréquence", "Tous les jours")]},
 {"name": "Brosse en caoutchouc (Kong ZoomGroom et autres)", "brand": "Plusieurs marques", "badge": "Poil court", "price": "€", "table": ["Picots en caoutchouc", "Court"],
  "for": "les chats à poil court, en complément d'une brosse à sous-poil.",
  "pros": ["Agréable pour le chat, effet massage", "Ramasse bien les poils en surface", "Se lave à l'eau"],
  "cons": ["Peu utile sur poil long", "Ne retire pas le sous-poil profond"],
  "specs": [("Type", "Picots en caoutchouc"), ("Pelage", "Court"), ("Nettoyage", "Lavable à l'eau"), ("Fréquence", "Tous les jours")]},
],
"criteria_title": "Choisir selon le pelage de votre chat",
"criteria_intro": "Un chat à poil court et un chat à poil long ne se brossent pas avec le même outil. Le pelage compte plus que la marque.",
"criteria": [
 ("Longueur du poil", "Court, mi-long ou long", "Une lame à sous-poil pour poil court abîme un pelage long."),
 ("Sous-poil", "Densité du duvet sous les poils", "C'est lui qui finit en touffes sur le canapé."),
 ("Tolérance du chat", "Accepte-t-il la brosse ?", "Un outil doux utilisé chaque jour vaut mieux qu'un outil efficace utilisé une fois par mois."),
 ("Nettoyage de l'outil", "Éjecteur ou picots rétractables", "Enlever les poils de la brosse à la main est vite pénible."),
],
"tip": {"title": "Brosser sans stresser le chat", "steps": [
 "Choisissez un moment calme, après un repas ou une sieste.",
 "Commencez par le dos et les joues, les zones qu'il aime.",
 "Arrêtez avant qu'il s'agace, et récompensez-le.",
 "Brossez dehors ou sur un drap pour ramasser les poils d'un coup."]},
"mistakes": [
 ("Insister au même endroit", "Une lame à sous-poil peut irriter la peau."),
 ("Brosser à rebrousse-poil", "C'est désagréable pour le chat et tire sur les nœuds."),
 ("Attendre la mue", "Un brossage régulier toute l'année limite les touffes et les boules de poils."),
 ("Couper les nœuds aux ciseaux", "Le risque de couper la peau est réel : demandez à un toiletteur."),
],
"faq": [
 ("À quelle fréquence brosser un chat ?", "Une à deux fois par semaine pour un poil court, plusieurs fois par semaine pour un poil long, et plus pendant la mue."),
 ("Le brossage réduit-il les boules de poils ?", "Oui : moins de poils morts sur le chat, c'est moins de poils avalés pendant la toilette."),
 ("Et pour un chat qui refuse la brosse ?", "Commencez par un gant de toilettage, que la plupart des chats acceptent comme une caresse."),
 ("Faut-il laver le chat ?", "Rarement. Le brossage suffit dans la grande majorité des cas."),
],
},
{
"slug": "rouleau-anti-poils", "cat": "animaux", "short": "Rouleau et outils anti-poils pour canapé",
"title": "Rouleau anti-poils 2026 : canapé, vêtements et tapis sans poils de chat",
"desc": "Rouleau anti-poils réutilisable, brosse en caoutchouc, outil pour tapis : notre comparatif pour retirer les poils de chat du canapé, des vêtements et de la moquette.",
"h1": "Rouleau anti-poils : enlever les poils de chat du canapé et des vêtements",
"lede": "Rouleau réutilisable, rouleau adhésif, outil pour tapis : les solutions les plus rapides pour retirer les poils incrustés dans le tissu.",
"teaser": "Le canapé sans poils en deux minutes.", "read": 6,
"pick": {"why": "Réutilisable à l'infini, sans recharge ni pile : on le passe sur le canapé, on ouvre le réservoir et on jette les poils.",
         "alts": 'Moquette et tapis ? Voir <a href="#p2">Uproot Cleaner</a>. Vêtements avant de sortir ? Voir <a href="#p3">rouleau adhésif</a>.'},
"table_cols": ["Surface", "Consommable"],
"products": [
 {"name": "ChomChom Roller", "brand": "ChomChom", "badge": "Meilleur choix", "price": "€", "table": ["Canapé, lit, coussins", "Aucun"],
  "for": "le canapé, le lit et les fauteuils.",
  "pros": ["Réutilisable, aucune recharge", "Réservoir qui garde les poils", "Très efficace sur les tissus"],
  "cons": ["Moins pratique sur un vêtement porté", "Encombrant dans un sac"],
  "specs": [("Surface", "Tissus d'ameublement"), ("Consommable", "Aucun"), ("Vidage", "Réservoir"), ("Pile", "Non")]},
 {"name": "Uproot Cleaner", "brand": "Uproot", "badge": "Tapis", "price": "€", "table": ["Tapis, moquette", "Aucun"],
  "for": "les poils incrustés dans la moquette et les tapis.",
  "pros": ["Décroche les poils que l'aspirateur laisse", "Aucune recharge", "Compact"],
  "cons": ["À tester sur un coin : pas pour les tissus fragiles", "Demande un peu d'huile de coude"],
  "specs": [("Surface", "Tapis, moquette, tissus épais"), ("Consommable", "Aucun"), ("Vidage", "Ramasser le tas à l'aspirateur"), ("Pile", "Non")]},
 {"name": "Rouleau adhésif", "brand": "Plusieurs marques", "badge": "Vêtements", "price": "€", "table": ["Vêtements", "Feuilles adhésives"],
  "for": "un dernier passage sur les vêtements avant de sortir.",
  "pros": ["Très efficace sur les vêtements", "Petit, se glisse dans un tiroir ou un sac", "Disponible partout"],
  "cons": ["Feuilles à racheter", "Crée des déchets"],
  "specs": [("Surface", "Vêtements"), ("Consommable", "Feuilles adhésives"), ("Vidage", "Feuille à arracher"), ("Pile", "Non")]},
 {"name": "Brosse en caoutchouc pour tissus", "brand": "Plusieurs marques", "badge": "Petit budget", "price": "€", "table": ["Canapé, voiture", "Aucun"],
  "for": "les sièges de voiture et les tissus épais.",
  "pros": ["Prix très bas", "Lavable à l'eau", "Efficace sur les sièges de voiture"],
  "cons": ["Il faut ramasser les poils regroupés", "Moins rapide que le ChomChom"],
  "specs": [("Surface", "Tissus épais, voiture"), ("Consommable", "Aucun"), ("Vidage", "Rinçage"), ("Pile", "Non")]},
],
"criteria_title": "Choisir selon la surface",
"criteria_intro": "Aucun outil ne fait tout. Le plus efficace est souvent d'en combiner deux : un pour les meubles, un pour les vêtements.",
"criteria": [
 ("Surface", "Canapé, vêtements, tapis ou voiture", "Chaque outil est conçu pour un type de tissu."),
 ("Consommables", "Recharges adhésives ou outil réutilisable", "Les recharges finissent par coûter plus cher que l'outil."),
 ("Vidage", "Réservoir ou poils à ramasser", "Un réservoir évite de disperser les poils ailleurs."),
 ("Tissus fragiles", "Velours, soie, laine", "Testez toujours sur un coin caché."),
],
"tip": {"title": "Garder un canapé sans poils", "steps": [
 "Posez un plaid lavable à l'endroit où dort le chat.",
 "Passez le rouleau réutilisable une fois par semaine.",
 "Brossez le chat régulièrement : c'est autant de poils en moins sur le canapé.",
 "Laissez un rouleau adhésif près de la porte d'entrée pour les vêtements."]},
"mistakes": [
 ("Utiliser un outil abrasif sur du velours", "Il peut marquer ou user le tissu."),
 ("Compter seulement sur l'aspirateur", "Les poils s'accrochent dans le tissu et résistent à l'aspiration."),
 ("Oublier la source", "Sans brossage du chat, les poils reviennent tous les jours."),
],
"faq": [
 ("Quel est l'outil le plus efficace pour un canapé ?", "Un rouleau réutilisable à réservoir comme le ChomChom est l'un des plus rapides sur les tissus d'ameublement."),
 ("Comment enlever les poils d'un vêtement en machine ?", "Une balle anti-poils dans le tambour et un nettoyage régulier du filtre aident beaucoup."),
 ("Et sur les sièges de voiture ?", "Une brosse en caoutchouc décroche les poils, puis un aspirateur à main les ramasse."),
],
},
{
"slug": "aspirateur-toilettage-chat", "cat": "animaux", "short": "Aspirateur de toilettage pour chat",
"title": "Aspirateur de toilettage pour chat et chien 2026 : comparatif",
"desc": "Aspirateur de toilettage : brosser l'animal et aspirer les poils en même temps. Notre comparatif de kits avec brosse et tondeuse aspirantes.",
"h1": "Aspirateur de toilettage : brosser le chat sans un poil qui s'envole",
"lede": "Brosse, carde et tondeuse reliées à un aspirateur : les poils partent directement dans le réservoir au lieu de voler dans la pièce.",
"teaser": "Brosser l'animal sans un poil qui s'envole.", "read": 6,
"pick": {"why": "Un kit complet avec plusieurs brosses et une tondeuse aspirantes, à un prix raisonnable, conçu d'abord pour les animaux.",
         "alts": 'Déjà un aspirateur Dyson ? Voir <a href="#p3">accessoire Dyson</a>. Pour aussi le ménage ? Voir <a href="#p2">Neabot</a>.'},
"table_cols": ["Accessoires", "Bruit"],
"products": [
 {"name": "Oneisall (kit de toilettage aspirant)", "brand": "Oneisall", "badge": "Meilleur choix", "price": "€€", "table": ["Brosses + tondeuse", "Modéré"],
  "for": "les chats et chiens qui perdent beaucoup de poils.",
  "pros": ["Plusieurs accessoires : carde, brosse, tondeuse", "Poils aspirés directement", "Plusieurs niveaux de puissance"],
  "cons": ["Le bruit peut inquiéter un chat craintif", "Réservoir à vider souvent"],
  "specs": [("Accessoires", "Carde, brosse, tondeuse"), ("Réservoir", "Oui, amovible"), ("Usage", "Chat, chien"), ("Alimentation", "Secteur")]},
 {"name": "Neabot (kit de toilettage aspirant)", "brand": "Neabot", "badge": "Polyvalent", "price": "€€", "table": ["Brosses + tondeuse", "Modéré"],
  "for": "ceux qui veulent aussi aspirer les poils sur le canapé avec le même appareil.",
  "pros": ["Kit complet de toilettage", "Peut servir d'aspirateur d'appoint", "Accessoires faciles à changer"],
  "cons": ["Encombrant à ranger", "Bruit selon le niveau de puissance"],
  "specs": [("Accessoires", "Carde, brosse, tondeuse, embout"), ("Réservoir", "Oui"), ("Usage", "Chat, chien"), ("Alimentation", "Secteur")]},
 {"name": "Accessoire de toilettage Dyson", "brand": "Dyson", "badge": "Si vous avez un Dyson", "price": "€", "table": ["Brosse seule", "Selon l'aspirateur"],
  "for": "les propriétaires d'un aspirateur Dyson compatible, plutôt pour chiens.",
  "pros": ["Se fixe sur l'aspirateur existant", "Poils aspirés directement dans le bac", "Peu de place en plus"],
  "cons": ["Nécessite un aspirateur Dyson compatible", "Pensé d'abord pour les chiens à poil moyen ou long"],
  "specs": [("Accessoires", "Brosse de toilettage"), ("Réservoir", "Celui de l'aspirateur"), ("Usage", "Surtout chien"), ("Alimentation", "Aspirateur Dyson")]},
],
"criteria_title": "Ce qui compte pour un aspirateur de toilettage",
"criteria_intro": "Le bruit est le premier obstacle : un chat qui a peur une fois refusera l'appareil. Choisissez un modèle avec un niveau de puissance bas.",
"criteria": [
 ("Bruit", "Niveau le plus bas disponible", "C'est ce qui décide si le chat l'accepte."),
 ("Accessoires", "Carde, brosse, tondeuse", "La carde suffit pour la plupart des chats."),
 ("Réservoir", "Contenance et facilité de vidage", "Une séance de mue remplit vite le réservoir."),
 ("Longueur du tuyau", "Distance entre l'animal et le moteur", "Plus le moteur est loin, moins le chat est gêné."),
],
"tip": {"title": "Habituer le chat au bruit", "steps": [
 "Laissez l'appareil éteint près de la zone de repos quelques jours.",
 "Allumez-le au niveau le plus bas, loin du chat, avec une friandise.",
 "Brossez d'abord sans aspiration, puis activez-la quelques secondes.",
 "Allongez les séances petit à petit."]},
"mistakes": [
 ("Commencer au niveau maximal", "Le chat associera l'appareil à la peur."),
 ("Tondre un chat sans savoir", "La tonte d'un chat se fait rarement : demandez conseil à un toiletteur."),
 ("Oublier de vider le réservoir", "L'aspiration baisse et les poils restent sur le chat."),
],
"faq": [
 ("Tous les chats acceptent-ils un aspirateur de toilettage ?", "Non. Beaucoup s'y habituent avec patience, mais un chat très craintif préférera un gant ou une brosse."),
 ("Est-ce plus efficace qu'une brosse ?", "La quantité de poils retirée est proche ; l'avantage est que les poils ne s'envolent pas dans la pièce."),
 ("Peut-on l'utiliser sur un chiot ou un chaton ?", "Mieux vaut attendre qu'il soit habitué à la brosse classique."),
],
},
{
"slug": "anti-poils-machine-a-laver", "cat": "animaux", "short": "Anti-poils pour machine à laver",
"title": "Anti-poils pour machine à laver : du linge sans poils de chat ni de chien",
"desc": "FurZapper, balles anti-poils, sachets pour tambour : notre comparatif des accessoires qui retirent les poils d'animaux du linge pendant le lavage.",
"h1": "Anti-poils pour machine à laver : sortir le linge sans poils d'animaux",
"lede": "Plaids, housses, vêtements : quelques accessoires glissés dans le tambour attrapent une bonne partie des poils pendant le lavage et le séchage.",
"teaser": "Les poils restent dans la machine, pas sur le linge.", "read": 6,
"pick": {"why": "Réutilisable des centaines de fois, il passe au lavage comme au sèche-linge et attrape les poils au lieu de les laisser se redéposer.",
         "alts": 'Petit budget ? Voir <a href="#p2">balles anti-poils</a>. Tambour plein de poils après le lavage d\'un panier ? Voir <a href="#p3">sachets nettoyants</a>.'},
"table_cols": ["Lavage / séchage", "Réutilisable"],
"products": [
 {"name": "FurZapper", "brand": "FurZapper", "badge": "Meilleur choix", "price": "€", "table": ["Les deux", "Oui"],
  "for": "les foyers qui lavent souvent plaids, couvertures et vêtements pleins de poils.",
  "pros": ["Disque en silicone collant qui attrape les poils", "Fonctionne au lavage et au séchage", "Se rince à l'eau et redevient efficace"],
  "cons": ["N'enlève pas tout sur une grosse charge", "À rincer après chaque cycle"],
  "specs": [("Matière", "Silicone collant"), ("Usage", "Lavage et séchage"), ("Entretien", "Rinçage à l'eau"), ("Consommable", "Aucun")]},
 {"name": "Balles anti-poils", "brand": "Plusieurs marques", "badge": "Petit budget", "price": "€", "table": ["Selon modèle", "Oui"],
  "for": "un petit coup de pouce à petit prix sur le linge du quotidien.",
  "pros": ["Prix très bas, souvent vendues par lot", "Aident aussi contre les bouloches", "Rien à racheter"],
  "cons": ["Efficacité variable selon les modèles", "Bruyantes au sèche-linge pour certaines"],
  "specs": [("Matière", "Caoutchouc ou nylon"), ("Usage", "Selon notice"), ("Entretien", "Retirer les poils à la main"), ("Consommable", "Aucun")]},
 {"name": "Sachets nettoyants pour tambour", "brand": "Plusieurs marques", "badge": "Tambour", "price": "€", "table": ["Lavage", "Non"],
  "for": "nettoyer la machine après le lavage d'un panier, d'un coussin ou d'une couverture très chargée.",
  "pros": ["Aident à décoller les poils restés dans le tambour", "Simple : un sachet, un cycle", "Évite de retrouver des poils sur la lessive suivante"],
  "cons": ["Usage unique, à racheter", "Ne remplace pas le nettoyage du filtre"],
  "specs": [("Format", "Sachet à usage unique"), ("Usage", "Cycle selon notice"), ("Entretien", "Aucun"), ("Consommable", "Oui")]},
],
"criteria_title": "Ce qui compte vraiment",
"criteria_intro": "Le meilleur accessoire ne fait pas tout : enlever le gros des poils avant le lavage et nettoyer le filtre comptent autant.",
"criteria": [
 ("Lavage et séchage", "L'accessoire supporte-t-il le sèche-linge ?", "C'est au séchage que beaucoup de poils se détachent."),
 ("Réutilisable", "Sans recharge ou à usage unique", "Un outil réutilisable revient bien moins cher à l'année."),
 ("Taille de la charge", "Nombre d'accessoires par cycle", "Sur une grosse charge, il en faut souvent deux."),
 ("Entretien du filtre", "Accès facile au filtre de vidange", "Les poils finissent là : un filtre bouché fait mal vidanger la machine."),
],
"tip": {"title": "La routine du linge sans poils", "steps": [
 "Secouez le plaid dehors ou passez un rouleau avant de le mettre en machine.",
 "Ajoutez le FurZapper ou deux balles dans le tambour.",
 "Si vous avez un sèche-linge, faites 10 minutes à froid avant le lavage : les poils partent dans le filtre.",
 "Nettoyez le filtre de la machine et du sèche-linge après chaque lavage chargé en poils."]},
"mistakes": [
 ("Laver un panier plein de poils tel quel", "Les poils se redéposent sur tout le linge et bouchent le filtre."),
 ("Mélanger linge d'animal et vêtements", "Lavez les plaids et paniers à part."),
 ("Oublier le filtre de vidange", "C'est là que s'accumulent les poils, cycle après cycle."),
],
"faq": [
 ("Le FurZapper abîme-t-il le linge ?", "Il est conçu pour tourner avec le linge, mais évitez-le avec les tissus très délicats."),
 ("Les balles anti-poils marchent-elles vraiment ?", "Elles aident sur le linge du quotidien, mais retirent moins de poils qu'un disque collant."),
 ("Peut-on mettre un panier pour chat en machine ?", "Oui si l'étiquette le permet : enlevez le gros des poils avant et lavez-le seul."),
],
},
]

# Sous-rubriques : pages qui regroupent des guides autour d'un problème précis.
SUBCATS = [
 {"key": "poils-animaux", "parent": "animaux", "name": "Poils d'animaux",
  "title": "Poils de chat et de chien : rouleaux, brosses et outils qui marchent",
  "desc": "Rouleau anti-poils, brosse, aspirateur de toilettage, accessoire pour machine à laver, robot aspirateur : tous nos outils pour se débarrasser des poils de chat et de chien.",
  "intro": "Sur le canapé, les vêtements, le sol ou directement sur l'animal : les outils les plus efficaces pour en finir avec les poils, classés selon l'endroit où ils vous embêtent.",
  "guides": ["rouleau-anti-poils", "brosse-anti-poils-chat", "aspirateur-toilettage-chat", "anti-poils-machine-a-laver", "robot-aspirateur-poils-animaux"],
  "where": [
   ("Sur le canapé et les coussins", "Un rouleau réutilisable à réservoir.", "rouleau-anti-poils", 1),
   ("Sur les vêtements", "Un rouleau adhésif près de la porte.", "rouleau-anti-poils", 3),
   ("Sur les tapis et la moquette", "Un outil en caoutchouc qui décroche les poils incrustés.", "rouleau-anti-poils", 2),
   ("Sur le chat, à la source", "Une brosse de sous-poil une à deux fois par semaine.", "brosse-anti-poils-chat", 1),
   ("Sans poils qui volent", "Un aspirateur de toilettage qui aspire en brossant.", "aspirateur-toilettage-chat", 1),
   ("Dans le linge", "Un disque anti-poils dans le tambour.", "anti-poils-machine-a-laver", 1),
   ("Sur le sol, tous les jours", "Un robot aspirateur à brosse caoutchouc.", "robot-aspirateur-poils-animaux", 1),
  ]},
]
