# Guides ménage, linge et cuisine (lot 5a).

GUIDES5A = [
{
"slug": "robot-aspirateur-station-vidage", "cat": "menage", "short": "Robot aspirateur avec station de vidage",
"title": "Robot aspirateur avec station de vidage 2026 : comparatif et conseils",
"desc": "Robot aspirateur avec station de vidage automatique : fini le bac à vider chaque jour. Comparatif de 5 modèles, avec ou sans lavage, pour bien choisir.",
"h1": "Robot aspirateur avec station de vidage : le bac se vide tout seul",
"lede": "Avec une station de vidage, le robot vide son bac dans un sac fermé après chaque passage. Vous ne touchez à la poussière que quelques fois par mois, quand le sac est plein.",
"teaser": "Le bac se vide tout seul, vous jetez un sac par mois.", "read": 8,
"pick": {"why": "Il aspire, lave les sols et se vide seul dans sa station : c'est le modèle qui demande le moins d'intervention au quotidien.",
         "alts": 'Budget plus serré ? Voir <a href="#p5">Roborock Q8 Max+</a>. Beaucoup de poils d\'animaux ? Voir <a href="#p4">Roomba j7+</a>. Sols lavables en priorité ? Voir <a href="#p3">Dreame L10s Ultra</a>.'},
"table_cols": ["Lavage", "Station"],
"products": [
 {"name": "Roborock Qrevo S", "brand": "Roborock", "badge": "Meilleur choix", "price": "€€€", "table": ["Oui, serpillères rotatives", "Vidage, lavage, séchage"],
  "for": "un logement avec parquet, carrelage et quelques tapis, sans vouloir y toucher.",
  "pros": ["Aspire et lave, la station gère aussi les serpillères", "Brosse en caoutchouc contre les poils enroulés", "Cartographie et gestion des pièces dans l'appli"],
  "cons": ["Station volumineuse à prévoir au sol", "Prix élevé pour un robot"],
  "specs": [("Fonction", "Aspiration et lavage"), ("Station", "Vidage, lavage et séchage des serpillères"), ("Navigation", "Cartographie, application"), ("Entretien", "Sac à changer, réservoirs à remplir")]},
 {"name": "Ecovacs Deebot T30 Omni", "brand": "Ecovacs", "badge": "Tout-en-un", "price": "€€€", "table": ["Oui, serpillères", "Vidage, lavage, séchage"],
  "for": "ceux qui veulent un robot complet avec une station relativement compacte.",
  "pros": ["Station pensée pour être compacte", "Aspire et lave", "Brosse conçue contre l'enroulement des cheveux"],
  "cons": ["Prix proche des modèles haut de gamme", "Lavage moins utile si vous avez surtout de la moquette"],
  "specs": [("Fonction", "Aspiration et lavage"), ("Station", "Vidage, lavage et séchage"), ("Navigation", "Cartographie, application"), ("Entretien", "Sac à changer, réservoirs à remplir")]},
 {"name": "Dreame L10s Ultra", "brand": "Dreame", "badge": "Sols lavables", "price": "€€€", "table": ["Oui, serpillères rotatives", "Vidage, lavage, séchage"],
  "for": "les logements surtout en carrelage ou en parquet, où le lavage compte.",
  "pros": ["Station complète : vidage, lavage, séchage", "Bon choix si les sols sont durs", "Évite de laver les serpillères à la main"],
  "cons": ["Station encombrante", "Réservoirs à remplir et vider régulièrement"],
  "specs": [("Fonction", "Aspiration et lavage"), ("Station", "Vidage, lavage et séchage"), ("Navigation", "Cartographie, application"), ("Entretien", "Sac à changer, réservoirs à remplir")]},
 {"name": "iRobot Roomba j7+", "brand": "iRobot", "badge": "Poils d'animaux", "price": "€€€", "table": ["Aspiration seule", "Vidage"],
  "for": "les foyers avec un chat ou un chien et des sols pas trop lavés.",
  "pros": ["Deux brosses en caoutchouc, bien adaptées aux poils", "Station de vidage simple", "Détection d'obstacles pour éviter les câbles"],
  "cons": ["N'essuie pas les sols", "Sacs de rechange d'origine à racheter"],
  "specs": [("Fonction", "Aspiration seule"), ("Station", "Vidage automatique"), ("Navigation", "Cartographie, application"), ("Entretien", "Sac à changer")]},
 {"name": "Roborock Q8 Max+", "brand": "Roborock", "badge": "Petit budget", "price": "€€", "table": ["Aspiration, lavage simple", "Vidage"],
  "for": "ceux qui veulent la station de vidage sans payer pour le lavage avancé.",
  "pros": ["Station de vidage à un prix plus doux", "Navigation par laser", "Appli complète pour les zones interdites"],
  "cons": ["Lavage plus basique que les modèles à serpillères rotatives", "Pas de séchage de serpillère"],
  "specs": [("Fonction", "Aspiration, lavage simple"), ("Station", "Vidage automatique"), ("Navigation", "Laser, application"), ("Entretien", "Sac à changer")]},
],
"criteria_title": "Ce qui compte pour une station de vidage",
"criteria_intro": "Le vrai gain, c'est le temps : un robot qui se vide seul peut tourner une semaine ou deux sans intervention. Voici ce qui change l'usage.",
"criteria": [
 ("Type de station", "Vidage seul ou tout-en-un", "Une station avec lavage des serpillères évite de les rincer à la main, mais coûte plus cher et prend plus de place."),
 ("Sols du logement", "Dur, moquette ou mixte", "Le lavage n'a d'intérêt que sur carrelage ou parquet : sur moquette, un robot qui aspire seulement suffit."),
 ("Coût des sacs", "Sacs d'origine ou compatibles", "Le sac est un consommable : vérifiez son prix et la présence de sacs compatibles."),
 ("Place disponible", "Dimensions de la station", "Elle a besoin d'un dégagement autour, au sol, près d'une prise."),
 ("Poils et cheveux", "Brosse en caoutchouc ou anti-enroulement", "Une brosse classique s'enroule de poils et demande un entretien régulier."),
],
"tip": {"title": "Installer sa station sans se tromper", "steps": [
 "Placez-la contre un mur, sur une surface plane, avec un dégagement devant.",
 "Laissez le robot cartographier tout le logement avant de programmer.",
 "Dégagez les câbles et les chaussettes au sol avant le premier passage.",
 "Programmez le passage quand vous êtes absent, et changez le sac quand l'appli le signale."]},
"mistakes": [
 ("Payer pour un lavage inutile", "Sur moquette, un modèle à aspiration seule fait l'affaire."),
 ("Oublier les sacs", "Prévoyez dès l'achat un lot de sacs de rechange."),
 ("Ne pas nettoyer les capteurs et les brosses", "La station vide le bac, pas les poils enroulés autour de la brosse."),
 ("Placer la station dans un passage", "Le robot a besoin d'un accès dégagé pour y revenir."),
],
"faq": [
 ("Une station de vidage est-elle vraiment utile ?", "Oui si vous voulez oublier le robot : le bac est vidé après chaque passage, le sac dure plusieurs semaines."),
 ("Le sac est-il à racheter ?", "Oui, c'est un consommable. Des sacs compatibles existent, à vérifier pour chaque modèle."),
 ("La station fait-elle du bruit ?", "Le vidage est bruyant pendant quelques secondes. Programmez le passage quand vous n'êtes pas là."),
 ("Faut-il une station pour un petit logement ?", "Pas obligatoirement : dans un studio, un robot simple se vide en quelques secondes. La station sert surtout quand le logement ou les poils sont importants."),
],
},
{
"slug": "nettoyeur-vapeur", "cat": "menage", "short": "Nettoyeur vapeur pour sols",
"title": "Nettoyeur vapeur pour sols 2026 : balai vapeur ou traîneau, comparatif",
"desc": "Balai vapeur ou nettoyeur vapeur traîneau : notre comparatif de 5 modèles pour laver et assainir carrelage, parquet stratifié et sols durs sans produit chimique.",
"h1": "Nettoyeur vapeur pour sols : balai vapeur ou nettoyeur traîneau",
"lede": "La vapeur nettoie et dégraisse les sols avec de l'eau seulement. Reste à choisir entre le balai vapeur, léger et rapide, et le nettoyeur traîneau, plus polyvalent.",
"teaser": "Des sols propres avec de l'eau seulement.", "read": 7,
"pick": {"why": "Un nettoyeur traîneau avec sa pression de vapeur et ses accessoires : il lave les sols, mais aussi joints, vitres et salle de bain.",
         "alts": 'Petit budget ? Voir <a href="#p2">Kärcher SC 2</a>. Juste les sols, vite fait ? Voir <a href="#p3">Vileda Steam XXL</a> ou <a href="#p5">Rowenta Clean & Steam</a>.'},
"table_cols": ["Type", "Usage"],
"products": [
 {"name": "Kärcher SC 3 EasyFix", "brand": "Kärcher", "badge": "Meilleur choix", "price": "€€", "table": ["Traîneau", "Sols, joints, surfaces"],
  "for": "ceux qui veulent un seul appareil pour les sols et les petites surfaces.",
  "pros": ["Chauffe en quelques dizaines de secondes", "Réservoir d'un litre", "Accessoires pour joints, vitres et salle de bain"],
  "cons": ["Plus encombrant qu'un balai vapeur", "Cartouche anticalcaire à renouveler"],
  "specs": [("Type", "Nettoyeur vapeur traîneau"), ("Réservoir", "1 litre"), ("Chauffe", "Environ 30 secondes"), ("Accessoires", "Suceur sol, buses, cartouche anticalcaire")]},
 {"name": "Kärcher SC 2 EasyFix", "brand": "Kärcher", "badge": "Petit budget", "price": "€€", "table": ["Traîneau", "Sols, joints"],
  "for": "un usage régulier sur sols durs avec un budget plus modéré.",
  "pros": ["Mêmes bases que le SC 3, à prix plus bas", "Réservoir d'un litre", "Kit sol EasyFix inclus"],
  "cons": ["Chauffe plus lente", "Un peu moins de pression"],
  "specs": [("Type", "Nettoyeur vapeur traîneau"), ("Réservoir", "1 litre"), ("Chauffe", "Plusieurs minutes"), ("Accessoires", "Suceur sol, buses")]},
 {"name": "Vileda Steam XXL", "brand": "Vileda", "badge": "Balai vapeur", "price": "€", "table": ["Balai vapeur", "Sols uniquement"],
  "for": "laver les sols vite, sans sortir un gros appareil.",
  "pros": ["Léger et rapide à sortir", "Large tête de nettoyage", "Lingettes microfibre lavables"],
  "cons": ["Pas d'accessoires pour les joints", "Moins puissant qu'un traîneau"],
  "specs": [("Type", "Balai vapeur"), ("Réservoir", "Réservoir intégré"), ("Chauffe", "Courte"), ("Accessoires", "Lingette microfibre")]},
 {"name": "Polti Vaporetto Smart 100_T", "brand": "Polti", "badge": "Chaudière", "price": "€€", "table": ["Chaudière", "Sols, vitres, joints"],
  "for": "un nettoyage plus intensif des surfaces et des recoins.",
  "pros": ["Chaudière pensée pour un usage plus intensif", "Nombreux accessoires", "Utilisable partout dans la maison"],
  "cons": ["Un peu long à chauffer", "Plus encombrant qu'un balai"],
  "specs": [("Type", "Nettoyeur vapeur à chaudière"), ("Réservoir", "Chaudière"), ("Chauffe", "Quelques minutes"), ("Accessoires", "Brosses, buses, rallonges")]},
 {"name": "Rowenta Clean & Steam RY7535", "brand": "Rowenta", "badge": "Aspire et vapeur", "price": "€€", "table": ["Balai aspirateur-vapeur", "Sols uniquement"],
  "for": "passer l'aspirateur et la vapeur sans changer d'appareil.",
  "pros": ["Aspire puis lave en un passage", "Plus rapide que deux appareils", "Vertical, rangement simple"],
  "cons": ["Réservoir assez petit", "Moins polyvalent qu'un traîneau"],
  "specs": [("Type", "Aspirateur balai avec vapeur"), ("Réservoir", "0,4 litre"), ("Chauffe", "Rapide"), ("Accessoires", "Brosse, lingettes")]},
],
"criteria_title": "Balai ou traîneau : comment choisir",
"criteria_intro": "Le choix dépend de ce que vous voulez nettoyer : seulement les sols ou aussi les joints, la douche et les vitres.",
"criteria": [
 ("Type d'appareil", "Balai vapeur ou nettoyeur traîneau", "Le balai est plus léger ; le traîneau ajoute des accessoires pour les recoins."),
 ("Temps de chauffe", "De 30 secondes à plusieurs minutes", "Une chauffe rapide donne envie de l'utiliser souvent."),
 ("Réservoir", "Contenance en litres", "Un grand réservoir permet de laver plus de surface sans recharge."),
 ("Type de sol", "Carrelage, parquet verni, stratifié", "Le parquet non traité, le vinyle fragile et certains stratifiés craignent la vapeur : lisez la notice."),
 ("Anticalcaire", "Cartouche ou eau déminéralisée", "Dans une eau calcaire, c'est l'entretien qui prolonge la vie de l'appareil."),
],
"tip": {"title": "Utiliser la vapeur sans abîmer les sols", "steps": [
 "Balayez ou aspirez d'abord pour retirer la poussière.",
 "Testez sur un coin discret avant la première utilisation.",
 "Avancez sans rester immobile : la vapeur ne doit pas stagner sur le parquet.",
 "Laissez sécher quelques minutes avant de marcher dessus."]},
"mistakes": [
 ("Utiliser la vapeur sur un parquet non verni", "L'humidité et la chaleur peuvent le gonfler ou le ternir."),
 ("Ne pas lire la notice du revêtement", "Certains sols sont garantis sans vapeur."),
 ("Oublier l'anticalcaire", "Le calcaire encrasse la chaudière et réduit la vapeur."),
 ("Compter sur la vapeur seule pour dégraisser fort", "Sur une graisse incrustée, un détergent reste utile."),
],
"faq": [
 ("La vapeur désinfecte-t-elle vraiment ?", "Elle assainit les surfaces grâce à la chaleur, sans produit chimique, mais le résultat dépend du temps de contact et de la surface."),
 ("Peut-on utiliser de l'eau du robinet ?", "En général oui, avec la cartouche anticalcaire. Si votre eau est très calcaire, l'eau déminéralisée est plus prudente."),
 ("Quel type de sol supporte la vapeur ?", "Carrelage et pierre sans souci en général. Pour le parquet et le stratifié, vérifiez la notice."),
 ("Un balai vapeur remplace-t-il un nettoyeur traîneau ?", "Pour les sols seulement, oui. Pour les joints, les vitres ou la douche, il faut des accessoires."),
],
},
{
"slug": "mini-lave-linge", "cat": "linge", "short": "Mini lave-linge pour studio",
"title": "Mini lave-linge pour studio 2026 : portable, compact, comparatif",
"desc": "Pas de place pour une machine classique ? Notre comparatif de 5 mini lave-linge : compact à poser, portable avec essoreuse, manuel ou pliable pour studio et petits espaces.",
"h1": "Mini lave-linge pour studio : laver son linge dans peu de place",
"lede": "Du lave-linge compact de 40 cm de large à la machine portable de quelques kilos, il existe une solution pour chaque studio. Tout dépend de ce que vous lavez et de votre budget.",
"teaser": "Une machine même sans place pour une vraie.", "read": 7,
"pick": {"why": "Un vrai lave-linge à chargement par le dessus, de seulement 41 cm de large, qui lave et essore comme une machine classique.",
         "alts": 'Besoin de portable ? Voir <a href="#p2">Camry CR 8054</a>. Sans électricité ? Voir <a href="#p3">Wonderwash</a>.'},
"table_cols": ["Type", "Capacité"],
"products": [
 {"name": "Candy Smart CST 06LE", "brand": "Candy", "badge": "Meilleur choix", "price": "€€", "table": ["Compact, chargement par le dessus", "6 kg"],
  "for": "un studio où la machine peut rester branchée, raccordée à l'eau.",
  "pros": ["Vrai lave-linge avec essorage", "Seulement 41 cm de large", "Plusieurs programmes rapides"],
  "cons": ["Demande un raccordement eau et évacuation", "Plus lourd à déplacer"],
  "specs": [("Type", "Chargement par le dessus"), ("Capacité", "6 kg"), ("Largeur", "41 cm"), ("Essorage", "1000 tr/min")]},
 {"name": "Camry CR 8054", "brand": "Camry", "badge": "Portable", "price": "€", "table": ["Semi-automatique avec essoreuse", "3 kg"],
  "for": "les locataires sans raccordement d'eau, ou les logements temporaires.",
  "pros": ["Aucune installation", "Lave et essore (deux cuves)", "Se range dans un placard"],
  "cons": ["Remplissage et vidange à la main", "Linge à transférer entre les deux cuves"],
  "specs": [("Type", "Mini machine avec essoreuse"), ("Capacité", "3 kg"), ("Raccordement", "Aucun, remplissage manuel"), ("Essorage", "Cuve dédiée")]},
 {"name": "Wonderwash", "brand": "Laundry Alternative", "badge": "Sans électricité", "price": "€", "table": ["Manuel, à manivelle", "Petite charge"],
  "for": "les petites quantités de linge, les voyages ou le camping.",
  "pros": ["Aucune électricité", "Silencieux", "Se range facilement"],
  "cons": ["Demande de tourner la manivelle", "Capacité limitée, essorage à faire à part"],
  "specs": [("Type", "Manuel à manivelle"), ("Capacité", "Petite charge"), ("Raccordement", "Aucun"), ("Essorage", "Non, à faire à part")]},
 {"name": "Mini lave-linge pliable portable", "brand": "Plusieurs marques", "badge": "Sous-vêtements", "price": "€", "table": ["Pliable, électrique", "Environ 1,5 kg"],
  "for": "les sous-vêtements, chaussettes et petites pièces, en voyage ou en dortoir.",
  "pros": ["Se range plié, très compact", "Prix très bas", "Utile pour le linge fin"],
  "cons": ["Capacité très limitée", "Ne remplace pas une vraie machine"],
  "specs": [("Type", "Bac pliable électrique"), ("Capacité", "Petites pièces"), ("Raccordement", "Aucun"), ("Essorage", "Non")]},
 {"name": "Comfee mini lave-linge 0,8 kg", "brand": "Comfee", "badge": "Très petit linge", "price": "€", "table": ["Mini machine à minuterie", "0,8 kg"],
  "for": "un étudiant ou un voyageur qui lave quelques pièces à la fois.",
  "pros": ["Très compact", "Minuterie réglable", "Prix bas"],
  "cons": ["Capacité très faible", "Pas de véritable essorage"],
  "specs": [("Type", "Mini machine à minuterie"), ("Capacité", "0,8 kg"), ("Raccordement", "Aucun"), ("Essorage", "Non")]},
],
"criteria_title": "Choisir selon votre logement",
"criteria_intro": "Tout dépend de deux questions : pouvez-vous raccorder une machine à l'eau, et combien de linge lavez-vous par semaine ?",
"criteria": [
 ("Raccordement", "Arrivée et évacuation d'eau", "Sans raccordement, il faut une machine portable à remplir à la main."),
 ("Capacité", "De 1 à 6 kg", "Une personne seule lave souvent 3 à 4 kg par semaine."),
 ("Largeur et hauteur", "Dimensions de la machine", "Mesurez l'emplacement : un modèle de 40 cm de large passe presque partout."),
 ("Essorage", "Intégré ou à part", "Un essorage correct réduit nettement le temps de séchage."),
 ("Bruit", "Niveau sonore et vibrations", "En studio, la machine tourne près du lit : un modèle bruyant se remarque vite."),
],
"tip": {"title": "Laver en studio sans souci", "steps": [
 "Mesurez l'emplacement et vérifiez la prise et l'arrivée d'eau.",
 "Pour une machine portable, préparez un bac et un tuyau de vidange.",
 "Lavez de petites charges, sans remplir au maximum.",
 "Faites sécher sur un étendoir, fenêtre légèrement ouverte."]},
"mistakes": [
 ("Acheter un portable en pensant à une vraie machine", "La capacité et l'essorage sont très en dessous."),
 ("Oublier l'évacuation", "Une machine posée doit se vider quelque part."),
 ("Remplir au maximum", "Le linge tourne mal et sort moins propre."),
 ("Négliger l'accord du propriétaire", "Pour un raccordement, vérifiez ce qui est autorisé dans votre bail."),
],
"faq": [
 ("Un mini lave-linge lave-t-il aussi bien qu'une machine normale ?", "Un compact avec raccordement lave très bien. Un portable convient surtout au petit linge."),
 ("Peut-on le brancher partout ?", "Un compact a besoin d'une arrivée et d'une évacuation d'eau. Un portable n'a besoin que d'une prise (ou de rien)."),
 ("Et le séchage ?", "En studio, un étendoir ou un sèche-linge compact. Voir notre guide sur le sèche-linge à condensation."),
 ("Quelle capacité pour une personne ?", "Entre 3 et 5 kg suffisent en général."),
],
},
{
"slug": "seche-linge-condensation", "cat": "linge", "short": "Sèche-linge à condensation",
"title": "Sèche-linge à condensation 2026 : sans évacuation, comparatif",
"desc": "Sèche-linge sans tuyau d'évacuation : condensation classique ou pompe à chaleur. Notre comparatif de 5 modèles et les critères pour bien choisir selon votre logement.",
"h1": "Sèche-linge à condensation : sécher son linge sans évacuation",
"lede": "Un sèche-linge à condensation ne demande aucun tuyau vers l'extérieur : l'eau est recueillie dans un bac. Vous pouvez l'installer dans une salle de bain, une cuisine ou un placard.",
"teaser": "Du linge sec sans fenêtre ni tuyau.", "read": 8,
"pick": {"why": "Une pompe à chaleur de 8 kg : sans évacuation, avec une consommation plus basse qu'une condensation classique.",
         "alts": 'Petit budget d\'achat ? Voir <a href="#p2">Bosch WTN85V08FR</a>. Grande famille ? Voir <a href="#p4">Haier 9 kg</a> ou <a href="#p5">Samsung 9 kg</a>.'},
"table_cols": ["Technologie", "Capacité"],
"products": [
 {"name": "Beko B3T42239", "brand": "Beko", "badge": "Meilleur choix", "price": "€€€", "table": ["Pompe à chaleur", "8 kg"],
  "for": "un foyer de 2 à 4 personnes qui sèche du linge toutes les semaines.",
  "pros": ["Pompe à chaleur : consommation réduite", "Programmes vapeur et allergies", "Tambour doux pour le linge"],
  "cons": ["Prix d'achat plus élevé qu'une condensation classique", "Séchage plus long à basse température"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "8 kg"), ("Évacuation", "Aucune, bac d'eau"), ("Programmes", "15, dont vapeur")]},
 {"name": "Bosch WTN85V08FR", "brand": "Bosch", "badge": "Condensation classique", "price": "€€", "table": ["Condensation", "7 kg"],
  "for": "un petit budget d'achat et un usage occasionnel.",
  "pros": ["Prix d'achat plus bas qu'une pompe à chaleur", "Marque réputée, SAV facile", "7 kg, suffisant pour 2 personnes"],
  "cons": ["Consomme plus qu'une pompe à chaleur", "Dégage plus de chaleur dans la pièce"],
  "specs": [("Technologie", "Condensation"), ("Capacité", "7 kg"), ("Évacuation", "Aucune, bac d'eau"), ("Série", "Bosch Série 4")]},
 {"name": "Candy CSOE H8A2TE-S", "brand": "Candy", "badge": "Connecté", "price": "€€", "table": ["Pompe à chaleur", "8 kg"],
  "for": "ceux qui veulent une pompe à chaleur à prix plus doux, avec appli.",
  "pros": ["Pompe à chaleur 8 kg", "Cycles rapides", "Connectivité Wi-Fi"],
  "cons": ["Moins de finitions que les modèles haut de gamme", "Bruit audible en cycle"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "8 kg"), ("Évacuation", "Aucune, bac d'eau"), ("Connectivité", "Wi-Fi")]},
 {"name": "Haier HD90-A2979", "brand": "Haier", "badge": "Grande capacité", "price": "€€€", "table": ["Pompe à chaleur", "9 kg"],
  "for": "les familles, les couettes et les grosses charges.",
  "pros": ["9 kg, grand tambour", "Pompe à chaleur", "Programme micro-vapeur"],
  "cons": ["Encombrant", "Prix élevé"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "9 kg"), ("Évacuation", "Aucune, bac d'eau"), ("Programmes", "14")]},
 {"name": "Samsung DV90DG52A0TEEG", "brand": "Samsung", "badge": "Appli et capteurs", "price": "€€€", "table": ["Pompe à chaleur", "9 kg"],
  "for": "ceux qui veulent un modèle connecté avec séchage automatique.",
  "pros": ["9 kg et pompe à chaleur", "Capteur d'humidité pour arrêter au bon moment", "Pilotage par appli"],
  "cons": ["Prix élevé", "Plus de fonctions que nécessaire pour certains"],
  "specs": [("Technologie", "Pompe à chaleur"), ("Capacité", "9 kg"), ("Évacuation", "Aucune, bac d'eau"), ("Connectivité", "SmartThings")]},
],
"criteria_title": "Condensation ou pompe à chaleur",
"criteria_intro": "Ces deux technologies n'ont pas besoin de tuyau. La pompe à chaleur coûte plus cher à l'achat mais consomme moins : le bon choix dépend de la fréquence d'usage.",
"criteria": [
 ("Technologie", "Condensation classique ou pompe à chaleur", "La pompe à chaleur consomme nettement moins mais coûte plus cher à l'achat."),
 ("Capacité", "De 7 à 10 kg", "Prenez 1 à 2 kg de plus que votre charge de lavage."),
 ("Dimensions", "Largeur, profondeur, porte", "Vérifiez que le sens d'ouverture de la porte convient à votre pièce."),
 ("Bac d'eau", "À vider ou raccordement possible", "Un bac se vide à chaque cycle, sauf si on le raccorde à un évier."),
 ("Entretien", "Filtre à nettoyer après chaque cycle", "Un filtre propre garde la performance et limite la consommation."),
],
"tip": {"title": "Bien utiliser son sèche-linge", "steps": [
 "Essorez bien le linge avant de le sécher.",
 "Videz le bac à eau et nettoyez le filtre après chaque cycle.",
 "Ne mélangez pas serviettes épaisses et tissus fins.",
 "Aérez un peu la pièce si le modèle dégage de la chaleur."]},
"mistakes": [
 ("Surcharger le tambour", "Le linge sèche mal et le cycle s'allonge."),
 ("Oublier le filtre", "Un filtre encrassé fait monter la consommation."),
 ("Installer dans une pièce trop petite et fermée", "Prévoyez un peu d'aération."),
 ("Choisir sur le prix d'achat seulement", "Si vous séchez souvent, la pompe à chaleur se rentabilise."),
],
"faq": [
 ("Faut-il un tuyau d'évacuation ?", "Non. L'eau est récupérée dans un bac que l'on vide, ou envoyée vers une évacuation si on le raccorde."),
 ("Quelle différence entre condensation et pompe à chaleur ?", "La pompe à chaleur recycle sa chaleur, consomme moins et sèche à plus basse température, ce qui ménage le linge."),
 ("Peut-on le poser sur un lave-linge ?", "Souvent oui avec un kit de superposition, vérifiez la compatibilité."),
 ("Convient-il à un petit logement ?", "Oui, c'est l'intérêt : aucune ouverture sur l'extérieur."),
],
},
{
"slug": "poubelle-automatique", "cat": "cuisine", "short": "Poubelle automatique",
"title": "Poubelle automatique à capteur 2026 : comparatif et conseils",
"desc": "Poubelle à ouverture automatique par capteur, ou poubelle qui ferme le sac toute seule comme la Townew : notre comparatif de 5 modèles pour la cuisine.",
"h1": "Poubelle automatique : ouvrir et fermer le sac sans y toucher",
"lede": "Les mains sales, le couvercle qui sent : une poubelle à capteur s'ouvre d'un geste. Certaines vont plus loin et ferment le sac toutes seules quand il est plein.",
"teaser": "Pas de contact, pas d'odeur, pas de sac qui coule.", "read": 6,
"pick": {"why": "Elle s'ouvre d'un geste, scelle le sac plein et en remet un propre : on ne touche à rien.",
         "alts": 'Grande cuisine ? Voir <a href="#p3">EKO Mirage-T 50 L</a>. Budget serré ? Voir <a href="#p5">Amazon Basics 50 L</a>.'},
"table_cols": ["Fonction", "Capacité"],
"products": [
 {"name": "Townew T Air X", "brand": "Townew", "badge": "Meilleur choix", "price": "€€€", "table": ["Ouverture + scellage du sac", "13,5 L"],
  "for": "ceux qui veulent ne jamais toucher le sac ni la poubelle.",
  "pros": ["Scelle le sac plein et en place un autre", "Ouverture sans contact", "Rechargeable"],
  "cons": ["Petite capacité", "Bagues de sac à racheter"],
  "specs": [("Fonction", "Ouverture + scellage du sac"), ("Capacité", "13,5 L"), ("Alimentation", "Rechargeable"), ("Consommable", "Bagues de recharge Townew")]},
 {"name": "simplehuman ST2009 45 L", "brand": "simplehuman", "badge": "Haut de gamme", "price": "€€€", "table": ["Capteur, couvercle", "45 L"],
  "for": "une cuisine où la poubelle est visible et doit être solide.",
  "pros": ["Finition en inox brossé", "Capteur réactif", "Réserve de sacs intégrée"],
  "cons": ["Prix élevé", "Sacs d'origine conseillés"],
  "specs": [("Fonction", "Ouverture par capteur"), ("Capacité", "45 L"), ("Matière", "Inox brossé"), ("Alimentation", "Piles")]},
 {"name": "EKO Mirage-T 50 L", "brand": "EKO", "badge": "Grande capacité", "price": "€€", "table": ["Capteur, couvercle", "50 L"],
  "for": "un foyer qui jette beaucoup, avec un sac de grande taille.",
  "pros": ["50 L, rectangulaire, se range contre un mur", "Ouverture sans contact", "Coloris au choix"],
  "cons": ["Encombrante pour une petite cuisine", "Il faut changer les piles de temps en temps"],
  "specs": [("Fonction", "Ouverture par capteur"), ("Capacité", "50 L"), ("Matière", "Acier"), ("Alimentation", "Piles ou adaptateur")]},
 {"name": "SONGMICS LTB640B02 50 L", "brand": "SONGMICS", "badge": "Bon rapport qualité-prix", "price": "€€", "table": ["Capteur, fermeture douce", "50 L"],
  "for": "ceux qui veulent un bon équilibre entre prix et fonctions.",
  "pros": ["Ouverture automatique ou au toucher", "Fermeture douce du couvercle", "Sacs fournis au départ"],
  "cons": ["Capteur parfois sensible", "Finitions moins soignées que le haut de gamme"],
  "specs": [("Fonction", "Capteur + ouverture au toucher"), ("Capacité", "50 L"), ("Matière", "Acier"), ("Alimentation", "Piles ou USB")]},
 {"name": "Amazon Basics 50 L à capteur", "brand": "Amazon Basics", "badge": "Petit budget", "price": "€", "table": ["Capteur, couvercle", "50 L"],
  "for": "une poubelle à capteur au prix le plus bas.",
  "pros": ["Prix bas", "Grande capacité", "Forme demi-circulaire facile à caler dans un angle"],
  "cons": ["Capteur moins précis", "Finition simple"],
  "specs": [("Fonction", "Ouverture par capteur"), ("Capacité", "50 L"), ("Matière", "Inox"), ("Alimentation", "Piles")]},
],
"criteria_title": "Ouverture seule ou scellage du sac",
"criteria_intro": "Deux familles : la poubelle à capteur, qui ouvre le couvercle, et la poubelle intelligente, qui ferme aussi le sac. La seconde coûte plus cher mais évite le geste le moins agréable.",
"criteria": [
 ("Fonction", "Capteur seul ou scellage du sac", "Le scellage évite d'attraper le sac à la main et limite les odeurs."),
 ("Capacité", "De 13 à 50 L", "Une petite capacité demande de sortir le sac plus souvent."),
 ("Alimentation", "Piles, USB ou batterie", "Une batterie rechargeable évite d'acheter des piles."),
 ("Consommables", "Sacs spécifiques ou standards", "Chez Townew, les bagues de recharge sont un coût récurrent."),
 ("Capteur", "Réglage de la sensibilité", "Un capteur trop sensible s'ouvre à chaque passage."),
],
"tip": {"title": "Éviter les faux déclenchements", "steps": [
 "Placez la poubelle à 20 cm du mur pour laisser le couvercle s'ouvrir.",
 "Ne la mettez pas dans un passage où l'on frôle le capteur.",
 "Gardez le capteur propre avec un chiffon doux.",
 "Retirez les piles si vous partez en vacances."]},
"mistakes": [
 ("Choisir trop petit", "Sur une poubelle de 13 L, on sort le sac très souvent."),
 ("Oublier les consommables", "Vérifiez le coût des bagues ou sacs adaptés."),
 ("Mal placer le capteur", "Il se déclenche tout seul si un objet passe devant."),
 ("Acheter sans mesurer", "Mesurez la hauteur sous le plan de travail."),
],
"faq": [
 ("Une poubelle à capteur consomme-t-elle beaucoup ?", "Très peu : quelques piles par an en usage normal, ou une recharge USB."),
 ("Les sacs se mettent-ils comme sur une poubelle classique ?", "Oui sur une poubelle à capteur. Chez Townew, il faut des bagues de recharge spécifiques."),
 ("Est-ce utile vraiment ?", "Oui si vous cuisinez beaucoup : ouvrir sans toucher le couvercle avec les mains sales est plus hygiénique."),
 ("Quelle capacité pour une famille ?", "Autour de 45 à 50 L pour 3 à 4 personnes."),
],
},
]
