# Guides ajoutés le 5 octobre 2026. Même format que content.py.

GUIDES2 = [
# ---------------------------------------------------------------- ASPIRATEUR BALAI
{
"slug": "aspirateur-balai-sans-fil", "cat": "menage", "short": "Aspirateur balai sans fil",
"title": "Aspirateur balai sans fil 2026 : comparatif et guide d'achat",
"desc": "Quel aspirateur balai sans fil choisir ? Autonomie, puissance, poids, poils d'animaux : notre comparatif de 4 modèles pour aspirer vite, sans câble.",
"h1": "Aspirateur balai sans fil : aspirer en cinq minutes, sans sortir le traîneau",
"lede": "Autonomie réelle, poids en main, batterie amovible, brosse anti-cheveux : ce qui fait qu'on attrape l'aspirateur sans y réfléchir.",
"teaser": "Un coup d'aspirateur en cinq minutes, sans câble.", "read": 9,
"pick": {"why": "Le plus complet : puissant, bien filtré, avec un capteur qui montre la poussière ramassée. Il remplace sans problème un aspirateur traîneau.",
         "alts": 'Petit budget ? Voir <a href="#p4">Rowenta X-Force</a>. Beaucoup de poils ? Voir <a href="#p3">Shark</a>.'},
"table_cols": ["Batterie", "Poids"],
"products": [
 {"name": "Dyson V15 Detect", "brand": "Dyson", "badge": "Meilleur choix", "price": "€€€€", "table": ["Amovible", "Lourd"],
  "for": "ceux qui veulent un seul aspirateur pour toute la maison.",
  "pros": ["Aspiration très puissante", "Laser qui révèle la poussière fine", "Excellente filtration"],
  "cons": ["Prix élevé", "Lourd à bout de bras"],
  "specs": [("Batterie", "Amovible"), ("Usage", "Maison entière"), ("Brosse anti-cheveux", "Oui"), ("Filtration", "Haute")]},
 {"name": "Samsung Bespoke Jet", "brand": "Samsung", "badge": "Vidage auto", "price": "€€€", "table": ["Amovible", "Moyen"],
  "for": "ceux qui ne veulent plus jamais vider un bac à la main.",
  "pros": ["Station qui vide le bac automatiquement", "Rangement propre et vertical", "Bonne autonomie"],
  "cons": ["Station encombrante", "Sacs de station à racheter"],
  "specs": [("Batterie", "Amovible"), ("Usage", "Maison entière"), ("Vidage", "Automatique"), ("Filtration", "Haute")]},
 {"name": "Shark (gamme Anti Hair Wrap)", "brand": "Shark", "badge": "Animaux", "price": "€€", "table": ["Amovible", "Moyen"],
  "for": "les maisons avec chiens, chats ou cheveux longs.",
  "pros": ["Brosse qui ne s'emmêle pas", "Tube flexible pour passer sous les meubles", "Bon rapport qualité-prix"],
  "cons": ["Bac assez petit", "Bruyant en mode maximum"],
  "specs": [("Batterie", "Amovible"), ("Usage", "Appartement, maison"), ("Brosse anti-cheveux", "Oui"), ("Tube", "Flexible")]},
 {"name": "Rowenta X-Force Flex", "brand": "Rowenta", "badge": "Petit budget", "price": "€€", "table": ["Amovible", "Moyen"],
  "for": "un appartement, pour un aspirateur rapide du quotidien.",
  "pros": ["Prix contenu", "Tube pliable pratique sous les meubles", "Marque avec SAV en France"],
  "cons": ["Moins puissant que le haut de gamme", "Autonomie limitée en mode fort"],
  "specs": [("Batterie", "Amovible"), ("Usage", "Appartement"), ("Tube", "Pliable"), ("SAV", "France")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "L'autonomie annoncée correspond presque toujours au mode le plus faible. En mode fort, comptez souvent trois à quatre fois moins.",
"criteria": [
 ("Autonomie réelle", "Durée en mode normal, pas en mode éco", "C'est ce qui dit si vous ferez toute la maison d'une traite."),
 ("Batterie amovible", "Peut-on la changer ou en ajouter une ?", "Une batterie usée se remplace au lieu de jeter l'appareil."),
 ("Poids", "Poids en main avec la brosse", "Un aspirateur lourd fatigue vite le poignet."),
 ("Brosse anti-cheveux", "Système qui coupe ou évite les cheveux", "Évite de démêler la brosse aux ciseaux."),
 ("Filtration", "Filtre lavable, étanchéité", "Important pour les personnes allergiques."),
],
"tip": {"title": "Faire durer la batterie", "steps": [
 "Utilisez le mode normal au quotidien et gardez le mode fort pour les tapis.",
 "Rangez l'aspirateur sur son support pour qu'il soit toujours chargé.",
 "Videz le bac avant qu'il soit plein : l'aspiration baisse vite.",
 "Lavez le filtre une fois par mois et laissez-le sécher 24 heures."]},
"mistakes": [
 ("Croire l'autonomie maximale", "Elle est mesurée en mode éco, sans brosse motorisée."),
 ("Négliger le poids", "Un modèle lourd finit au placard."),
 ("Oublier le filtre", "Un filtre encrassé fait chuter la puissance."),
 ("Prendre une batterie non amovible", "Quand elle s'use, tout l'appareil devient inutilisable."),
],
"faq": [
 ("Un balai sans fil remplace-t-il un traîneau ?", "Oui pour la plupart des logements. Les modèles haut de gamme aspirent aussi bien les tapis épais."),
 ("Combien de temps dure une batterie ?", "En général plusieurs années. Une batterie amovible se remplace facilement ensuite."),
 ("Et pour les allergiques ?", "Choisissez un modèle avec une filtration étanche et un bac qui se vide sans contact."),
 ("Faut-il aussi un robot aspirateur ?", "Les deux se complètent : le robot fait l'entretien quotidien, le balai les coins, les escaliers et le canapé."),
],
},
# ---------------------------------------------------------------- NETTOYEUR DE SOLS
{
"slug": "aspirateur-laveur-sans-fil", "cat": "menage", "short": "Aspirateur laveur sans fil",
"title": "Aspirateur laveur sans fil 2026 : comparatif et avis",
"desc": "Aspirateur laveur sans fil : il aspire et lave en un seul passage. Notre comparatif de 4 modèles et les critères pour bien choisir.",
"h1": "Aspirateur laveur sans fil : aspirer et laver le sol en un seul passage",
"lede": "Deux réservoirs, un rouleau qui se rince seul, une station qui sèche : comment remplacer seau et serpillière par un seul appareil.",
"teaser": "Aspirer et laver en un seul passage.", "read": 8,
"pick": {"why": "Le plus abouti pour les sols durs : il ajuste l'eau selon la saleté et se nettoie tout seul sur sa base.",
         "alts": 'Petit budget ? Voir <a href="#p4">Kärcher FC</a>. Rouleau qui sèche à l\'air chaud ? Voir <a href="#p2">Dreame H-series</a>.'},
"table_cols": ["Auto-nettoyage", "Séchage"],
"products": [
 {"name": "Tineco Floor One", "brand": "Tineco", "badge": "Meilleur choix", "price": "€€€", "table": ["Oui", "Selon modèle"],
  "for": "les maisons avec beaucoup de carrelage ou de parquet vitrifié.",
  "pros": ["Capteur qui adapte l'eau à la saleté", "Auto-nettoyage sur la base", "Ramasse liquides et miettes"],
  "cons": ["Lourd", "Réservoir d'eau sale à rincer"],
  "specs": [("Auto-nettoyage", "Oui"), ("Séchage du rouleau", "Selon modèle"), ("Sols", "Durs uniquement"), ("Réservoirs", "Eau propre + eau sale")]},
 {"name": "Dreame H-series", "brand": "Dreame", "badge": "Séchage chaud", "price": "€€€", "table": ["Oui", "Air chaud"],
  "for": "ceux qui veulent un rouleau toujours propre et sans odeur.",
  "pros": ["Séchage du rouleau à l'air chaud", "Nettoie au ras des plinthes", "Bonne autonomie"],
  "cons": ["Encombrant", "Gamme difficile à suivre"],
  "specs": [("Auto-nettoyage", "Oui"), ("Séchage du rouleau", "Air chaud"), ("Sols", "Durs uniquement"), ("Réservoirs", "Eau propre + eau sale")]},
 {"name": "Dyson WashG1", "brand": "Dyson", "badge": "Sans brosse sale", "price": "€€€€", "table": ["Oui", "Non"],
  "for": "ceux qui ont surtout des taches humides et collantes.",
  "pros": ["Séparation des débris et de l'eau", "Rouleaux faciles à rincer", "Construction soignée"],
  "cons": ["Prix élevé", "N'aspire pas la poussière sèche fine"],
  "specs": [("Auto-nettoyage", "Oui"), ("Séchage du rouleau", "Non"), ("Sols", "Durs uniquement"), ("Réservoirs", "Eau propre + eau sale")]},
 {"name": "Kärcher FC", "brand": "Kärcher", "badge": "Petit budget", "price": "€€", "table": ["Selon modèle", "Non"],
  "for": "un appartement avec peu de surface à laver.",
  "pros": ["Marque fiable", "Prix plus accessible", "Simple à utiliser"],
  "cons": ["Moins d'automatismes", "Autonomie plus courte"],
  "specs": [("Auto-nettoyage", "Selon modèle"), ("Séchage du rouleau", "Non"), ("Sols", "Durs uniquement"), ("Réservoirs", "Eau propre + eau sale")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Ces appareils sont faits pour les sols durs. Sur un tapis ou une moquette, il faut un aspirateur classique.",
"criteria": [
 ("Auto-nettoyage", "Rinçage du rouleau sur la base", "Sinon il faut rincer le rouleau à la main après chaque usage."),
 ("Séchage", "Séchage du rouleau à l'air chaud", "Un rouleau humide prend vite une mauvaise odeur."),
 ("Bords", "Nettoyage au ras des plinthes", "C'est là que la saleté s'accumule."),
 ("Poids", "Poids en main", "Ces appareils sont plus lourds qu'un aspirateur balai."),
 ("Réservoirs", "Capacité eau propre et eau sale", "Détermine la surface lavée sans remplir."),
],
"tip": {"title": "Garder l'appareil sans odeur", "steps": [
 "Videz le réservoir d'eau sale juste après chaque usage.",
 "Lancez le cycle d'auto-nettoyage à chaque fois.",
 "Laissez le rouleau sécher, ou retirez-le s'il n'y a pas de séchage.",
 "Utilisez le produit recommandé, en petite quantité."]},
"mistakes": [
 ("L'utiliser sur un tapis", "Il est conçu pour les sols durs uniquement."),
 ("Laisser l'eau sale dans le réservoir", "C'est la cause numéro un des mauvaises odeurs."),
 ("Mettre trop de produit", "Le sol devient collant et garde des traces."),
 ("L'utiliser sur un parquet huilé", "Vérifiez que votre parquet supporte l'humidité."),
],
"faq": [
 ("Remplace-t-il l'aspirateur ?", "Sur les sols durs, en grande partie. Il faut un aspirateur pour les tapis et la poussière fine."),
 ("Est-ce compatible avec le parquet ?", "Oui pour un parquet vitrifié. Évitez-le sur un parquet huilé ou ciré."),
 ("Combien de temps sèche le sol ?", "Quelques minutes en général, car l'appareil aspire l'eau sale en même temps."),
 ("Robot laveur ou aspirateur laveur ?", "Le robot travaille seul au quotidien. L'aspirateur laveur est plus efficace sur les grosses salissures."),
],
},
# ---------------------------------------------------------------- AIRFRYER
{
"slug": "airfryer", "cat": "cuisine", "short": "Airfryer (friteuse sans huile)",
"title": "Airfryer 2026 : comparatif des friteuses sans huile",
"desc": "Quel airfryer choisir ? Capacité, double tiroir, nettoyage, consommation : notre comparatif de 4 friteuses sans huile pour cuisiner sans surveiller.",
"h1": "Airfryer : cuisiner vite, sans surveiller ni salir le four",
"lede": "Un ou deux tiroirs, capacité, programmes, facilité de nettoyage : comment choisir un airfryer qui simplifie vraiment les repas.",
"teaser": "Des repas prêts sans surveiller la cuisson.", "read": 8,
"pick": {"why": "Deux tiroirs indépendants qui finissent en même temps : le plat et l'accompagnement sont prêts ensemble, sans surveiller.",
         "alts": 'Petite cuisine ? Voir <a href="#p3">Cosori</a>. Petit budget ? Voir <a href="#p4">Moulinex Easy Fry</a>.'},
"table_cols": ["Tiroirs", "Pour"],
"products": [
 {"name": "Ninja Foodi Dual Zone", "brand": "Ninja", "badge": "Meilleur choix", "price": "€€€", "table": ["2", "Famille"],
  "for": "les familles qui veulent cuire plat et accompagnement en même temps.",
  "pros": ["Deux tiroirs qui finissent ensemble", "Grande capacité totale", "Paniers faciles à laver"],
  "cons": ["Encombrant sur le plan de travail", "Tiroirs étroits pour un poulet entier"],
  "specs": [("Tiroirs", "2"), ("Capacité", "Grande"), ("Lave-vaisselle", "Paniers oui"), ("Personnes", "4 et plus")]},
 {"name": "Philips Airfryer", "brand": "Philips", "badge": "Cuisson régulière", "price": "€€€", "table": ["1", "Famille"],
  "for": "ceux qui veulent la cuisson la plus homogène.",
  "pros": ["Cuisson très régulière", "Application de recettes", "Marque pionnière"],
  "cons": ["Un seul tiroir", "Prix élevé selon la taille"],
  "specs": [("Tiroirs", "1"), ("Capacité", "Moyenne à grande"), ("Lave-vaisselle", "Panier oui"), ("Personnes", "2 à 6")]},
 {"name": "Cosori", "brand": "Cosori", "badge": "Compact", "price": "€€", "table": ["1", "Couple"],
  "for": "un couple ou une petite cuisine.",
  "pros": ["Bon rapport qualité-prix", "Format compact", "Nombreux programmes"],
  "cons": ["Capacité limitée pour une famille", "Revêtement à ménager"],
  "specs": [("Tiroirs", "1"), ("Capacité", "Moyenne"), ("Lave-vaisselle", "Panier oui"), ("Personnes", "1 à 4")]},
 {"name": "Moulinex Easy Fry", "brand": "Moulinex", "badge": "Petit budget", "price": "€", "table": ["1", "Couple"],
  "for": "un premier airfryer à petit prix.",
  "pros": ["Prix accessible", "Simple à utiliser", "SAV en France"],
  "cons": ["Moins de programmes", "Cuisson moins régulière"],
  "specs": [("Tiroirs", "1"), ("Capacité", "Moyenne"), ("Lave-vaisselle", "Panier oui"), ("Personnes", "1 à 4")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Choisissez la capacité selon le nombre de personnes : un airfryer trop petit oblige à cuire en plusieurs fois.",
"criteria": [
 ("Capacité", "Volume du ou des tiroirs", "Comptez environ 1 litre par personne."),
 ("Double tiroir", "Deux zones indépendantes", "Permet de cuire deux aliments différents en même temps."),
 ("Nettoyage", "Panier compatible lave-vaisselle", "C'est ce qui fait qu'on l'utilise tous les jours."),
 ("Encombrement", "Dimensions sur le plan de travail", "Certains modèles prennent beaucoup de place."),
 ("Bruit", "Bruit du ventilateur", "Plus ou moins discret selon les modèles."),
],
"tip": {"title": "Réussir ses cuissons sans surveiller", "steps": [
 "Ne remplissez pas le panier à ras bord : l'air doit circuler.",
 "Ajoutez une cuillère d'huile pour les frites maison.",
 "Secouez le panier à mi-cuisson, ou programmez un rappel.",
 "Lavez le panier tout de suite, avant que le gras ne sèche."]},
"mistakes": [
 ("Trop remplir le panier", "Les aliments cuisent mal et restent mous."),
 ("Prendre trop petit", "Il faudra cuire en plusieurs fois pour une famille."),
 ("Utiliser des ustensiles en métal", "Ils rayent le revêtement antiadhésif."),
 ("Le coller au mur", "Il a besoin d'espace pour évacuer l'air chaud."),
],
"faq": [
 ("Un airfryer consomme-t-il moins qu'un four ?", "En général oui, car il chauffe plus vite un plus petit volume."),
 ("Peut-on tout cuire dedans ?", "Viandes, légumes, frites, poissons et même gâteaux. Les liquides et les pâtes humides sont à éviter."),
 ("Faut-il de l'huile ?", "Très peu, voire pas du tout selon les aliments."),
 ("Un ou deux tiroirs ?", "Deux tiroirs pour une famille ou pour cuire un repas complet. Un seul suffit pour un couple."),
],
},
# ---------------------------------------------------------------- ROBOT CUISEUR
{
"slug": "robot-cuiseur", "cat": "cuisine", "short": "Robot cuiseur multifonction",
"title": "Robot cuiseur multifonction 2026 : comparatif et avis",
"desc": "Robot cuiseur multifonction : il pèse, coupe, mélange et cuit. Notre comparatif de 4 modèles pour préparer les repas sans rester devant les casseroles.",
"h1": "Robot cuiseur : préparer les repas sans rester devant les casseroles",
"lede": "Recettes guidées, cuisson intégrée, nettoyage, prix : comment choisir un robot qui fait vraiment la cuisine à votre place.",
"teaser": "Les repas se préparent pendant que vous faites autre chose.", "read": 10,
"pick": {"why": "Le plus complet et le plus simple à suivre : les recettes guidées sur l'écran pèsent, coupent et cuisent étape par étape.",
         "alts": 'Petit budget ? Voir <a href="#p4">Monsieur Cuisine</a>. Envie de pâtisserie ? Voir <a href="#p3">Kenwood Cooking Chef</a>.'},
"table_cols": ["Recettes guidées", "Balance"],
"products": [
 {"name": "Thermomix", "brand": "Vorwerk", "badge": "Meilleur choix", "price": "€€€€", "table": ["Oui, très nombreuses", "Intégrée"],
  "for": "les familles qui cuisinent tous les jours.",
  "pros": ["Immense bibliothèque de recettes guidées", "Très polyvalent", "Revente facile d'occasion"],
  "cons": ["Prix très élevé", "Abonnement aux recettes"],
  "specs": [("Recettes guidées", "Oui, écran"), ("Balance", "Intégrée"), ("Cuisson", "Oui"), ("Vente", "Conseillers à domicile")]},
 {"name": "Moulinex Companion", "brand": "Moulinex", "badge": "Rapport qualité-prix", "price": "€€€", "table": ["Oui, application", "Selon modèle"],
  "for": "ceux qui veulent un robot cuiseur complet sans payer le prix fort.",
  "pros": ["Grande capacité", "Bon brassage pour les plats mijotés", "SAV en France"],
  "cons": ["Encombrant", "Balance absente sur certains modèles"],
  "specs": [("Recettes guidées", "Application"), ("Balance", "Selon modèle"), ("Cuisson", "Oui"), ("Vente", "Magasins")]},
 {"name": "Kenwood Cooking Chef", "brand": "Kenwood", "badge": "Pâtisserie", "price": "€€€€", "table": ["Oui, application", "Intégrée"],
  "for": "ceux qui font du pain et des gâteaux autant que des plats.",
  "pros": ["Excellent pétrissage", "Bol à induction", "Nombreux accessoires"],
  "cons": ["Très encombrant", "Prix élevé"],
  "specs": [("Recettes guidées", "Application"), ("Balance", "Intégrée"), ("Cuisson", "Induction"), ("Vente", "Magasins")]},
 {"name": "Monsieur Cuisine", "brand": "Silvercrest (Lidl)", "badge": "Petit budget", "price": "€€", "table": ["Selon modèle", "Intégrée"],
  "for": "découvrir le robot cuiseur sans gros investissement.",
  "pros": ["Prix très bas pour un robot complet", "Balance intégrée", "Recettes guidées sur les versions connectées"],
  "cons": ["Disponibilité par arrivages", "Finitions plus simples"],
  "specs": [("Recettes guidées", "Selon modèle"), ("Balance", "Intégrée"), ("Cuisson", "Oui"), ("Vente", "Arrivages Lidl")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Le vrai gain de temps vient des recettes guidées : elles évitent de chercher, de peser et de surveiller.",
"criteria": [
 ("Recettes guidées", "Écran intégré ou application", "Elles transforment le robot en cuisinier autonome."),
 ("Balance", "Balance intégrée au bol", "Évite de sortir une balance à chaque recette."),
 ("Capacité", "Volume utile du bol", "Une famille de quatre a besoin d'un grand bol."),
 ("Nettoyage", "Bol et lames au lave-vaisselle", "Sinon le gain de temps disparaît à la vaisselle."),
 ("Coût des recettes", "Abonnement payant ou gratuit", "Un abonnement s'ajoute au prix sur plusieurs années."),
],
"tip": {"title": "Gagner du temps toute la semaine", "steps": [
 "Choisissez trois ou quatre recettes simples pour commencer.",
 "Préparez une grande quantité le dimanche et congelez des portions.",
 "Lancez une cuisson pendant que vous faites autre chose.",
 "Rincez le bol à l'eau chaude dès la fin, avec le mode nettoyage s'il existe."]},
"mistakes": [
 ("Acheter sans essayer les recettes", "Vérifiez que les recettes proposées vous plaisent."),
 ("Oublier l'abonnement", "Certaines recettes sont payantes chaque année."),
 ("Prendre trop petit", "Un bol trop petit oblige à cuisiner deux fois."),
 ("Le ranger dans un placard", "Un robot rangé n'est jamais utilisé : prévoyez une place sur le plan de travail."),
],
"faq": [
 ("Un robot cuiseur remplace-t-il la cuisine classique ?", "Pour beaucoup de plats du quotidien, oui. Les grillades et les fritures restent à faire à part."),
 ("Est-ce rentable ?", "Si vous cuisinez souvent, il fait gagner du temps chaque jour et évite des plats préparés."),
 ("Faut-il une connexion Internet ?", "Pour les recettes guidées en ligne, oui. Les fonctions manuelles marchent sans."),
 ("Est-ce facile à nettoyer ?", "Le bol et les lames passent en général au lave-vaisselle."),
],
},
# ---------------------------------------------------------------- DEFROISSEUR
{
"slug": "defroisseur-vapeur", "cat": "linge", "short": "Défroisseur vapeur",
"title": "Défroisseur vapeur 2026 : comparatif pour ne plus repasser",
"desc": "Défroisseur vapeur à main ou sur pied : notre comparatif de 4 modèles pour défroisser chemises et robes en deux minutes, sans table à repasser.",
"h1": "Défroisseur vapeur : en finir avec la table à repasser",
"lede": "À main ou sur pied, temps de chauffe, puissance de vapeur : comment défroisser une chemise en deux minutes, sans sortir la planche.",
"teaser": "Des vêtements défroissés sans table à repasser.", "read": 7,
"pick": {"why": "Prêt en quelques secondes, léger, avec une vapeur suffisante pour les chemises : il remplace le fer pour le quotidien.",
         "alts": 'Beaucoup de linge ? Voir <a href="#p3">défroisseur sur pied</a>. Voyage ? Voir <a href="#p4">Steamery Cirrus</a>.'},
"table_cols": ["Format", "Chauffe"],
"products": [
 {"name": "Rowenta Access Steam", "brand": "Rowenta", "badge": "Meilleur choix", "price": "€€", "table": ["À main", "Rapide"],
  "for": "défroisser les vêtements du jour, chaque matin.",
  "pros": ["Chauffe rapide", "Vapeur régulière", "SAV en France"],
  "cons": ["Réservoir à remplir souvent", "Moins efficace sur le lin épais"],
  "specs": [("Format", "À main"), ("Chauffe", "Rapide"), ("Réservoir", "Petit"), ("Usage", "Quotidien")]},
 {"name": "Philips Steam&Go", "brand": "Philips", "badge": "Polyvalent", "price": "€€", "table": ["À main", "Rapide"],
  "for": "ceux qui veulent aussi rafraîchir rideaux et canapés.",
  "pros": ["Plaque chauffante qui évite les gouttes", "Utilisable sur les rideaux", "Sans risque de brûler le tissu"],
  "cons": ["Un peu lourd en main", "Bruyant"],
  "specs": [("Format", "À main"), ("Chauffe", "Rapide"), ("Réservoir", "Moyen"), ("Usage", "Vêtements, textiles")]},
 {"name": "Défroisseur sur pied (Calor, Rowenta)", "brand": "Plusieurs marques", "badge": "Gros volumes", "price": "€€€", "table": ["Sur pied", "Moyenne"],
  "for": "les familles qui défroissent beaucoup de linge.",
  "pros": ["Grand réservoir", "Vapeur continue puissante", "Cintre intégré"],
  "cons": ["Encombrant", "Plus long à chauffer"],
  "specs": [("Format", "Sur pied"), ("Chauffe", "Moyenne"), ("Réservoir", "Grand"), ("Usage", "Famille")]},
 {"name": "Steamery Cirrus", "brand": "Steamery", "badge": "Voyage", "price": "€€", "table": ["À main, compact", "Rapide"],
  "for": "les voyageurs et les petits espaces.",
  "pros": ["Très compact", "Design soigné", "Léger dans une valise"],
  "cons": ["Petit réservoir", "Prix élevé pour sa taille"],
  "specs": [("Format", "Compact"), ("Chauffe", "Rapide"), ("Réservoir", "Petit"), ("Usage", "Voyage")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Un défroisseur ne donne pas un pli net comme un fer, mais il suffit pour la grande majorité des vêtements du quotidien.",
"criteria": [
 ("Format", "À main ou sur pied", "À main pour le quotidien, sur pied pour les gros volumes."),
 ("Temps de chauffe", "Secondes avant la première vapeur", "Le matin, chaque minute compte."),
 ("Débit de vapeur", "Grammes par minute", "Plus le débit est fort, plus les plis partent vite."),
 ("Réservoir", "Volume et facilité de remplissage", "Un petit réservoir oblige à remplir en cours de route."),
 ("Anti-gouttes", "Plaque chauffante", "Évite de mouiller le vêtement."),
],
"tip": {"title": "Défroisser en deux minutes", "steps": [
 "Suspendez le vêtement sur un cintre, porte fermée.",
 "Tendez le tissu vers le bas avec la main libre.",
 "Passez la vapeur de haut en bas, sans appuyer.",
 "Laissez le vêtement sécher une minute avant de l'enfiler."]},
"mistakes": [
 ("Utiliser l'eau du robinet calcaire", "Le calcaire bouche l'appareil. Mélangez avec de l'eau déminéralisée."),
 ("Défroisser à plat", "La vapeur marche mieux sur un vêtement suspendu."),
 ("Approcher trop près de la soie", "Certains tissus fragiles demandent de la distance."),
 ("Attendre un pli de pantalon", "Pour un pli marqué, le fer reste nécessaire."),
],
"faq": [
 ("Un défroisseur remplace-t-il le fer ?", "Pour la plupart des vêtements du quotidien, oui. Pour un col très net ou un pli de pantalon, le fer reste meilleur."),
 ("Quels tissus peut-on défroisser ?", "Coton, polyester, laine, soie avec précaution. Évitez le cuir et le daim."),
 ("Est-ce que ça désodorise ?", "La vapeur rafraîchit les textiles et réduit certaines odeurs, sans remplacer un lavage."),
 ("Faut-il de l'eau déminéralisée ?", "Un mélange avec l'eau du robinet est souvent conseillé. Suivez la notice."),
],
},
# ---------------------------------------------------------------- LAVE-LINGE SECHANT
{
"slug": "lave-linge-sechant", "cat": "linge", "short": "Lave-linge séchant",
"title": "Lave-linge séchant 2026 : comparatif et guide d'achat",
"desc": "Lave-linge séchant : laver et sécher dans la même machine. Notre comparatif de 4 modèles pour les logements sans place pour deux appareils.",
"h1": "Lave-linge séchant : laver et sécher sans rien déplacer",
"lede": "Capacité en lavage et en séchage, durée des cycles, consommation : ce qu'il faut savoir avant de remplacer deux machines par une seule.",
"teaser": "Laver et sécher sans déplacer le linge.", "read": 8,
"pick": {"why": "Un cycle laver-sécher fiable, assez rapide, avec une bonne capacité de séchage : le linge sort sec et prêt à ranger.",
         "alts": 'Petit budget ? Voir <a href="#p4">Haier</a>. Grande famille ? Voir <a href="#p2">LG</a>.'},
"table_cols": ["Lavage / séchage", "Point fort"],
"products": [
 {"name": "Bosch Série 6 lavant-séchant", "brand": "Bosch", "badge": "Meilleur choix", "price": "€€€", "table": ["≈ 10 / 6 kg", "Fiabilité"],
  "for": "la plupart des familles qui manquent de place.",
  "pros": ["Fiable et bien fini", "Cycle laver-sécher en continu", "SAV répandu"],
  "cons": ["Cycles complets longs", "Prix élevé"],
  "specs": [("Lavage", "≈ 10 kg (" + "à vérifier" + ")"), ("Séchage", "≈ 6 kg"), ("Cycle continu", "Oui"), ("Pose", "Pose libre")]},
 {"name": "LG lavant-séchant", "brand": "LG", "badge": "Grande capacité", "price": "€€€", "table": ["Grande", "Capacité"],
  "for": "les grandes familles qui lavent beaucoup.",
  "pros": ["Grande capacité", "Moteur à entraînement direct, discret", "Programmes vapeur"],
  "cons": ["Application peu utile", "Encombrant en profondeur"],
  "specs": [("Lavage", "Grande capacité"), ("Séchage", "Selon modèle"), ("Cycle continu", "Oui"), ("Pose", "Pose libre")]},
 {"name": "Samsung lavant-séchant", "brand": "Samsung", "badge": "Connecté", "price": "€€€", "table": ["Grande", "Programmes"],
  "for": "ceux qui veulent piloter la machine à distance.",
  "pros": ["Nombreux programmes", "Suivi depuis le téléphone", "Design soigné"],
  "cons": ["Fiabilité variable selon les séries", "Cycles longs"],
  "specs": [("Lavage", "Grande capacité"), ("Séchage", "Selon modèle"), ("Cycle continu", "Oui"), ("Pose", "Pose libre")]},
 {"name": "Haier lavant-séchant", "brand": "Haier", "badge": "Petit budget", "price": "€€", "table": ["Moyenne", "Prix"],
  "for": "un premier lavant-séchant à prix contenu.",
  "pros": ["Prix accessible", "Bonne capacité pour le prix", "Moteur silencieux"],
  "cons": ["Finitions basiques", "SAV moins répandu"],
  "specs": [("Lavage", "Moyenne capacité"), ("Séchage", "Selon modèle"), ("Cycle continu", "Oui"), ("Pose", "Pose libre")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "La capacité de séchage est toujours plus petite que celle de lavage. Pour un cycle laver-sécher d'une traite, chargez selon la capacité de séchage.",
"criteria": [
 ("Capacité de séchage", "Kilos séchés en un cycle", "C'est elle qui limite un cycle laver-sécher continu."),
 ("Durée des cycles", "Durée d'un cycle complet", "Un cycle complet peut durer plusieurs heures."),
 ("Consommation", "Eau et électricité par cycle", "Le séchage par condensation consomme de l'eau."),
 ("Bruit", "Bruit en essorage et en séchage", "Important dans une cuisine ouverte."),
 ("Dimensions", "Profondeur réelle", "Les grandes capacités sont souvent plus profondes."),
],
"tip": {"title": "Linge sec et prêt à ranger", "steps": [
 "Chargez selon la capacité de séchage, pas de lavage.",
 "Choisissez le séchage « prêt à ranger » plutôt que « extra sec ».",
 "Sortez le linge dès la fin pour limiter les plis.",
 "Nettoyez le filtre de vidange tous les mois."]},
"mistakes": [
 ("Charger à la capacité de lavage", "Le linge ne sèche pas d'une traite."),
 ("Ignorer la durée", "Un cycle complet prend du temps : lancez-le la nuit ou en partant."),
 ("Oublier le filtre", "Un filtre bouché allonge les cycles."),
 ("Comparer seulement le prix", "Une machine fiable coûte moins cher sur dix ans."),
],
"faq": [
 ("Vaut-il mieux deux machines séparées ?", "Si vous avez la place, oui : c'est plus rapide et plus économe. Le lavant-séchant est la solution quand la place manque."),
 ("Peut-on laver sans sécher ?", "Oui, il fonctionne aussi comme un lave-linge classique."),
 ("Consomme-t-il beaucoup ?", "Le séchage consomme plus qu'un sèche-linge pompe à chaleur. Le lavage seul est comparable à un lave-linge."),
 ("Le linge est-il froissé ?", "Moins qu'un linge étendu, surtout si on le sort dès la fin du cycle."),
],
},
# ---------------------------------------------------------------- FONTAINE CHAT
{
"slug": "fontaine-eau-chat", "cat": "animaux", "short": "Fontaine à eau pour chat",
"title": "Fontaine à eau pour chat 2026 : comparatif et conseils",
"desc": "Fontaine à eau pour chat : filtration, bruit, nettoyage, pompe sans fil. Notre comparatif de 4 fontaines pour une eau fraîche sans y penser.",
"h1": "Fontaine à eau pour chat : de l'eau fraîche sans changer la gamelle",
"lede": "Filtre, bruit de la pompe, volume, facilité de nettoyage : comment choisir une fontaine qui fait boire votre chat et vous évite de changer l'eau chaque jour.",
"teaser": "De l'eau fraîche sans changer la gamelle.", "read": 7,
"pick": {"why": "Silencieuse, avec une pompe sans fil dans l'eau et un réservoir qui tient plusieurs jours : le meilleur équilibre.",
         "alts": 'Petit budget ? Voir <a href="#p2">Catit Flower</a>. Plusieurs animaux ? Voir <a href="#p4">PetSafe Drinkwell</a>.'},
"table_cols": ["Pompe", "Nettoyage"],
"products": [
 {"name": "Petkit Eversweet", "brand": "Petkit", "badge": "Meilleur choix", "price": "€€", "table": ["Sans fil dans l'eau", "Facile"],
  "for": "la plupart des chats, surtout ceux qui boivent peu.",
  "pros": ["Pompe sans fil, plus sûre", "Très silencieuse", "Suivi de la consommation sur certains modèles"],
  "cons": ["Filtres de la marque à racheter", "Prix plus élevé"],
  "specs": [("Pompe", "Sans fil (induction)"), ("Filtre", "Oui"), ("Bruit", "Très faible"), ("Animaux", "1 à 2 chats")]},
 {"name": "Catit Flower", "brand": "Catit", "badge": "Petit budget", "price": "€", "table": ["Filaire", "Moyen"],
  "for": "un premier essai de fontaine à petit prix.",
  "pros": ["Prix accessible", "Plusieurs modes d'écoulement", "Filtres faciles à trouver"],
  "cons": ["Nombreuses pièces à laver", "Réservoir assez petit"],
  "specs": [("Pompe", "Filaire"), ("Filtre", "Oui"), ("Bruit", "Faible"), ("Animaux", "1 chat")]},
 {"name": "Xiaomi Smart Pet Fountain", "brand": "Xiaomi", "badge": "Connectée", "price": "€€", "table": ["Filaire", "Facile"],
  "for": "ceux qui veulent une alerte quand l'eau manque.",
  "pros": ["Alerte de niveau d'eau", "Design discret", "Prix raisonnable"],
  "cons": ["Application peu utile au quotidien", "Disponibilité variable"],
  "specs": [("Pompe", "Filaire"), ("Filtre", "Oui"), ("Bruit", "Faible"), ("Animaux", "1 à 2 chats")]},
 {"name": "PetSafe Drinkwell", "brand": "PetSafe", "badge": "Plusieurs animaux", "price": "€€", "table": ["Filaire", "Moyen"],
  "for": "les foyers avec plusieurs chats ou un petit chien.",
  "pros": ["Grand volume d'eau", "Robuste", "Plusieurs points d'eau"],
  "cons": ["Plus bruyante", "Encombrante"],
  "specs": [("Pompe", "Filaire"), ("Filtre", "Oui"), ("Bruit", "Moyen"), ("Animaux", "Plusieurs")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Les chats boivent souvent trop peu. Une eau qui coule et reste fraîche les incite à boire davantage.",
"criteria": [
 ("Pompe", "Filaire ou sans fil dans l'eau", "Une pompe sans fil évite qu'un câble traîne dans l'eau."),
 ("Bruit", "Bruit de la pompe et de l'eau", "Un chat craintif fuit une fontaine bruyante."),
 ("Nettoyage", "Nombre de pièces, lave-vaisselle", "Une fontaine sale est pire qu'une gamelle."),
 ("Volume", "Litres d'eau", "Détermine la fréquence de remplissage."),
 ("Coût des filtres", "Prix et durée de vie des filtres", "C'est le vrai coût sur un an."),
],
"tip": {"title": "Faire adopter la fontaine", "steps": [
 "Placez la fontaine loin de la litière et de la gamelle de croquettes.",
 "Laissez l'ancienne gamelle d'eau à côté quelques jours.",
 "Commencez par un écoulement doux.",
 "Nettoyez la fontaine chaque semaine et changez le filtre selon la notice."]},
"mistakes": [
 ("La placer près de la litière", "Les chats évitent de boire près de leurs toilettes."),
 ("Ne jamais la nettoyer", "Un biofilm se forme vite dans la pompe."),
 ("Oublier les filtres", "Un filtre usé ne filtre plus rien."),
 ("Choisir une fontaine bruyante", "Un chat sensible au bruit ne s'en approchera pas."),
],
"faq": [
 ("Une fontaine fait-elle vraiment boire plus ?", "Beaucoup de chats boivent davantage avec une eau qui coule, ce qui aide à prévenir certains problèmes urinaires."),
 ("Tous les combien la nettoyer ?", "Une fois par semaine en général, pompe comprise."),
 ("Consomme-t-elle beaucoup d'électricité ?", "Très peu : la pompe a une puissance de quelques watts."),
 ("Convient-elle aux chiens ?", "Les grands modèles oui. Pour un grand chien, choisissez un grand volume."),
],
},
# ---------------------------------------------------------------- HAUTE PRESSION
{
"slug": "nettoyeur-haute-pression", "cat": "jardin", "short": "Nettoyeur haute pression",
"title": "Nettoyeur haute pression 2026 : comparatif pour terrasse et voiture",
"desc": "Quel nettoyeur haute pression choisir pour la terrasse, la voiture ou la façade ? Notre comparatif de 4 modèles et les critères à connaître.",
"h1": "Nettoyeur haute pression : la terrasse propre en une heure, pas en un week-end",
"lede": "Pression, débit, moteur, accessoires pour terrasse : comment choisir un nettoyeur qui fait le travail sans abîmer les surfaces.",
"teaser": "Une terrasse propre en une heure.", "read": 8,
"pick": {"why": "La puissance qu'il faut pour une terrasse et une voiture, avec un nettoyeur de surfaces qui évite les traces.",
         "alts": 'Petit budget ? Voir <a href="#p4">Bosch EasyAquatak</a>. Sans prise ? Voir <a href="#p3">Worx Hydroshot</a>.'},
"table_cols": ["Usage", "Alimentation"],
"products": [
 {"name": "Kärcher K5", "brand": "Kärcher", "badge": "Meilleur choix", "price": "€€€", "table": ["Terrasse, voiture, façade", "Secteur"],
  "for": "une maison avec terrasse, allées et voiture.",
  "pros": ["Puissance suffisante pour la plupart des usages", "Nombreux accessoires compatibles", "Marque de référence"],
  "cons": ["Lourd", "Accessoire terrasse parfois en option"],
  "specs": [("Usage", "Polyvalent"), ("Alimentation", "Secteur"), ("Moteur", "Refroidi à l'eau"), ("Terrasse", "Accessoire dédié")]},
 {"name": "Nilfisk Core", "brand": "Nilfisk", "badge": "Robuste", "price": "€€", "table": ["Terrasse, voiture", "Secteur"],
  "for": "un usage régulier sur grandes surfaces.",
  "pros": ["Construction robuste", "Bon débit", "Enrouleur de tuyau pratique"],
  "cons": ["Encombrant", "Moins d'accessoires en magasin"],
  "specs": [("Usage", "Polyvalent"), ("Alimentation", "Secteur"), ("Moteur", "Selon modèle"), ("Terrasse", "Accessoire dédié")]},
 {"name": "Worx Hydroshot", "brand": "Worx", "badge": "Sans fil", "price": "€€", "table": ["Voiture, vélo, mobilier", "Batterie"],
  "for": "nettoyer sans prise ni robinet à proximité.",
  "pros": ["Fonctionne sur batterie", "Peut puiser dans un seau", "Léger"],
  "cons": ["Pression limitée", "Pas fait pour une grande terrasse"],
  "specs": [("Usage", "Léger"), ("Alimentation", "Batterie"), ("Moteur", "Compact"), ("Terrasse", "Petites surfaces")]},
 {"name": "Bosch EasyAquatak", "brand": "Bosch", "badge": "Petit budget", "price": "€", "table": ["Voiture, mobilier", "Secteur"],
  "for": "un usage occasionnel sur petites surfaces.",
  "pros": ["Prix accessible", "Léger et compact", "Simple à ranger"],
  "cons": ["Pression modeste", "Moins durable en usage intensif"],
  "specs": [("Usage", "Occasionnel"), ("Alimentation", "Secteur"), ("Moteur", "Compact"), ("Terrasse", "Petites surfaces")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "La pression maximale n'est pas tout : le débit d'eau compte autant pour décrocher la saleté et rincer vite.",
"criteria": [
 ("Pression", "Pression en bars", "Assez forte pour la terrasse, sans abîmer le bois tendre."),
 ("Débit", "Litres par heure", "Plus le débit est élevé, plus le rinçage est rapide."),
 ("Nettoyeur de surfaces", "Accessoire terrasse rotatif", "Il évite les traces en zigzag sur les dalles."),
 ("Moteur", "Moteur à induction refroidi à l'eau", "Plus durable pour un usage régulier."),
 ("Tuyau", "Longueur et enrouleur", "Évite de déplacer la machine sans arrêt."),
],
"tip": {"title": "Nettoyer une terrasse sans l'abîmer", "steps": [
 "Balayez d'abord les feuilles et la terre.",
 "Testez la pression sur un coin peu visible.",
 "Utilisez le nettoyeur de surfaces, à vitesse régulière.",
 "Rincez du haut vers le bas, puis laissez sécher avant d'appliquer un traitement."]},
"mistakes": [
 ("Tenir la buse trop près", "Le jet peut creuser le bois et les joints."),
 ("L'utiliser sur un crépi fragile", "Vérifiez que la façade supporte la haute pression."),
 ("Oublier le gel", "Videz l'appareil et rangez-le hors gel l'hiver."),
 ("Choisir à la pression seule", "Le débit et les accessoires comptent autant."),
],
"faq": [
 ("Peut-on laver sa voiture au nettoyeur haute pression ?", "Oui, à distance raisonnable et avec la buse adaptée. Vérifiez si c'est autorisé chez vous."),
 ("Faut-il du détergent ?", "Pas toujours. Pour une terrasse très encrassée, un produit adapté facilite le travail."),
 ("Consomme-t-il beaucoup d'eau ?", "Moins qu'un tuyau d'arrosage pour le même travail, car il nettoie plus vite."),
 ("Et pour le bois ?", "Utilisez une pression réduite et gardez de la distance pour ne pas relever les fibres."),
],
},
# ---------------------------------------------------------------- ARROSAGE
{
"slug": "programmateur-arrosage", "cat": "jardin", "short": "Programmateur d'arrosage",
"title": "Programmateur d'arrosage 2026 : comparatif connecté ou mécanique",
"desc": "Programmateur d'arrosage automatique connecté ou simple : notre comparatif de 4 modèles pour arroser le jardin sans y penser, même en vacances.",
"h1": "Programmateur d'arrosage : arroser le jardin sans y penser",
"lede": "Mécanique, électronique ou connecté, nombre de voies, capteur de pluie : comment automatiser l'arrosage pour quelques dizaines d'euros.",
"teaser": "Le jardin s'arrose tout seul, même en vacances.", "read": 7,
"pick": {"why": "Simple à installer sur un robinet, pilotable depuis le téléphone, et capable de sauter un arrosage quand il pleut.",
         "alts": 'Sans application ? Voir <a href="#p3">Hozelock</a>. Plusieurs zones ? Voir <a href="#p2">Rain Bird</a>.'},
"table_cols": ["Type", "Voies"],
"products": [
 {"name": "Gardena Smart Water Control", "brand": "Gardena", "badge": "Meilleur choix", "price": "€€€", "table": ["Connecté", "1"],
  "for": "un jardin arrosé depuis un robinet extérieur.",
  "pros": ["Pilotage depuis le téléphone", "Ajustement selon la météo", "Écosystème d'accessoires"],
  "cons": ["Passerelle nécessaire", "Prix plus élevé"],
  "specs": [("Type", "Connecté"), ("Voies", "1"), ("Alimentation", "Piles"), ("Capteur de pluie", "Compatible")]},
 {"name": "Rain Bird (programmateurs multi-zones)", "brand": "Rain Bird", "badge": "Multi-zones", "price": "€€", "table": ["Électronique", "Plusieurs"],
  "for": "un arrosage enterré avec plusieurs zones.",
  "pros": ["Gère plusieurs zones", "Très fiable", "Référence chez les pros"],
  "cons": ["Installation plus technique", "Électrovannes à prévoir"],
  "specs": [("Type", "Électronique"), ("Voies", "Plusieurs"), ("Alimentation", "Secteur"), ("Capteur de pluie", "Compatible")]},
 {"name": "Hozelock", "brand": "Hozelock", "badge": "Sans application", "price": "€", "table": ["Électronique", "1 ou 2"],
  "for": "ceux qui veulent juste arroser à heure fixe.",
  "pros": ["Prix accessible", "Programmation simple", "Aucun compte ni application"],
  "cons": ["Pas de réglage à distance", "Programmes limités"],
  "specs": [("Type", "Électronique"), ("Voies", "1 ou 2"), ("Alimentation", "Piles"), ("Capteur de pluie", "Selon modèle")]},
 {"name": "Linktap", "brand": "Linktap", "badge": "Longue portée", "price": "€€", "table": ["Connecté", "1"],
  "for": "un robinet éloigné de la maison et du Wi-Fi.",
  "pros": ["Grande portée radio", "Mesure du débit, alerte de fuite", "Application complète"],
  "cons": ["Passerelle nécessaire", "Marque moins connue"],
  "specs": [("Type", "Connecté"), ("Voies", "1"), ("Alimentation", "Piles"), ("Capteur de pluie", "Via météo")]},
],
"criteria_title": "Les critères qui font la différence",
"criteria_intro": "Commencez par compter vos zones d'arrosage et vérifier où se trouve votre robinet par rapport au Wi-Fi.",
"criteria": [
 ("Type", "Mécanique, électronique ou connecté", "Le connecté permet d'ajuster à distance et selon la météo."),
 ("Nombre de voies", "Combien de zones arrosées séparément", "Pelouse et potager n'ont pas les mêmes besoins."),
 ("Portée", "Distance au Wi-Fi ou à la passerelle", "Un robinet au fond du jardin peut être hors de portée."),
 ("Capteur de pluie", "Arrêt automatique en cas de pluie", "Évite d'arroser pour rien."),
 ("Alimentation", "Piles ou secteur", "Des piles faibles et l'arrosage s'arrête."),
],
"tip": {"title": "Arroser mieux avec moins d'eau", "steps": [
 "Arrosez tôt le matin pour limiter l'évaporation.",
 "Préférez des arrosages longs et espacés à de petits arrosages quotidiens.",
 "Installez un goutte-à-goutte pour le potager et les massifs.",
 "Changez les piles au début de chaque saison."]},
"mistakes": [
 ("Arroser en plein soleil", "Une grande partie de l'eau s'évapore."),
 ("Oublier les restrictions d'eau", "Vérifiez les arrêtés sécheresse de votre commune."),
 ("Laisser le programmateur dehors l'hiver", "Le gel le casse : rentrez-le."),
 ("Une seule zone pour tout", "Pelouse et plantes en pot n'ont pas les mêmes besoins."),
],
"faq": [
 ("Faut-il un plombier ?", "Non pour un programmateur de robinet : il se visse simplement. Un arrosage enterré multi-zones demande plus de travail."),
 ("Fonctionne-t-il pendant les vacances ?", "Oui, c'est même son principal intérêt. Vérifiez les piles avant de partir."),
 ("Et en cas de restriction d'eau ?", "Les modèles connectés permettent de suspendre ou d'adapter les horaires à distance."),
 ("Peut-on l'utiliser avec un récupérateur d'eau de pluie ?", "Oui, avec une pompe adaptée qui fournit assez de pression."),
],
},
]
