# Guides : cuiseur à riz, robot tondeuse pas cher, désherbeur électrique, litière autonettoyante pas cher.

GUIDES5B = [
{
"slug": "cuiseur-riz", "cat": "cuisine", "short": "Cuiseur à riz automatique",
"title": "Cuiseur à riz automatique 2026 : comparatif et conseils d'achat",
"desc": "Quel cuiseur à riz choisir ? Notre comparatif de 5 modèles, du simple cuiseur au multicuiseur, avec cuisson vapeur, maintien au chaud et conseils d'achat.",
"h1": "Cuiseur à riz automatique : du riz réussi sans surveiller la casserole",
"lede": "On remplit, on appuie, et l'appareil s'arrête seul quand le riz est cuit. Voici comment choisir selon le nombre de personnes et ce que vous cuisinez d'autre que du riz.",
"teaser": "Un riz parfait, sans casserole à surveiller.", "read": 7,
"pick": {"why": "Un cuiseur multifonction qui fait le riz, mais aussi la vapeur et plusieurs programmes, avec maintien au chaud : le plus polyvalent pour une famille.",
         "alts": 'Petit budget ? Voir <a href="#p3">Tefal RK1011</a>. Riz de haute qualité ? Voir <a href="#p4">Zojirushi</a>. Surtout de la vapeur ? Voir <a href="#p5">cuiseur vapeur</a>.'},
"table_cols": ["Type", "Particularité"],
"products": [
 {"name": "Tefal Easy Rice 8in1 RK7321", "brand": "Tefal", "badge": "Meilleur choix", "price": "€€", "table": ["Cuiseur multifonction", "Plusieurs programmes"],
  "for": "une famille qui mange du riz souvent et veut aussi cuire d'autres céréales ou à la vapeur.",
  "pros": ["Plusieurs programmes selon le riz et les céréales", "Cuisson vapeur possible", "Maintien au chaud automatique"],
  "cons": ["Plus encombrant qu'un cuiseur simple", "Programmes à apprivoiser au début"],
  "specs": [("Type", "Cuiseur multifonction"), ("Capacité", "Grande (famille)"), ("Vapeur", "Oui"), ("Maintien au chaud", "Oui")]},
 {"name": "Tefal RK8121 multicuiseur", "brand": "Tefal", "badge": "Multicuiseur", "price": "€€", "table": ["Multicuiseur à écran", "Nombreux programmes"],
  "for": "ceux qui veulent un appareil pour le riz, les soupes, les céréales et les mijotés.",
  "pros": ["Écran et nombreuses fonctions de cuisson", "Départ différé possible", "Livré avec un livre de recettes"],
  "cons": ["Beaucoup de fonctions dont on n'utilise qu'une partie", "Plus cher qu'un cuiseur à riz simple"],
  "specs": [("Type", "Multicuiseur"), ("Capacité", "Grande (famille)"), ("Vapeur", "Oui"), ("Maintien au chaud", "Oui")]},
 {"name": "Tefal RK1011", "brand": "Tefal", "badge": "Petit budget", "price": "€", "table": ["Cuiseur simple", "Prix bas"],
  "for": "un usage de temps en temps, pour une à trois personnes.",
  "pros": ["Simple : un seul bouton", "Prix bas", "Cuve antiadhésive facile à laver"],
  "cons": ["Moins de réglages", "Peu adapté à une grande famille"],
  "specs": [("Type", "Cuiseur simple"), ("Capacité", "Petite à moyenne"), ("Vapeur", "Selon accessoire"), ("Maintien au chaud", "Oui")]},
 {"name": "Zojirushi NS-TSC10", "brand": "Zojirushi", "badge": "Riz haut de gamme", "price": "€€€", "table": ["Cuiseur à microprocesseur", "Riz japonais"],
  "for": "les amateurs de riz, notamment japonais, prêts à investir.",
  "pros": ["Cuisson réglée par microprocesseur", "Réputation de fiabilité et de riz très régulier", "Maintien au chaud soigné"],
  "cons": ["Prix élevé", "Notice et menus pas toujours en français selon la version"],
  "specs": [("Type", "Cuiseur à microprocesseur"), ("Capacité", "Environ 1 L (5,5 tasses)"), ("Vapeur", "Non"), ("Maintien au chaud", "Oui")]},
 {"name": "Tefal Convenient Series VC502D10 (cuiseur vapeur)", "brand": "Tefal", "badge": "Surtout vapeur", "price": "€€", "table": ["Cuiseur vapeur", "Plusieurs paniers"],
  "for": "ceux qui cuisinent surtout légumes et poisson à la vapeur, avec un peu de riz.",
  "pros": ["Plusieurs paniers pour cuire des aliments différents", "Minuterie intégrée", "Cuisine saine, sans matière grasse"],
  "cons": ["Ne remplace pas un vrai cuiseur à riz", "Prend de la place sur le plan de travail"],
  "specs": [("Type", "Cuiseur vapeur"), ("Capacité", "Plusieurs paniers"), ("Vapeur", "Oui"), ("Maintien au chaud", "Selon modèle")]},
],
"criteria_title": "Choisir son cuiseur à riz",
"criteria_intro": "Pensez au nombre de personnes à table et à ce que vous mangez en dehors du riz. Un cuiseur trop grand cuit mal les petites quantités.",
"criteria": [
 ("Capacité", "Une à deux personnes, ou famille", "Un petit cuiseur cuit bien 1 à 3 portions ; au-delà, prenez plus grand."),
 ("Programmes", "Riz blanc, complet, céréales, vapeur", "Le riz complet et les céréales demandent un temps de cuisson plus long."),
 ("Maintien au chaud", "Bascule automatique après cuisson", "Le riz reste chaud sans se dessécher pendant un moment."),
 ("Cuve", "Antiadhésive ou inox", "Une cuve amovible se lave au lavabo en une minute."),
],
"tip": {"title": "Un riz bien cuit à chaque fois", "steps": [
 "Rincez le riz à l'eau claire jusqu'à ce qu'elle soit presque limpide.",
 "Respectez la graduation de la cuve, plutôt qu'un dosage au hasard.",
 "Ne soulevez pas le couvercle pendant la cuisson.",
 "Laissez reposer cinq minutes après la fin, puis égrainez à la fourchette."]},
"mistakes": [
 ("Ne pas rincer le riz", "L'amidon en surface rend le riz collant."),
 ("Trop d'eau", "Suivez les repères de la cuve : le riz sera pâteux sinon."),
 ("Laisser le riz des jours en maintien au chaud", "Il sèche et jaunit : servez-le dans les heures qui suivent."),
 ("Mettre la cuve au lave-vaisselle sans vérifier", "Le revêtement antiadhésif peut s'abîmer : consultez la notice."),
],
"faq": [
 ("Un cuiseur à riz vaut-il mieux qu'une casserole ?", "Il évite la surveillance, s'arrête seul et garde le riz chaud. Pour du riz de temps en temps, la casserole suffit."),
 ("Peut-on cuire autre chose que du riz ?", "Oui, selon le modèle : quinoa, céréales, légumes à la vapeur, parfois soupes et mijotés."),
 ("Quelle capacité pour une famille de quatre ?", "Visez un modèle de grande capacité, de l'ordre de 1,5 à 1,8 L ou plus."),
 ("Comment nettoyer la cuve ?", "À la main, avec une éponge douce, sans gratter le revêtement."),
],
},
{
"slug": "robot-tondeuse-pas-cher", "cat": "jardin", "short": "Robot tondeuse pas cher",
"title": "Robot tondeuse pas cher 2026 : petit jardin, petit budget",
"desc": "Robot tondeuse à petit prix pour petit jardin : notre comparatif de 5 modèles avec fil périphérique, de 250 à 500 m², et nos conseils pour bien l'installer.",
"h1": "Robot tondeuse pas cher : tondre un petit jardin sans se ruiner",
"lede": "Pour un jardin de quelques centaines de mètres carrés, inutile de payer un robot haut de gamme. Les modèles à fil périphérique restent les moins chers et les plus fiables.",
"teaser": "Une pelouse tondue sans vous, à budget maîtrisé.", "read": 7,
"pick": {"why": "Un robot silencieux, simple à installer et à régler avec son application Bluetooth, taillé pour un petit terrain sans pente forte.",
         "alts": 'Jardin de 300 m² avec appli complète ? Voir <a href="#p3">Worx Landroid S</a>. Terrain plus grand ? Voir <a href="#p4">Einhell Freelexo 500 BT</a>.'},
"table_cols": ["Surface", "Pilotage"],
"products": [
 {"name": "Gardena Sileno Minimo 250", "brand": "Gardena", "badge": "Meilleur choix", "price": "€€", "table": ["Environ 250 m²", "Bluetooth"],
  "for": "les petits jardins plats, sans parcours compliqué.",
  "pros": ["Silencieux", "Réglage par application Bluetooth", "Installation simple avec fil périphérique"],
  "cons": ["Surface limitée, pas pour un grand terrain", "Pas fait pour les pentes marquées"],
  "specs": [("Surface", "Environ 250 m²"), ("Pilotage", "Application Bluetooth"), ("Délimitation", "Fil périphérique"), ("Pente", "Faible")]},
 {"name": "Yard Force Compact 280R", "brand": "Yard Force", "badge": "Petit prix", "price": "€", "table": ["Environ 280 m²", "Boutons / programmation"],
  "for": "ceux qui veulent le prix le plus bas pour un petit terrain.",
  "pros": ["Prix d'entrée bas", "Capteurs à ultrasons pour éviter les obstacles", "Compact"],
  "cons": ["Moins de fonctions connectées", "Prise en main moins soignée qu'une grande marque"],
  "specs": [("Surface", "Environ 280 m²"), ("Pilotage", "Boutons sur l'appareil"), ("Délimitation", "Fil périphérique"), ("Pente", "Faible")]},
 {"name": "Worx Landroid S WR130E", "brand": "Worx", "badge": "Appli complète", "price": "€€", "table": ["Environ 300 m²", "Application Wi-Fi"],
  "for": "un jardin d'environ 300 m² que l'on veut piloter à distance.",
  "pros": ["Application complète", "Tond sous la pluie selon réglage", "Plusieurs zones possibles"],
  "cons": ["Un peu plus bruyant qu'un Gardena", "Installation du fil à soigner"],
  "specs": [("Surface", "Environ 300 m²"), ("Pilotage", "Application"), ("Délimitation", "Fil périphérique"), ("Pente", "Modérée")]},
 {"name": "Einhell FREELEXO 500 BT", "brand": "Einhell", "badge": "Terrain moyen", "price": "€€", "table": ["Environ 500 m²", "Bluetooth"],
  "for": "un terrain un peu plus grand, avec plusieurs zones.",
  "pros": ["Surface plus grande pour le prix", "Fonctionne avec les batteries Power X-Change Einhell", "Gestion de plusieurs zones"],
  "cons": ["Un peu plus cher que les modèles de 250 m²", "Installation plus longue sur un grand terrain"],
  "specs": [("Surface", "Environ 500 m²"), ("Pilotage", "Application Bluetooth"), ("Délimitation", "Fil périphérique"), ("Pente", "Modérée")]},
 {"name": "Bosch Indego S+ 500", "brand": "Bosch", "badge": "Un cran au-dessus", "price": "€€€", "table": ["Environ 500 m²", "Application"],
  "for": "ceux qui veulent un robot plus sophistiqué, à la tonte plus régulière.",
  "pros": ["Tonte en lignes parallèles, plus régulière", "Application de pilotage", "Marque reconnue"],
  "cons": ["Plus cher que les autres modèles du comparatif", "Fil périphérique tout de même nécessaire"],
  "specs": [("Surface", "Environ 500 m²"), ("Pilotage", "Application"), ("Délimitation", "Fil périphérique"), ("Pente", "Modérée")]},
],
"criteria_title": "Bien choisir un robot tondeuse à petit prix",
"criteria_intro": "Le fil périphérique demande une heure ou deux d'installation, mais c'est ce qui rend ces robots abordables. Surveillez surtout la surface annoncée.",
"criteria": [
 ("Surface", "Jardin réel, avec marge", "Prenez un modèle annoncé un peu au-dessus de votre surface : il tondra moins de temps."),
 ("Pente", "Terrain plat ou incliné", "Les modèles d'entrée de gamme supportent mal les pentes fortes."),
 ("Pilotage", "Boutons, Bluetooth ou Wi-Fi", "Le Bluetooth suffit pour programmer ; le Wi-Fi permet de piloter à distance."),
 ("Obstacles", "Massifs, arbres, bassin", "Un fil bien posé autour des zones à protéger compte plus que le modèle."),
],
"tip": {"title": "Poser le fil périphérique sans stress", "steps": [
 "Tondez court une dernière fois avant de poser le fil.",
 "Placez la borne de charge sur un terrain plat, près d'une prise extérieure.",
 "Fixez le fil avec les piquets à environ 30 cm du bord, plus loin des obstacles.",
 "Testez un cycle complet et corrigez les passages où le robot se coince."]},
"mistakes": [
 ("Choisir trop juste en surface", "Le robot n'aura pas le temps de tout tondre chaque semaine."),
 ("Laisser des obstacles sans protection", "Jouets, tuyaux et pierres abîment les lames."),
 ("Oublier de nettoyer le dessous", "L'herbe collée finit par freiner le robot."),
 ("Ne pas rentrer le robot l'hiver", "La batterie supporte mal le gel prolongé."),
],
"faq": [
 ("Un robot tondeuse pas cher est-il fiable ?", "Oui pour un petit terrain plat. Les différences se jouent sur le bruit, l'application et les pentes."),
 ("Faut-il vraiment un fil périphérique ?", "C'est ce qui rend ces modèles abordables. Les robots sans fil existent mais coûtent plus cher : voir notre guide dédié."),
 ("Le robot tond-il sous la pluie ?", "Selon le modèle et le réglage. L'herbe mouillée est tondue moins proprement."),
 ("Peut-on le laisser dehors toute l'année ?", "La station peut rester dehors, mais mieux vaut rentrer le robot pour l'hiver."),
],
},
{
"slug": "desherbeur-electrique", "cat": "jardin", "short": "Désherbeur électrique et thermique",
"title": "Désherbeur électrique 2026 : désherber sans produit chimique",
"desc": "Désherbeur électrique, thermique à gaz ou brosse pour joints de terrasse : notre comparatif de 5 solutions pour éliminer les mauvaises herbes sans pesticides.",
"h1": "Désherbeur électrique : arracher les mauvaises herbes sans produit chimique",
"lede": "Chaleur, brosse rotative ou gaz : plusieurs outils remplacent le désherbant. Voici lequel choisir selon la surface et l'endroit à désherber.",
"teaser": "Des allées propres, sans désherbant.", "read": 6,
"pick": {"why": "Un désherbeur électrique à éléments céramiques, sans flamme : il chauffe les herbes plutôt que de les brûler, et il se branche simplement sur le secteur.",
         "alts": 'Grande surface ? Voir <a href="#p2">Hozelock XL</a>. Joints de terrasse ? Voir <a href="#p5">brosse électrique</a>. Pas de prise ? Voir <a href="#p4">désherbeur à gaz</a>.'},
"table_cols": ["Énergie", "Usage"],
"products": [
 {"name": "Hozelock Green Power Evolution Plus", "brand": "Hozelock", "badge": "Meilleur choix", "price": "€€", "table": ["Électrique", "Allées, terrasses"],
  "for": "les allées, cours et bordures d'un jardin moyen.",
  "pros": ["Sans flamme, éléments chauffants en céramique", "Aucun produit chimique", "Léger et simple à utiliser"],
  "cons": ["Il faut une prise et une rallonge", "Plusieurs passages sur les herbes vivaces"],
  "specs": [("Énergie", "Électrique (secteur)"), ("Usage", "Allées, cours, bordures"), ("Flamme", "Non"), ("Cible", "Jeunes pousses, annuelles")]},
 {"name": "Hozelock Désherbeur électrique XL", "brand": "Hozelock", "badge": "Grande surface", "price": "€€", "table": ["Électrique", "Grandes allées"],
  "for": "de grandes surfaces à désherber, avec un capot plus large.",
  "pros": ["Capot large, couvre plus de terrain par passage", "Sans flamme", "Ergonomique"],
  "cons": ["Plus encombrant", "Toujours dépendant d'une prise"],
  "specs": [("Énergie", "Électrique (secteur)"), ("Usage", "Grandes surfaces"), ("Flamme", "Non"), ("Cible", "Jeunes pousses, annuelles")]},
 {"name": "VOUNOT désherbeur électrique 2000 W", "brand": "VOUNOT", "badge": "Petit prix", "price": "€", "table": ["Électrique, air chaud", "Polyvalent"],
  "for": "un petit budget, avec un outil qui sert aussi à allumer le barbecue.",
  "pros": ["Prix bas", "Plusieurs buses", "Servira aussi pour d'autres usages"],
  "cons": ["Moins confortable à manier qu'un modèle dédié", "Air très chaud : prudence avec les enfants"],
  "specs": [("Énergie", "Électrique, 2000 W"), ("Usage", "Petites zones"), ("Flamme", "Non, air chaud"), ("Cible", "Jeunes pousses")]},
 {"name": "GLORIA Thermoflamm BIO Professional PLUS", "brand": "GLORIA", "badge": "Sans prise", "price": "€€", "table": ["Gaz", "Partout"],
  "for": "les jardins sans prise à proximité ou les gros chantiers.",
  "pros": ["Aucune prise nécessaire", "Efficace sur les herbes plus grandes", "Maniable"],
  "cons": ["Il faut une cartouche ou bouteille de gaz", "Flamme : attention aux haies sèches"],
  "specs": [("Énergie", "Gaz"), ("Usage", "Partout, chantiers"), ("Flamme", "Oui"), ("Cible", "Annuelles, plus grandes herbes")]},
 {"name": "CFH EFB 675 (brosse électrique à joints)", "brand": "CFH", "badge": "Joints de terrasse", "price": "€€", "table": ["Électrique, brosse", "Joints, dalles"],
  "for": "les joints de terrasse et les dalles envahis par la mousse.",
  "pros": ["Retire mousse et herbes entre les dalles", "Changement de brosse sans outil", "400 W, sans produit"],
  "cons": ["Pas fait pour les herbes hautes", "Peut projeter du sable des joints"],
  "specs": [("Énergie", "Électrique, 400 W"), ("Usage", "Joints, dalles"), ("Flamme", "Non"), ("Cible", "Mousse, herbes dans les joints")]},
],
"criteria_title": "Choisir son désherbeur",
"criteria_intro": "Le bon outil dépend de l'endroit : chaleur pour les allées, brosse pour les joints. Aucun ne règle le problème en une seule fois.",
"criteria": [
 ("Surface", "Allée, terrasse ou grande cour", "Un capot large fait gagner du temps sur les grandes surfaces."),
 ("Énergie", "Prise, gaz ou batterie", "Sans prise à proximité, le gaz évite la rallonge."),
 ("Sécurité", "Sans flamme ou à flamme", "Évitez la flamme près des haies sèches et des paillis."),
 ("Type d'herbe", "Jeunes pousses ou vivaces", "Les vivaces repoussent : plusieurs passages sont nécessaires."),
],
"tip": {"title": "Désherber à la chaleur efficacement", "steps": [
 "Intervenez sur des herbes jeunes, avant qu'elles montent en graines.",
 "Passez l'outil quelques secondes : l'herbe doit faner, pas brûler.",
 "Repassez deux à trois semaines plus tard sur les repousses.",
 "Gardez les enfants et animaux à distance pendant l'utilisation."]},
"mistakes": [
 ("Brûler l'herbe plutôt que la chauffer", "Quelques secondes suffisent : le choc thermique détruit les cellules."),
 ("Laisser les herbes monter en graines", "Elles se ressèment partout autour."),
 ("Utiliser une flamme près de matériaux secs", "Risque d'incendie : arrosez avant par temps sec."),
 ("Compter sur un seul passage", "Les racines des vivaces repartent."),
],
"faq": [
 ("Le désherbeur thermique tue-t-il les racines ?", "Pas toujours. Il détruit les parties aériennes ; les vivaces demandent des passages répétés."),
 ("Est-ce plus écologique qu'un désherbant ?", "Il n'utilise aucun produit chimique, mais consomme de l'électricité ou du gaz."),
 ("Peut-on désherber en terrasse sans abîmer les dalles ?", "Oui, une brosse à joints convient aux dalles ; testez d'abord sur une zone discrète."),
 ("Y a-t-il un modèle sans fil ?", "Il existe des brosses et désherbeurs sur batterie, mais l'autonomie est plus limitée."),
],
},
{
"slug": "litiere-autonettoyante-pas-cher", "cat": "animaux", "short": "Litière autonettoyante pas chère",
"title": "Litière autonettoyante pas chère 2026 : bons plans et pièges",
"desc": "Litière autonettoyante à petit budget : notre comparatif de 5 modèles accessibles, avec sécurité anti-pincement, capacité, application et pièges à éviter.",
"h1": "Litière autonettoyante pas chère : ce qu'on peut sacrifier, et ce qu'il faut garder",
"lede": "Les modèles à petit prix existent. L'essentiel est de ne rien sacrifier sur la sécurité du chat, et d'accepter un peu moins de finitions.",
"teaser": "Une litière qui se nettoie seule, sans vider le budget.", "read": 7,
"pick": {"why": "Un modèle d'une grande marque spécialisée, avec capteurs de sécurité et application, au meilleur rapport qualité-prix de la sélection.",
         "alts": 'Budget le plus serré ? Voir <a href="#p2">XQDKoon</a>. Plusieurs chats ? Voir <a href="#p4">CATLINK Pro</a>.'},
"table_cols": ["Capacité", "Application"],
"products": [
 {"name": "PETKIT Pura X", "brand": "PETKIT", "badge": "Meilleur choix", "price": "€€", "table": ["Environ 60 L", "Oui"],
  "for": "un ou deux chats, avec un bon niveau de sécurité.",
  "pros": ["Capteurs de sécurité pour protéger le chat", "Application et suivi de passage", "Marque spécialisée, pièces disponibles"],
  "cons": ["Plus cher que les modèles génériques", "Sacs et filtres à racheter"],
  "specs": [("Capacité", "Environ 60 L"), ("Application", "Oui"), ("Sécurité", "Capteurs anti-pincement"), ("Chats", "Un à deux")]},
 {"name": "XQDKoon litière autonettoyante 65 L", "brand": "XQDKoon", "badge": "Petit prix", "price": "€", "table": ["65 L + bac à déchets", "Oui"],
  "for": "ceux qui veulent le prix le plus bas avec une grande capacité.",
  "pros": ["Grande capacité", "Application incluse", "Sacs poubelle fournis au départ"],
  "cons": ["Marque peu connue, service après-vente à vérifier", "Qualité des finitions inégale selon les avis"],
  "specs": [("Capacité", "65 L + 9 L de déchets"), ("Application", "Oui"), ("Sécurité", "Capteurs"), ("Chats", "Un à plusieurs")]},
 {"name": "Neakasa M1 Lite", "brand": "Neakasa", "badge": "Modèle ouvert", "price": "€€", "table": ["Grande, ouverte", "Oui"],
  "for": "se lancer dans la litière automatique avec un modèle ouvert, adapté aux grands chats.",
  "pros": ["Design ouvert, moins stressant pour le chat", "Convient aux grands chats", "Suivi dans l'application"],
  "cons": ["Plus cher que les modèles génériques", "Encombrant"],
  "specs": [("Capacité", "Grande"), ("Application", "Oui"), ("Sécurité", "Capteurs"), ("Chats", "Un ou plusieurs")]},
 {"name": "CATLINK Pro", "brand": "CATLINK", "badge": "Plusieurs chats", "price": "€€", "table": ["Environ 57 L", "Oui"],
  "for": "un foyer avec deux chats, avec reconnaissance du chat.",
  "pros": ["Détection de plusieurs chats", "Suivi de santé dans l'application", "Capteurs de sécurité"],
  "cons": ["Chats de 1,5 à 10 kg seulement", "Plus cher que les modèles génériques"],
  "specs": [("Capacité", "Environ 57 L"), ("Application", "Oui"), ("Sécurité", "Capteurs"), ("Chats", "Un à deux")]},
 {"name": "Feelneedy litière autonettoyante 65 L", "brand": "Feelneedy", "badge": "Grand volume", "price": "€", "table": ["Environ 65 L", "Oui"],
  "for": "un foyer qui veut une grande cuve à petit prix.",
  "pros": ["Grande cuve", "Sécurité anti-fuites et anti-pincement annoncées", "Prix contenu"],
  "cons": ["Marque récente", "Peu de recul sur la durabilité"],
  "specs": [("Capacité", "Environ 65 L"), ("Application", "Oui"), ("Sécurité", "Anti-pincement"), ("Chats", "Un à plusieurs")]},
],
"criteria_title": "Où faire des économies, où non",
"criteria_intro": "À petit prix, on peut renoncer à l'application ou à la déco. Pas aux capteurs de sécurité ni à la facilité de nettoyage.",
"criteria": [
 ("Sécurité", "Capteur de poids et anti-pincement", "Le chat ne doit jamais être touché par le tambour."),
 ("Poids minimum du chat", "Souvent 1,5 à 2 kg", "Un chaton léger peut ne pas déclencher les capteurs."),
 ("Consommables", "Sacs, filtres, litière", "Un modèle bon marché devient cher si les consommables sont propriétaires."),
 ("Service après-vente", "Marque connue, pièces disponibles", "Un appareil en panne sans pièce se jette."),
],
"tip": {"title": "Faire accepter la litière automatique", "steps": [
 "Installez-la éteinte à côté de l'ancienne litière pendant quelques jours.",
 "Mettez-y de la litière usagée pour l'odeur familière.",
 "Allumez-la quand le chat l'utilise sans crainte.",
 "Gardez l'ancienne litière une à deux semaines en secours."]},
"mistakes": [
 ("Choisir sans vérifier les capteurs", "Un tambour qui tourne pendant la présence du chat est dangereux."),
 ("Oublier la compatibilité avec la litière", "Certaines litières agglomérantes ne conviennent pas au tambour."),
 ("Placer l'appareil dans un coin bruyant", "Le chat doit pouvoir l'utiliser dans le calme."),
 ("Supprimer l'ancienne litière trop vite", "Un chat méfiant peut aller ailleurs dans la maison."),
],
"faq": [
 ("Une litière autonettoyante à petit prix est-elle fiable ?", "Elle peut l'être, à condition d'avoir des capteurs de sécurité et un service après-vente disponible."),
 ("Convient-elle à un chaton ?", "Souvent non : beaucoup de modèles exigent un poids minimum, vérifiez la notice."),
 ("Faut-il encore la vider ?", "Oui, le bac à déchets, tous les quelques jours, et la litière complète de temps en temps."),
 ("Quelle différence avec un modèle haut de gamme ?", "Surtout les finitions, l'application, le silence et le suivi de santé."),
],
},
]
