# Guides ciblés (longue traîne), ajoutés le 5 octobre 2026.

GUIDES3 = [
# ================================================================ MENAGE
{
"slug": "robot-aspirateur-pas-cher", "cat": "menage", "short": "Robot aspirateur pas cher",
"title": "Robot aspirateur pas cher 2026 : les meilleurs petits prix",
"desc": "Robot aspirateur pas cher : quels modèles valent vraiment le coup à petit prix ? Notre sélection et les compromis à accepter.",
"h1": "Robot aspirateur pas cher : ce qu'on peut vraiment attendre à petit prix",
"lede": "Navigation laser ou aléatoire, autonomie, application : où se trouvent les bons compromis quand on ne veut pas dépasser quelques centaines d'euros.",
"teaser": "Les bons compromis à petit prix.", "read": 7,
"pick": {"why": "La navigation laser à petit prix : il cartographie le logement et ne repasse pas dix fois au même endroit.",
         "alts": 'Encore moins cher ? Voir <a href="#p3">Lefant</a>. Avec lavage ? Voir <a href="#p2">Roborock Q-series</a>.'},
"table_cols": ["Navigation", "Lavage"],
"products": [
 {"name": "Xiaomi Robot Vacuum (entrée de gamme)", "brand": "Xiaomi", "badge": "Meilleur choix", "price": "€", "table": ["Laser", "Serpillière fixe"],
  "for": "un appartement, avec un budget serré.",
  "pros": ["Navigation laser rare à ce prix", "Application complète", "Zones interdites"],
  "cons": ["Bac à vider à la main", "Lavage basique"],
  "specs": [("Navigation", "Laser"), ("Station", "Charge seule"), ("Lavage", "Serpillière fixe"), ("Logement", "Appartement")]},
 {"name": "Roborock Q-series", "brand": "Roborock", "badge": "Avec lavage", "price": "€€", "table": ["Laser", "Serpillière fixe"],
  "for": "ceux qui veulent un petit plus de qualité sans exploser le budget.",
  "pros": ["Navigation fiable", "Bonne aspiration", "Station de vidage sur certaines versions"],
  "cons": ["Plus cher que l'entrée de gamme", "Lavage limité"],
  "specs": [("Navigation", "Laser"), ("Station", "Selon version"), ("Lavage", "Serpillière fixe"), ("Logement", "Appartement, maison")]},
 {"name": "Lefant", "brand": "Lefant", "badge": "Prix plancher", "price": "€", "table": ["Gyroscope", "Non"],
  "for": "un studio, juste pour garder un sol sans poussière.",
  "pros": ["Prix très bas", "Très fin, passe partout", "Simple"],
  "cons": ["Navigation moins méthodique", "Pas de vraie carte"],
  "specs": [("Navigation", "Gyroscope"), ("Station", "Charge seule"), ("Lavage", "Non"), ("Logement", "Studio")]},
],
"criteria_title": "Les compromis à accepter à petit prix",
"criteria_intro": "Un robot pas cher fait très bien l'entretien quotidien. Ce qu'on perd, c'est surtout l'autonomie de la station.",
"criteria": [
 ("Navigation laser", "Présence d'un capteur laser sur le dessus", "C'est le critère le plus important : un robot qui se repère finit le travail."),
 ("Station de vidage", "Souvent absente à petit prix", "Il faudra vider le bac régulièrement."),
 ("Application", "Carte, zones interdites, programmation", "Indispensable pour ne pas surveiller le robot."),
 ("Pièces détachées", "Brosses et filtres disponibles", "Un robot pas cher doit rester réparable."),
],
"tip": {"title": "Tirer le meilleur d'un robot pas cher", "steps": [
 "Programmez un passage quotidien plutôt qu'un grand ménage par semaine.",
 "Videz le bac à chaque retour à la base.",
 "Achetez un lot de brosses et filtres de rechange dès le départ."]},
"mistakes": [
 ("Prendre un robot sans laser", "Il tourne au hasard et laisse des zones sales."),
 ("Attendre le lavage d'un modèle haut de gamme", "À petit prix, la serpillière humidifie mais ne frotte pas."),
 ("Oublier l'entretien", "Une brosse emmêlée réduit vite l'efficacité."),
],
"faq": [
 ("Un robot pas cher vaut-il le coup ?", "Oui pour l'entretien quotidien d'un appartement. Pour une grande maison, mieux vaut un modèle avec station."),
 ("Peut-on ajouter une station plus tard ?", "Rarement. Si la station vous intéresse, choisissez directement une version qui en a une."),
 ("Combien de temps dure-t-il ?", "Plusieurs années avec un entretien régulier. La batterie est la première pièce à s'user."),
],
},
{
"slug": "robot-aspirateur-poils-animaux", "cat": "menage", "short": "Robot aspirateur pour poils d'animaux",
"title": "Robot aspirateur pour poils d'animaux 2026 : comparatif",
"desc": "Quel robot aspirateur pour les poils de chien et de chat ? Brosse anti-emmêlement, filtration, évitement des déjections : notre sélection.",
"h1": "Robot aspirateur pour poils d'animaux : en finir avec les touffes sous les meubles",
"lede": "Brosse en caoutchouc, puissance sur les tapis, évitement des jouets et des accidents : ce qui compte quand un chien ou un chat perd ses poils toute l'année.",
"teaser": "Fini les touffes de poils sous les meubles.", "read": 8,
"pick": {"why": "Sa brosse limite l'emmêlement des poils et sa station vide tout seule le bac, qui se remplit vite avec un animal.",
         "alts": 'Petit budget ? Voir <a href="#p3">Shark</a>. Évitement des accidents ? Voir <a href="#p2">Roborock avec caméra</a>.'},
"table_cols": ["Brosse", "Station"],
"products": [
 {"name": "Dreame L-series", "brand": "Dreame", "badge": "Meilleur choix", "price": "€€€€", "table": ["Anti-emmêlement", "Tout-en-un"],
  "for": "les maisons avec un ou plusieurs animaux qui perdent beaucoup de poils.",
  "pros": ["Brosse conçue contre les poils emmêlés", "Forte aspiration sur tapis", "Vidage automatique"],
  "cons": ["Prix élevé", "Station encombrante"],
  "specs": [("Brosse", "Anti-emmêlement"), ("Station", "Tout-en-un"), ("Caméra", "Selon modèle"), ("Filtration", "Haute")]},
 {"name": "Roborock avec caméra", "brand": "Roborock", "badge": "Évite les accidents", "price": "€€€€", "table": ["Caoutchouc", "Tout-en-un"],
  "for": "les chiots et chats pas encore propres.",
  "pros": ["Caméra qui reconnaît les déjections", "Évite câbles et jouets", "Station complète"],
  "cons": ["Prix élevé", "Caméra embarquée : réglages de confidentialité à vérifier"],
  "specs": [("Brosse", "Caoutchouc"), ("Station", "Tout-en-un"), ("Caméra", "Oui"), ("Filtration", "Haute")]},
 {"name": "Shark robot avec station", "brand": "Shark", "badge": "Petit budget", "price": "€€", "table": ["Anti-cheveux", "Vidage"],
  "for": "un appartement avec un animal, à budget raisonnable.",
  "pros": ["Brosse anti-cheveux efficace", "Station de vidage sans sac sur certains modèles", "Bon prix"],
  "cons": ["Navigation moins précise", "Lavage limité"],
  "specs": [("Brosse", "Anti-cheveux"), ("Station", "Vidage"), ("Caméra", "Non"), ("Filtration", "Bonne")]},
],
"criteria_title": "Ce qui compte avec des animaux",
"criteria_intro": "Avec un animal, le bac se remplit en un passage. La station de vidage passe de confort à nécessité.",
"criteria": [
 ("Brosse", "Caoutchouc ou anti-emmêlement", "Les poils s'enroulent autour des brosses à poils classiques."),
 ("Station de vidage", "Vidage automatique du bac", "Sinon, il faut vider le bac après chaque passage."),
 ("Évitement d'obstacles", "Caméra qui reconnaît les déjections", "Un robot qui roule dans un accident étale tout dans la maison."),
 ("Filtration", "Filtre fin et bac étanche", "Retient les squames responsables d'allergies."),
],
"tip": {"title": "Habituer l'animal au robot", "steps": [
 "Laissez l'animal renifler le robot éteint pendant quelques jours.",
 "Lancez les premiers passages en votre présence, en mode silencieux.",
 "Programmez ensuite le robot quand l'animal est dans une autre pièce ou dehors."]},
"mistakes": [
 ("Choisir une brosse à poils", "Elle s'emmêle en quelques jours."),
 ("Laisser tourner un robot sans caméra avec un chiot", "Un accident au sol peut tourner à la catastrophe."),
 ("Oublier les gamelles", "Créez une zone interdite autour de l'eau et des croquettes."),
],
"faq": [
 ("Le robot fait-il peur aux animaux ?", "Souvent au début. La plupart s'habituent en quelques jours, certains le suivent même."),
 ("Ramasse-t-il la litière éparpillée ?", "Oui, les grains de litière sont bien aspirés, à condition de vider souvent le bac."),
 ("Faut-il passer plus souvent ?", "Un passage quotidien est conseillé en période de mue."),
],
},
{
"slug": "robot-aspirateur-petit-appartement", "cat": "menage", "short": "Robot aspirateur pour petit appartement",
"title": "Robot aspirateur pour petit appartement 2026 : notre sélection",
"desc": "Robot aspirateur pour petit appartement ou studio : compact, silencieux, sans station encombrante. Notre sélection de modèles adaptés.",
"h1": "Robot aspirateur pour petit appartement : compact, discret et efficace",
"lede": "Taille de la station, hauteur sous les meubles, bruit dans un studio : comment choisir un robot qui ne prend pas plus de place qu'il n'en libère.",
"teaser": "Un robot qui ne prend pas toute la place.", "read": 7,
"pick": {"why": "Compact, discret et doté d'une station de vidage plus petite que la moyenne : l'équilibre idéal pour un deux-pièces.",
         "alts": 'Studio et petit budget ? Voir <a href="#p2">Xiaomi</a>. Très bas sous les meubles ? Voir <a href="#p3">Eufy</a>.'},
"table_cols": ["Station", "Hauteur"],
"products": [
 {"name": "Roborock Q-series avec station", "brand": "Roborock", "badge": "Meilleur choix", "price": "€€", "table": ["Vidage compact", "Standard"],
  "for": "un deux ou trois-pièces.",
  "pros": ["Station de vidage relativement compacte", "Navigation laser fiable", "Bon rapport qualité-prix"],
  "cons": ["Lavage basique", "Tourelle laser qui ajoute de la hauteur"],
  "specs": [("Station", "Vidage"), ("Navigation", "Laser"), ("Hauteur", "Standard"), ("Logement", "2 à 3 pièces")]},
 {"name": "Xiaomi Robot Vacuum", "brand": "Xiaomi", "badge": "Studio", "price": "€", "table": ["Charge seule", "Standard"],
  "for": "un studio ou une chambre de location.",
  "pros": ["Base minuscule", "Prix bas", "Navigation laser"],
  "cons": ["Bac à vider à la main", "Bac de petite contenance"],
  "specs": [("Station", "Charge seule"), ("Navigation", "Laser"), ("Hauteur", "Standard"), ("Logement", "Studio")]},
 {"name": "Eufy RoboVac (gamme fine)", "brand": "Eufy", "badge": "Très fin", "price": "€", "table": ["Charge seule", "Très bas"],
  "for": "les logements avec lits et canapés très bas.",
  "pros": ["Passe sous les meubles bas", "Silencieux", "Simple à utiliser"],
  "cons": ["Navigation moins précise sans laser", "Pas de carte détaillée"],
  "specs": [("Station", "Charge seule"), ("Navigation", "Gyroscope"), ("Hauteur", "Très bas"), ("Logement", "Studio, 2 pièces")]},
],
"criteria_title": "Ce qui compte dans un petit logement",
"criteria_intro": "Dans un petit appartement, la place prise par la station et le bruit comptent autant que l'aspiration.",
"criteria": [
 ("Taille de la station", "Hauteur et largeur au sol", "Une station tout-en-un peut occuper autant qu'un petit meuble."),
 ("Hauteur du robot", "Hauteur comparée aux meubles", "Dans un studio, le lit et le canapé couvrent une grande partie du sol."),
 ("Bruit", "Mode silencieux", "Le robot tourne souvent dans la pièce où l'on vit."),
 ("Programmation", "Passage quand vous êtes absent", "Le meilleur moyen de ne jamais l'entendre."),
],
"tip": {"title": "Optimiser un petit espace", "steps": [
 "Placez la base dans un couloir ou sous un meuble ouvert.",
 "Relevez les chaises sur la table le jour du grand passage.",
 "Programmez le robot pendant vos heures de travail."]},
"mistakes": [
 ("Acheter une station tout-en-un trop grande", "Elle risque de ne pas trouver sa place."),
 ("Ignorer la hauteur du lit", "C'est la zone la plus poussiéreuse d'un studio."),
 ("Le lancer quand vous êtes là", "Dans un petit espace, le bruit devient vite pénible."),
],
"faq": [
 ("Un robot est-il utile dans un studio ?", "Oui : moins de surface, donc un robot simple fait tout le travail en un passage."),
 ("Faut-il une station de vidage ?", "Pas forcément dans un studio, le bac suffit pour plusieurs passages."),
 ("Où mettre la base ?", "Contre un mur, avec un peu d'espace dégagé devant et sur les côtés."),
],
},
{
"slug": "aspirateur-a-main", "cat": "menage", "short": "Aspirateur à main",
"title": "Aspirateur à main 2026 : comparatif pour canapé, voiture et miettes",
"desc": "Aspirateur à main sans fil pour les miettes, le canapé ou la voiture : notre comparatif de modèles légers, puissants et faciles à vider.",
"h1": "Aspirateur à main : les miettes ramassées en dix secondes",
"lede": "Puissance, autonomie, accessoires pour la voiture et le canapé : comment choisir le petit aspirateur qu'on attrape sans réfléchir.",
"teaser": "Miettes, canapé, voiture : dix secondes et c'est fini.", "read": 6,
"pick": {"why": "Léger, puissant pour sa taille et livré avec une brosse motorisée efficace sur le canapé et les poils.",
         "alts": 'Petit budget ? Voir <a href="#p3">Black+Decker Dustbuster</a>. Pour la voiture ? Voir <a href="#p2">Shark WandVac</a>.'},
"table_cols": ["Brosse motorisée", "Charge"],
"products": [
 {"name": "Dyson (aspirateur à main)", "brand": "Dyson", "badge": "Meilleur choix", "price": "€€€", "table": ["Oui", "Socle ou câble"],
  "for": "ceux qui veulent un aspirateur à main aussi puissant qu'un balai.",
  "pros": ["Très puissant", "Brosse motorisée efficace", "Bonne filtration"],
  "cons": ["Prix élevé", "Autonomie courte en mode fort"],
  "specs": [("Brosse motorisée", "Oui"), ("Charge", "Socle ou câble"), ("Usage", "Canapé, voiture, escaliers"), ("Poids", "Léger")]},
 {"name": "Shark WandVac", "brand": "Shark", "badge": "Voiture", "price": "€€", "table": ["Selon modèle", "Socle"],
  "for": "la voiture et les petites corvées du quotidien.",
  "pros": ["Très léger et fin", "Socle de charge pratique", "Bac facile à vider"],
  "cons": ["Petit bac", "Moins puissant sur les tapis"],
  "specs": [("Brosse motorisée", "Selon modèle"), ("Charge", "Socle"), ("Usage", "Voiture, miettes"), ("Poids", "Très léger")]},
 {"name": "Black+Decker Dustbuster", "brand": "Black+Decker", "badge": "Petit budget", "price": "€", "table": ["Selon modèle", "Socle"],
  "for": "les miettes de la cuisine et de la table.",
  "pros": ["Prix bas", "Toujours chargé sur son socle", "Robuste"],
  "cons": ["Puissance modeste", "Filtre à nettoyer souvent"],
  "specs": [("Brosse motorisée", "Selon modèle"), ("Charge", "Socle"), ("Usage", "Miettes"), ("Poids", "Léger")]},
],
"criteria_title": "Ce qui compte pour un aspirateur à main",
"criteria_intro": "Un aspirateur à main est utile s'il est toujours chargé et à portée de main. Le socle compte autant que la puissance.",
"criteria": [
 ("Charge", "Socle mural ou câble USB", "Un socle le garde toujours prêt."),
 ("Brosse motorisée", "Brosse rotative pour les tissus", "Indispensable pour les poils sur le canapé."),
 ("Poids", "Poids en main", "On l'utilise à bout de bras, souvent en hauteur."),
 ("Vidage", "Ouverture du bac en un geste", "Sinon on finit par le vider à la main."),
],
"tip": {"title": "L'avoir toujours sous la main", "steps": [
 "Fixez le socle dans la cuisine, là où tombent les miettes.",
 "Videz le bac après chaque usage.",
 "Tapez le filtre au-dessus de la poubelle une fois par semaine."]},
"mistakes": [
 ("Le ranger dans un placard", "Il ne sera jamais utilisé."),
 ("Ignorer la brosse motorisée", "Sans elle, les poils restent accrochés au tissu."),
 ("Aspirer du liquide", "Sauf modèle prévu pour, cela abîme le moteur."),
],
"faq": [
 ("Peut-on le charger dans la voiture ?", "Certains modèles se chargent en USB, ce qui permet de les laisser dans la voiture."),
 ("Un aspirateur balai ne suffit-il pas ?", "La plupart des balais se transforment en aspirateur à main, mais un petit modèle dédié est plus rapide à attraper."),
 ("Combien de temps tient la batterie ?", "Quelques minutes à un quart d'heure : largement assez pour les petites corvées."),
],
},
# ================================================================ LINGE
{
"slug": "etendoir-chauffant", "cat": "linge", "short": "Étendoir à linge chauffant",
"title": "Étendoir à linge chauffant 2026 : comparatif et consommation",
"desc": "Étendoir à linge électrique chauffant : sécher le linge en quelques heures sans sèche-linge. Notre sélection et ce qu'il consomme vraiment.",
"h1": "Étendoir chauffant : sécher le linge vite, sans sèche-linge",
"lede": "Barres chauffantes, housse, pliage, consommation : la solution pour sécher en quelques heures quand on n'a pas la place pour un sèche-linge.",
"teaser": "Du linge sec en quelques heures, sans sèche-linge.", "read": 6,
"pick": {"why": "Avec sa housse, il sèche une machine en quelques heures, puis se replie à plat contre un mur.",
         "alts": 'Petit espace ? Voir <a href="#p2">modèle à ailes</a>. Petit budget ? Voir <a href="#p3">modèle sans housse</a>.'},
"table_cols": ["Housse", "Pliage"],
"products": [
 {"name": "Étendoir chauffant à étages avec housse", "brand": "Plusieurs marques", "badge": "Meilleur choix", "price": "€€", "table": ["Oui", "À plat"],
  "for": "sécher une machine entière en hiver, en appartement.",
  "pros": ["Séchage rapide grâce à la housse", "Grande longueur d'étendage", "Se replie"],
  "cons": ["Encombrant déplié", "Housse à acheter à part selon les modèles"],
  "specs": [("Housse", "Oui"), ("Pliage", "À plat"), ("Minuterie", "Selon modèle"), ("Usage", "Machine entière")]},
 {"name": "Étendoir chauffant à ailes", "brand": "Plusieurs marques", "badge": "Petit espace", "price": "€€", "table": ["Selon modèle", "Ailes"],
  "for": "une petite salle de bains ou un studio.",
  "pros": ["Encombrement réduit ailes repliées", "Facile à déplacer", "Pratique pour le petit linge"],
  "cons": ["Moins de longueur d'étendage", "Séchage plus lent sans housse"],
  "specs": [("Housse", "Selon modèle"), ("Pliage", "Ailes"), ("Minuterie", "Selon modèle"), ("Usage", "Petites charges")]},
 {"name": "Domo DO7117DR", "brand": "Domo", "badge": "Petit budget", "price": "€", "table": ["Non", "Debout ou au mur"],
  "for": "sécher serviettes et petit linge dans un petit logement, sans se ruiner.",
  "pros": ["Minuterie intégrée", "150 W seulement", "Se pose au sol ou se fixe au mur"],
  "cons": ["Séchage lent sans housse", "Peu de place pour une grosse lessive"],
  "specs": [("Housse", "Non"), ("Forme", "Porte-serviettes debout"), ("Minuterie", "Oui"), ("Puissance", "150 W")]},
],
"criteria_title": "Ce qui compte pour un étendoir chauffant",
"criteria_intro": "Les barres ne chauffent qu'à basse température : c'est la housse qui fait la vraie différence de vitesse.",
"criteria": [
 ("Housse", "Housse isolante fournie ou en option", "Elle garde la chaleur et divise le temps de séchage."),
 ("Longueur d'étendage", "Mètres de barres", "Détermine si une machine entière tient dessus."),
 ("Minuterie", "Arrêt automatique", "Évite de chauffer pour rien."),
 ("Encombrement plié", "Épaisseur une fois replié", "Il doit pouvoir se ranger derrière une porte."),
],
"tip": {"title": "Sécher plus vite en consommant moins", "steps": [
 "Essorez fort à la machine avant d'étendre.",
 "Espacez les vêtements pour que l'air circule.",
 "Mettez la housse et réglez la minuterie.",
 "Aérez la pièce après le séchage pour évacuer l'humidité."]},
"mistakes": [
 ("Oublier la housse", "Sans elle, le séchage reste lent."),
 ("Surcharger les barres", "Le linge du dessous ne sèche pas."),
 ("Le laisser dans une pièce fermée", "L'humidité se dépose sur les murs."),
],
"faq": [
 ("Consomme-t-il beaucoup ?", "Beaucoup moins qu'un sèche-linge classique : les barres ont une puissance modérée. Le coût dépend de la durée d'utilisation."),
 ("Peut-on y sécher tous les tissus ?", "Oui pour la plupart. Évitez la laine fragile directement sur les barres."),
 ("Est-ce sûr ?", "Oui, les barres chauffent doucement. Ne couvrez pas l'appareil autrement qu'avec la housse prévue."),
],
},
{
"slug": "centrale-vapeur", "cat": "linge", "short": "Centrale vapeur",
"title": "Centrale vapeur 2026 : comparatif pour repasser deux fois plus vite",
"desc": "Centrale vapeur : repasser plus vite qu'avec un fer classique. Pression, anti-calcaire, poids : notre comparatif et nos conseils.",
"h1": "Centrale vapeur : repasser deux fois plus vite quand on ne peut pas y échapper",
"lede": "Pression de vapeur, réservoir, système anti-calcaire : la bonne centrale divise le temps de repassage des chemises et des draps.",
"teaser": "Repasser deux fois plus vite.", "read": 7,
"pick": {"why": "Pas besoin de régler la température : la même semelle passe sur tous les tissus sans les brûler.",
         "alts": 'Petit budget ? Voir <a href="#p3">Calor Express</a>. Beaucoup de linge ? Voir <a href="#p2">Rowenta</a>.'},
"table_cols": ["Réglage", "Anti-calcaire"],
"products": [
 {"name": "Philips PerfectCare", "brand": "Philips", "badge": "Meilleur choix", "price": "€€€", "table": ["Automatique", "Cartouche ou rinçage"],
  "for": "ceux qui repassent des tissus variés sans vouloir trier.",
  "pros": ["Une seule température pour tous les tissus", "Vapeur puissante", "Semelle glissante"],
  "cons": ["Prix élevé", "Base encombrante"],
  "specs": [("Réglage", "Automatique"), ("Anti-calcaire", "Oui"), ("Réservoir", "Amovible"), ("Usage", "Famille")]},
 {"name": "Rowenta (centrale vapeur)", "brand": "Rowenta", "badge": "Gros volumes", "price": "€€€", "table": ["Manuel ou auto", "Collecteur"],
  "for": "les familles qui repassent beaucoup de linge.",
  "pros": ["Très bonne pression", "Grand réservoir", "SAV en France"],
  "cons": ["Lourde", "Bruyante"],
  "specs": [("Réglage", "Selon modèle"), ("Anti-calcaire", "Collecteur"), ("Réservoir", "Grand"), ("Usage", "Gros volumes")]},
 {"name": "Calor Express", "brand": "Calor", "badge": "Petit budget", "price": "€€", "table": ["Manuel", "Collecteur"],
  "for": "passer du fer classique à une centrale sans gros budget.",
  "pros": ["Prix accessible", "Gain de temps net par rapport à un fer", "Simple"],
  "cons": ["Moins de pression", "Réglages manuels"],
  "specs": [("Réglage", "Manuel"), ("Anti-calcaire", "Collecteur"), ("Réservoir", "Moyen"), ("Usage", "Occasionnel")]},
],
"criteria_title": "Ce qui compte pour une centrale vapeur",
"criteria_intro": "Si vous repassez surtout pour défroisser, un défroisseur suffit. La centrale vaut le coup pour les chemises, les draps et les gros volumes.",
"criteria": [
 ("Pression", "Pression de vapeur en bars", "Plus elle est forte, plus la vapeur traverse le tissu."),
 ("Anti-calcaire", "Collecteur ou cartouche", "Le calcaire est la première cause de panne."),
 ("Réglage automatique", "Une température pour tous les tissus", "Évite de brûler un vêtement fragile."),
 ("Réservoir", "Amovible et remplissable en cours de route", "Évite les interruptions."),
],
"tip": {"title": "Repasser moins longtemps", "steps": [
 "Sortez le linge du sèche-linge ou de l'étendoir encore un peu humide.",
 "Commencez par les tissus fragiles si la centrale n'est pas automatique.",
 "Repassez les chemises sur cintre, col et poignets en premier.",
 "Rincez le collecteur de calcaire selon la notice."]},
"mistakes": [
 ("Négliger le calcaire", "La centrale crache des traces blanches puis tombe en panne."),
 ("Acheter pour défroisser seulement", "Un défroisseur est moins cher et plus rapide."),
 ("Ranger la centrale chaude", "Laissez-la refroidir et videz le réservoir."),
],
"faq": [
 ("Centrale ou défroisseur ?", "Le défroisseur pour le quotidien, la centrale pour les chemises nettes et les gros volumes."),
 ("Faut-il de l'eau déminéralisée ?", "Suivez la notice : beaucoup de centrales récentes acceptent l'eau du robinet grâce à leur système anti-calcaire."),
 ("Est-ce que ça consomme beaucoup ?", "La puissance est élevée pendant la chauffe, mais le repassage est plus court qu'avec un fer."),
],
},
# ================================================================ CUISINE
{
"slug": "multicuiseur", "cat": "cuisine", "short": "Multicuiseur (type Cookeo)",
"title": "Multicuiseur 2026 : comparatif Cookeo, Instant Pot et autres",
"desc": "Multicuiseur électrique : il mijote, cuit sous pression et garde au chaud tout seul. Notre comparatif pour des plats prêts sans surveillance.",
"h1": "Multicuiseur : le plat mijote seul pendant que vous faites autre chose",
"lede": "Cuisson sous pression, mijotage, maintien au chaud, recettes guidées : comment choisir l'appareil qui prépare le dîner sans surveillance.",
"teaser": "Le dîner mijote tout seul.", "read": 7,
"pick": {"why": "Les recettes guidées pas à pas et la cuisson sous pression en font l'appareil le plus simple pour un repas en vingt minutes.",
         "alts": 'Plus de fonctions ? Voir <a href="#p2">Instant Pot</a>. Cuisson lente ? Voir <a href="#p3">mijoteuse électrique</a>.'},
"table_cols": ["Pression", "Recettes guidées"],
"products": [
 {"name": "Moulinex Cookeo", "brand": "Moulinex", "badge": "Meilleur choix", "price": "€€", "table": ["Oui", "Oui"],
  "for": "les familles qui veulent des plats rapides sans réfléchir.",
  "pros": ["Recettes guidées pas à pas", "Cuisson sous pression rapide", "Maintien au chaud automatique"],
  "cons": ["Cuve de taille fixe", "Pas de dorage aussi fort qu'une poêle"],
  "specs": [("Pression", "Oui"), ("Recettes guidées", "Oui"), ("Maintien au chaud", "Oui"), ("Personnes", "Jusqu'à 6")]},
 {"name": "Instant Pot", "brand": "Instant Brands", "badge": "Polyvalent", "price": "€€", "table": ["Oui", "Application"],
  "for": "ceux qui veulent un seul appareil pour tout : riz, yaourt, mijoté.",
  "pros": ["Très nombreuses fonctions", "Cuve inox solide", "Communauté de recettes"],
  "cons": ["Interface moins guidée", "Manuels parfois en anglais"],
  "specs": [("Pression", "Oui"), ("Recettes guidées", "Application"), ("Maintien au chaud", "Oui"), ("Personnes", "Selon taille")]},
 {"name": "Mijoteuse électrique (slow cooker)", "brand": "Plusieurs marques", "badge": "Petit budget", "price": "€", "table": ["Non", "Non"],
  "for": "lancer le plat le matin et le trouver prêt le soir.",
  "pros": ["Prix bas", "Très simple", "Consommation faible"],
  "cons": ["Cuisson longue", "Pas de cuisson rapide"],
  "specs": [("Pression", "Non"), ("Recettes guidées", "Non"), ("Maintien au chaud", "Oui"), ("Personnes", "Selon taille")]},
],
"criteria_title": "Ce qui compte pour un multicuiseur",
"criteria_intro": "Deux usages s'opposent : la cuisson rapide sous pression le soir, ou la cuisson lente lancée le matin.",
"criteria": [
 ("Cuisson sous pression", "Oui ou non", "Divise par deux ou trois les temps de cuisson."),
 ("Recettes guidées", "Écran ou application", "Évite de chercher quoi faire et comment."),
 ("Capacité", "Litres de la cuve", "Prévoyez assez grand pour cuisiner en double et congeler."),
 ("Départ différé", "Programmation de l'heure de fin", "Le plat est prêt quand vous rentrez."),
],
"tip": {"title": "Un dîner prêt en rentrant", "steps": [
 "Coupez les légumes la veille et gardez-les au frais.",
 "Le matin, mettez tout dans la cuve et programmez un départ différé.",
 "Le soir, le maintien au chaud garde le plat à température."]},
"mistakes": [
 ("Remplir au-delà du repère", "En cuisson sous pression, c'est dangereux."),
 ("Ouvrir avant la décompression", "Attendez toujours que la pression soit retombée."),
 ("Négliger le joint", "Un joint sale garde les odeurs et finit par fuir."),
],
"faq": [
 ("Cookeo ou robot cuiseur ?", "Le multicuiseur cuit, le robot cuiseur coupe et mixe aussi. Pour des plats mijotés simples, le multicuiseur suffit."),
 ("Est-ce sûr de le laisser en marche en partant ?", "Les mijoteuses sont conçues pour cela. Pour la cuisson sous pression, suivez la notice."),
 ("Peut-on faire dorer la viande ?", "Oui, la plupart ont une fonction dorer avant la cuisson."),
],
},
{
"slug": "machine-a-pain", "cat": "cuisine", "short": "Machine à pain",
"title": "Machine à pain 2026 : comparatif pour du pain frais sans effort",
"desc": "Machine à pain : du pain frais le matin, sans pétrir ni surveiller. Notre comparatif de modèles et nos conseils pour réussir le pain.",
"h1": "Machine à pain : du pain frais au réveil, sans pétrir",
"lede": "Départ différé, taille de la cuve, programmes sans gluten, distributeur de graines : comment choisir une machine qui fait le pain pendant que vous dormez.",
"teaser": "Du pain frais au réveil, sans pétrir.", "read": 6,
"pick": {"why": "Son départ différé et ses nombreux programmes en font la machine la plus simple pour un pain frais chaque matin.",
         "alts": 'Petit budget ? Voir <a href="#p3">Moulinex Pain Doré</a>. Avec graines et fruits secs ? Voir <a href="#p2">Panasonic</a>.'},
"table_cols": ["Départ différé", "Distributeur"],
"products": [
 {"name": "Moulinex Home Bread", "brand": "Moulinex", "badge": "Meilleur choix", "price": "€€", "table": ["Oui", "Selon modèle"],
  "for": "les familles qui veulent du pain frais tous les jours.",
  "pros": ["Nombreux programmes", "Départ différé", "SAV en France"],
  "cons": ["Encombrante", "Trou de la pale dans la mie"],
  "specs": [("Départ différé", "Oui"), ("Distributeur", "Selon modèle"), ("Sans gluten", "Oui"), ("Pain", "Jusqu'à 1 kg")]},
 {"name": "Panasonic (machine à pain)", "brand": "Panasonic", "badge": "Distributeur", "price": "€€€", "table": ["Oui", "Oui"],
  "for": "les amateurs de pains aux graines et aux fruits secs.",
  "pros": ["Distributeur automatique de graines", "Cuisson régulière", "Construction durable"],
  "cons": ["Prix plus élevé", "Bruit de pétrissage"],
  "specs": [("Départ différé", "Oui"), ("Distributeur", "Oui"), ("Sans gluten", "Oui"), ("Pain", "Selon modèle")]},
 {"name": "Moulinex Pain Doré", "brand": "Moulinex", "badge": "Petit budget", "price": "€", "table": ["Oui", "Non"],
  "for": "essayer le pain maison sans gros investissement.",
  "pros": ["Prix bas", "Simple à utiliser", "Compacte"],
  "cons": ["Moins de programmes", "Croûte moins dorée"],
  "specs": [("Départ différé", "Oui"), ("Distributeur", "Non"), ("Sans gluten", "Selon modèle"), ("Pain", "Jusqu'à 1 kg")]},
],
"criteria_title": "Ce qui compte pour une machine à pain",
"criteria_intro": "Le départ différé est ce qui transforme la machine en vrai gain de temps : on prépare le soir, le pain est prêt le matin.",
"criteria": [
 ("Départ différé", "Programmation jusqu'à 12 ou 15 heures", "Le pain cuit pendant la nuit."),
 ("Taille du pain", "Poids maximal", "Une famille consomme vite un pain de 500 g."),
 ("Distributeur", "Ajout automatique de graines", "Évite d'attendre le bip pour les ajouter."),
 ("Programmes", "Sans gluten, pâte à pizza, confiture", "Rend la machine plus utile au quotidien."),
],
"tip": {"title": "Réussir son pain du premier coup", "steps": [
 "Pesez les ingrédients au gramme près.",
 "Mettez les liquides en premier, la levure en dernier, sans contact avec le sel.",
 "Utilisez une farine adaptée à la machine.",
 "Démoulez le pain dès la fin pour garder la croûte croustillante."]},
"mistakes": [
 ("Mettre le sel sur la levure", "Le pain ne lève pas."),
 ("Doser à l'œil", "La machine pardonne peu les erreurs de quantité."),
 ("Laisser le pain dans la cuve", "La vapeur ramollit la croûte."),
],
"faq": [
 ("Est-ce économique ?", "En général oui par rapport au pain de boulangerie, selon la farine utilisée et la fréquence."),
 ("Peut-on faire de la pâte à pizza ?", "Oui, la plupart ont un programme pâte qui pétrit et laisse lever."),
 ("Combien de temps dure un cycle ?", "Environ trois heures pour un pain classique, moins pour un programme rapide."),
],
},
# ================================================================ JARDIN
{
"slug": "robot-tondeuse-sans-fil-perimetrique", "cat": "jardin", "short": "Robot tondeuse sans fil périmétrique",
"title": "Robot tondeuse sans fil périmétrique 2026 : comparatif RTK et vision",
"desc": "Robot tondeuse sans fil périmétrique : GPS RTK, vision par caméra, installation en une heure. Notre comparatif et les limites à connaître.",
"h1": "Robot tondeuse sans fil périmétrique : installer en une heure, sans creuser",
"lede": "GPS RTK, caméras, antenne de référence : comment fonctionnent les robots tondeuses sans câble, et dans quels jardins ils marchent bien.",
"teaser": "Pas de fil à enterrer.", "read": 8,
"pick": {"why": "Le guidage RTK le plus abouti du marché grand public : tonte en lignes droites et zones modifiables depuis le téléphone.",
         "alts": 'Grand jardin exigeant ? Voir <a href="#p2">Husqvarna EPOS</a>. Petit jardin ? Voir <a href="#p3">Mammotion</a>.'},
"table_cols": ["Guidage", "Jardin"],
"products": [
 {"name": "Segway Navimow", "brand": "Segway", "badge": "Meilleur choix", "price": "€€€", "table": ["RTK + vision", "Petit à grand"],
  "for": "la plupart des jardins dégagés.",
  "pros": ["Installation sans fil", "Tonte en lignes nettes", "Application claire"],
  "cons": ["Signal gêné sous les arbres", "Antenne à placer en hauteur"],
  "specs": [("Guidage", "RTK + vision"), ("Antenne", "Oui"), ("Pentes", "Moyennes"), ("Jardin", "Petit à grand")]},
 {"name": "Husqvarna Automower EPOS", "brand": "Husqvarna", "badge": "Haut de gamme", "price": "€€€€", "table": ["RTK", "Grand"],
  "for": "les grands terrains en pente.",
  "pros": ["Grande fiabilité", "Très bon sur les pentes", "SAV étendu"],
  "cons": ["Prix très élevé", "Station de référence à installer"],
  "specs": [("Guidage", "RTK"), ("Antenne", "Oui"), ("Pentes", "Fortes"), ("Jardin", "Grand")]},
 {"name": "Mammotion Luba / Yuka", "brand": "Mammotion", "badge": "Pentes et traction", "price": "€€€", "table": ["RTK + vision", "Moyen à grand"],
  "for": "les jardins accidentés ou très en pente.",
  "pros": ["Transmission intégrale sur certains modèles", "Grande capacité de pente", "Zones multiples"],
  "cons": ["Encombrant", "Marque récente"],
  "specs": [("Guidage", "RTK + vision"), ("Antenne", "Oui"), ("Pentes", "Très fortes"), ("Jardin", "Moyen à grand")]},
],
"criteria_title": "Ce qui compte sans fil périmétrique",
"criteria_intro": "Le RTK a besoin de voir le ciel. Un jardin très arboré ou encaissé reste mieux servi par un fil périmétrique.",
"criteria": [
 ("Ciel dégagé", "Proportion de pelouse sous les arbres", "Le signal satellite se perd sous un feuillage dense."),
 ("Antenne", "Emplacement en hauteur, alimentation", "Elle doit voir le ciel et rester fixe."),
 ("Vision", "Caméra pour les obstacles et les zones sans signal", "Complète le RTK près des murs et des haies."),
 ("Zones", "Plusieurs zones et passages", "Permet de relier pelouse avant et arrière."),
],
"tip": {"title": "Réussir l'installation RTK", "steps": [
 "Placez l'antenne en hauteur, dégagée de tout obstacle.",
 "Dessinez la limite en pilotant le robot au téléphone, lentement.",
 "Testez les passages étroits avant de lancer le planning."]},
"mistakes": [
 ("Ignorer les arbres", "Sous un grand arbre, le robot peut se perdre."),
 ("Bouger l'antenne", "Toute la carte devient fausse."),
 ("Oublier la 4G ou le Wi-Fi", "Certains modèles ont besoin d'une connexion pour être suivis."),
],
"faq": [
 ("Est-ce aussi précis qu'un fil ?", "En terrain dégagé, oui, à quelques centimètres près."),
 ("Et en cas de perte de signal ?", "Le robot s'arrête ou utilise ses caméras pour continuer prudemment."),
 ("Peut-on le voler plus facilement ?", "Ils ont en général une alarme, un code PIN et une localisation."),
],
},
{
"slug": "robot-piscine-sans-fil", "cat": "jardin", "short": "Robot piscine sans fil",
"title": "Robot piscine sans fil 2026 : comparatif des modèles sur batterie",
"desc": "Robot de piscine sans fil sur batterie : autonomie, parois, ligne d'eau, récupération. Notre comparatif et les limites à connaître.",
"h1": "Robot piscine sans fil : fini le câble emmêlé",
"lede": "Autonomie, recharge, nettoyage des parois, récupération au bord : ce que valent les robots sur batterie face aux modèles filaires.",
"teaser": "Un robot de piscine sans câble.", "read": 7,
"pick": {"why": "Le sans-fil le plus complet : fond, parois, ligne d'eau et même la surface, avec un retour au bord pour être récupéré.",
         "alts": 'Budget moyen ? Voir <a href="#p2">Aiper</a>. Petit bassin ? Voir <a href="#p3">modèle fond seul</a>.'},
"table_cols": ["Nettoie", "Retour au bord"],
"products": [
 {"name": "Beatbot", "brand": "Beatbot", "badge": "Meilleur choix", "price": "€€€€", "table": ["Fond, parois, surface", "Oui"],
  "for": "une grande piscine, sans compromis.",
  "pros": ["Nettoyage le plus complet", "Se gare seul au bord", "Bonne autonomie"],
  "cons": ["Prix très élevé", "Lourd"],
  "specs": [("Nettoie", "Fond, parois, surface"), ("Retour au bord", "Oui"), ("Recharge", "Hors de l'eau"), ("Piscine", "Grande")]},
 {"name": "Aiper", "brand": "Aiper", "badge": "Rapport qualité-prix", "price": "€€", "table": ["Fond et parois selon modèle", "Selon modèle"],
  "for": "une piscine moyenne, à budget raisonnable.",
  "pros": ["Prix raisonnable", "Léger", "Gamme large"],
  "cons": ["Autonomie limitée", "Ligne d'eau selon modèle"],
  "specs": [("Nettoie", "Selon modèle"), ("Retour au bord", "Selon modèle"), ("Recharge", "Hors de l'eau"), ("Piscine", "Moyenne")]},
 {"name": "Robot sans fil fond seul (entrée de gamme)", "brand": "Plusieurs marques", "badge": "Petit budget", "price": "€", "table": ["Fond", "Non"],
  "for": "une piscine hors-sol ou un petit bassin.",
  "pros": ["Prix bas", "Très simple", "Léger"],
  "cons": ["Ne nettoie que le fond", "Autonomie courte"],
  "specs": [("Nettoie", "Fond"), ("Retour au bord", "Non"), ("Recharge", "Hors de l'eau"), ("Piscine", "Petite")]},
],
"criteria_title": "Ce qui compte pour un robot sans fil",
"criteria_intro": "Le sans-fil supprime le câble, mais impose de sortir le robot pour le recharger. Le retour automatique au bord change tout.",
"criteria": [
 ("Autonomie", "Durée d'un cycle complet", "Elle doit couvrir toute la surface de votre bassin."),
 ("Retour au bord", "Le robot remonte-t-il seul ?", "Évite de le pêcher au fond avec un crochet."),
 ("Zones", "Fond, parois, ligne d'eau", "Les modèles d'entrée de gamme ne font souvent que le fond."),
 ("Poids", "Poids à sortir de l'eau", "Un robot plein d'eau pèse lourd."),
],
"tip": {"title": "Garder la batterie en forme", "steps": [
 "Rechargez le robot à l'ombre, sec.",
 "Ne le laissez pas déchargé plusieurs semaines.",
 "Hivernez-le avec une batterie à moitié chargée."]},
"mistakes": [
 ("Prendre un fond seul pour une grande piscine", "Les parois verdissent quand même."),
 ("Ignorer l'autonomie", "Le robot s'arrête avant d'avoir tout nettoyé."),
 ("Le recharger mouillé", "Séchez les contacts de charge avant de brancher."),
],
"faq": [
 ("Sans fil ou filaire ?", "Le sans-fil est plus confortable. Le filaire reste plus endurant pour les grands bassins."),
 ("Combien de temps dure la batterie ?", "Plusieurs saisons avec une bonne utilisation, comme pour les autres appareils sur batterie."),
 ("Peut-il rester dans l'eau ?", "Mieux vaut le sortir après chaque cycle pour le recharger et protéger ses joints."),
],
},
{
"slug": "souffleur-feuilles-batterie", "cat": "jardin", "short": "Souffleur de feuilles sur batterie",
"title": "Souffleur de feuilles sur batterie 2026 : comparatif",
"desc": "Souffleur de feuilles sans fil sur batterie : puissance, autonomie, bruit. Notre comparatif pour ramasser les feuilles en un temps record.",
"h1": "Souffleur de feuilles sur batterie : l'automne sans le râteau",
"lede": "Vitesse et volume d'air, autonomie, poids, bruit pour les voisins : comment choisir un souffleur qui remplace le râteau.",
"teaser": "Les feuilles ramassées sans râteau.", "read": 6,
"pick": {"why": "Puissant, léger et compatible avec toute une gamme d'outils sur la même batterie.",
         "alts": 'Déjà des batteries Ryobi ? Voir <a href="#p2">Ryobi</a>. Petit budget ? Voir <a href="#p3">Worx</a>.'},
"table_cols": ["Aspiration", "Gamme de batteries"],
"products": [
 {"name": "Makita (souffleur 18 V)", "brand": "Makita", "badge": "Meilleur choix", "price": "€€", "table": ["Non", "Très large"],
  "for": "un jardin moyen et ceux qui ont déjà des outils Makita.",
  "pros": ["Robuste", "Batteries partagées avec de nombreux outils", "Bonne puissance"],
  "cons": ["Batterie vendue à part", "Bruyant en mode turbo"],
  "specs": [("Aspiration", "Non"), ("Batterie", "18 V partagée"), ("Poids", "Léger"), ("Jardin", "Moyen")]},
 {"name": "Ryobi (souffleur ONE+)", "brand": "Ryobi", "badge": "Gamme large", "price": "€€", "table": ["Selon modèle", "Très large"],
  "for": "les jardiniers équipés de la gamme ONE+.",
  "pros": ["Batterie commune à des dizaines d'outils", "Prix raisonnable", "Facile à trouver"],
  "cons": ["Autonomie moyenne", "Finitions simples"],
  "specs": [("Aspiration", "Selon modèle"), ("Batterie", "18 V partagée"), ("Poids", "Léger"), ("Jardin", "Petit à moyen")]},
 {"name": "Worx (souffleur aspirateur)", "brand": "Worx", "badge": "Petit budget", "price": "€", "table": ["Oui", "Moyenne"],
  "for": "un petit jardin, pour souffler et aspirer.",
  "pros": ["Souffle et aspire", "Broyage des feuilles", "Prix bas"],
  "cons": ["Sac vite plein", "Moins puissant"],
  "specs": [("Aspiration", "Oui"), ("Batterie", "20 V"), ("Poids", "Moyen"), ("Jardin", "Petit")]},
],
"criteria_title": "Ce qui compte pour un souffleur",
"criteria_intro": "Le volume d'air déplacé compte plus que la vitesse : c'est lui qui pousse un tas de feuilles humides.",
"criteria": [
 ("Volume d'air", "Mètres cubes par heure", "Pousse les feuilles en tas."),
 ("Autonomie", "Minutes à pleine puissance", "Prévoyez une deuxième batterie pour un grand jardin."),
 ("Écosystème", "Batterie partagée avec d'autres outils", "Évite de racheter chargeur et batteries."),
 ("Bruit", "Niveau sonore", "Les horaires d'utilisation sont souvent réglementés."),
],
"tip": {"title": "Ramasser les feuilles en vingt minutes", "steps": [
 "Soufflez par temps sec, quand les feuilles sont légères.",
 "Travaillez dans le sens du vent, vers une bâche posée au sol.",
 "Repliez la bâche et videz-la au compost."]},
"mistakes": [
 ("Souffler des feuilles mouillées", "Elles collent au sol et vident la batterie."),
 ("Changer de marque de batterie", "Restez dans le même écosystème."),
 ("Souffler tôt le matin", "Respectez les horaires de bruit de votre commune."),
],
"faq": [
 ("Batterie ou thermique ?", "Pour un jardin de particulier, la batterie suffit et fait beaucoup moins de bruit."),
 ("Faut-il la fonction aspiration ?", "Utile pour un petit jardin. Pour un grand, souffler en tas puis ramasser va plus vite."),
 ("Les feuilles broyées servent-elles ?", "Oui, en paillage au pied des massifs."),
],
},
# ================================================================ ANIMAUX
{
"slug": "litiere-autonettoyante-plusieurs-chats", "cat": "animaux", "short": "Litière autonettoyante pour plusieurs chats",
"title": "Litière autonettoyante pour plusieurs chats 2026 : notre sélection",
"desc": "Litière autonettoyante pour 2 ou 3 chats : capacité du bac, identification des chats, cycles. Notre sélection et nos conseils pratiques.",
"h1": "Litière autonettoyante pour plusieurs chats : une seule pour tous ?",
"lede": "Capacité du bac à déchets, reconnaissance de chaque chat, nombre de litières conseillé : comment gérer deux ou trois chats sans ramassage quotidien.",
"teaser": "Gérer deux ou trois chats sans ramassage.", "read": 7,
"pick": {"why": "Son grand bac et sa reconnaissance des chats par le poids permettent de suivre chacun et de vider moins souvent.",
         "alts": 'Chats craintifs ? Voir <a href="#p3">deux bacs ouverts</a>. Format fermé ? Voir <a href="#p2">Petkit Pura Max</a>.'},
"table_cols": ["Suivi par chat", "Bac"],
"products": [
 {"name": "Litter-Robot 4", "brand": "Whisker", "badge": "Meilleur choix", "price": "€€€€", "table": ["Oui, par le poids", "Grand"],
  "for": "deux à trois chats adultes.",
  "pros": ["Grand bac à déchets", "Suivi par chat dans l'application", "Cycle rapide"],
  "cons": ["Prix élevé", "Hauteur importante"],
  "specs": [("Suivi par chat", "Oui"), ("Bac", "Grand"), ("Format", "Globe"), ("Chats", "Jusqu'à 3")]},
 {"name": "Petkit Pura Max", "brand": "Petkit", "badge": "Fermée", "price": "€€€", "table": ["Oui", "Moyen"],
  "for": "deux chats habitués aux litières couvertes.",
  "pros": ["Reconnaissance des chats", "Contrôle des odeurs", "Application complète"],
  "cons": ["Bac à vider plus souvent", "Format fermé qui peut gêner"],
  "specs": [("Suivi par chat", "Oui"), ("Bac", "Moyen"), ("Format", "Fermé"), ("Chats", "Jusqu'à 2")]},
 {"name": "Deux bacs à râteau (PetSafe ScoopFree)", "brand": "PetSafe", "badge": "Chats craintifs", "price": "€€", "table": ["Non", "Plateau"],
  "for": "des chats qui refusent de partager ou qui ont peur du mouvement.",
  "pros": ["Un bac par chat", "Format ouvert rassurant", "Moins cher que deux robots"],
  "cons": ["Plateaux jetables", "Pas de suivi"],
  "specs": [("Suivi par chat", "Non"), ("Bac", "Plateau"), ("Format", "Ouvert"), ("Chats", "1 par bac")]},
],
"criteria_title": "Ce qui compte avec plusieurs chats",
"criteria_intro": "Les vétérinaires conseillent souvent une litière par chat, plus une. Une litière automatique réduit ce besoin, sans toujours le supprimer.",
"criteria": [
 ("Capacité du bac", "Jours d'autonomie annoncés pour un chat", "Divisez par le nombre de chats."),
 ("Suivi par chat", "Reconnaissance par le poids", "Permet de repérer qui va moins souvent aux toilettes."),
 ("Délai de cycle", "Attente après le passage", "Avec plusieurs chats, un délai court évite qu'ils trouvent une litière sale."),
 ("Deuxième litière", "Place pour une litière classique", "Certains chats refusent de partager."),
],
"tip": {"title": "Faire cohabiter plusieurs chats", "steps": [
 "Gardez une litière classique en plus les premières semaines.",
 "Observez qui utilise la nouvelle litière dans l'application.",
 "Retirez l'ancienne seulement si tous les chats ont adopté la nouvelle."]},
"mistakes": [
 ("Une seule litière pour quatre chats", "Le bac déborde et les conflits apparaissent."),
 ("Ignorer le chat dominant", "Il peut bloquer l'accès aux autres."),
 ("Ne pas surveiller", "Un chat qui ne va plus aux toilettes doit voir un vétérinaire."),
],
"faq": [
 ("Combien de chats par litière automatique ?", "Deux ou trois selon le modèle et le bac. Vérifiez la recommandation du fabricant."),
 ("Les chats se partagent-ils une litière ?", "Beaucoup oui, mais certains refusent. Gardez une solution de secours."),
 ("Le suivi par chat est-il fiable ?", "Il fonctionne bien quand les chats ont des poids assez différents."),
],
},
{
"slug": "chatiere-electronique", "cat": "animaux", "short": "Chatière électronique",
"title": "Chatière électronique à puce 2026 : comparatif",
"desc": "Chatière électronique à puce : votre chat sort seul, les chats du voisinage restent dehors. Notre comparatif et nos conseils d'installation.",
"h1": "Chatière électronique : le chat sort seul, sans vous réveiller",
"lede": "Lecture de puce, couvre-feu, application, installation sur porte ou vitre : comment ne plus jouer les portiers.",
"teaser": "Le chat sort seul, sans vous réveiller.", "read": 6,
"pick": {"why": "Elle lit la puce d'identification de votre chat et garde dehors ceux du voisinage. Couvre-feu et application en option.",
         "alts": 'Sans application ? Voir <a href="#p2">SureFlap Microchip</a>. Petit budget ? Voir <a href="#p3">Cat Mate</a>.'},
"table_cols": ["Lecture", "Application"],
"products": [
 {"name": "SureFlap Connect", "brand": "Sure Petcare", "badge": "Meilleur choix", "price": "€€€", "table": ["Puce", "Oui"],
  "for": "suivre les allées et venues et verrouiller à distance.",
  "pros": ["Lecture de la puce existante", "Verrouillage à distance", "Historique des sorties"],
  "cons": ["Passerelle nécessaire", "Prix élevé"],
  "specs": [("Lecture", "Puce"), ("Application", "Oui"), ("Couvre-feu", "Oui"), ("Pose", "Porte, mur, vitre")]},
 {"name": "SureFlap Microchip", "brand": "Sure Petcare", "badge": "Sans application", "price": "€€", "table": ["Puce", "Non"],
  "for": "bloquer les chats du voisinage, simplement.",
  "pros": ["Lecture de la puce", "Fiable", "Fonctionne sur piles"],
  "cons": ["Pas de suivi", "Installation à prévoir"],
  "specs": [("Lecture", "Puce"), ("Application", "Non"), ("Couvre-feu", "Selon modèle"), ("Pose", "Porte, mur, vitre")]},
 {"name": "Cat Mate (chatière électronique)", "brand": "Cat Mate", "badge": "Petit budget", "price": "€", "table": ["Puce ou médaille", "Non"],
  "for": "un premier équipement à petit prix.",
  "pros": ["Prix accessible", "Plusieurs chats enregistrables", "Verrouillage manuel"],
  "cons": ["Finitions plus simples", "Pas de suivi"],
  "specs": [("Lecture", "Puce ou médaille"), ("Application", "Non"), ("Couvre-feu", "Non"), ("Pose", "Porte")]},
],
"criteria_title": "Ce qui compte pour une chatière",
"criteria_intro": "Vérifiez d'abord que votre chat est pucé : la plupart des chatières électroniques lisent directement la puce d'identification.",
"criteria": [
 ("Lecture", "Puce ou médaille de collier", "La puce évite le collier, qui peut se perdre."),
 ("Pose", "Porte, mur, double vitrage", "La pose sur vitre demande un vitrier."),
 ("Couvre-feu", "Verrouillage programmé", "Garde le chat à l'intérieur la nuit."),
 ("Taille du passage", "Dimensions de l'ouverture", "Un grand chat doit passer sans forcer."),
],
"tip": {"title": "Apprendre la chatière au chat", "steps": [
 "Bloquez la trappe en position ouverte les premiers jours.",
 "Placez une friandise de l'autre côté.",
 "Passez en mode normal quand le chat la traverse seul."]},
"mistakes": [
 ("Oublier de vérifier la puce", "Certaines puces anciennes sont mal lues."),
 ("Mal choisir la hauteur", "Le passage doit être à hauteur du ventre du chat."),
 ("Négliger les piles", "Une chatière à plat reste bloquée."),
],
"faq": [
 ("Les chats du voisinage peuvent-ils entrer ?", "Non : seuls les chats enregistrés ouvrent la trappe."),
 ("Fonctionne-t-elle avec plusieurs chats ?", "Oui, on peut enregistrer plusieurs puces."),
 ("Peut-on l'installer en location ?", "Mieux vaut demander l'accord du propriétaire, ou choisir une pose sur panneau amovible."),
],
},
{
"slug": "lanceur-balle-automatique", "cat": "animaux", "short": "Lanceur de balle automatique pour chien",
"title": "Lanceur de balle automatique pour chien 2026 : comparatif",
"desc": "Lanceur de balle automatique pour chien : distance, taille des balles, apprentissage. Notre sélection pour occuper son chien sans y passer des heures.",
"h1": "Lanceur de balle automatique : le chien joue, vous soufflez",
"lede": "Distance de lancer, taille des balles, intérieur ou extérieur, autonomie : comment choisir un lanceur que votre chien apprendra à recharger seul.",
"teaser": "Le chien joue tout seul à la balle.", "read": 6,
"pick": {"why": "Distance réglable, utilisable dedans comme dehors, et facile à recharger seul pour un chien qui a compris le principe.",
         "alts": 'Petit chien ? Voir <a href="#p2">modèle mini</a>. Grand jardin ? Voir <a href="#p3">modèle longue portée</a>.'},
"table_cols": ["Balles", "Usage"],
"products": [
 {"name": "iFetch", "brand": "iFetch", "badge": "Meilleur choix", "price": "€€", "table": ["Petites ou standard", "Intérieur, extérieur"],
  "for": "la plupart des chiens joueurs.",
  "pros": ["Distance réglable", "Simple à comprendre pour le chien", "Utilisable en intérieur"],
  "cons": ["Balles spécifiques selon le modèle", "Bruit au lancer"],
  "specs": [("Balles", "Selon modèle"), ("Distance", "Réglable"), ("Alimentation", "Secteur ou batterie"), ("Usage", "Intérieur, extérieur")]},
 {"name": "PetSafe Lanceur de balle automatique", "brand": "PetSafe", "badge": "Réglages fins", "price": "€€€", "table": ["Tennis standard", "Intérieur et jardin"],
  "for": "les chiens petits à moyens accros au rapport, à l'intérieur comme au jardin.",
  "pros": ["9 distances (2,5 à 9 m) et 6 angles", "Capteur de mouvement devant la sortie", "Pause automatique après 30 minutes"],
  "cons": ["Plus cher", "Encombrant en appartement"],
  "specs": [("Balles", "Tennis standard"), ("Distance", "2,5 à 9 m"), ("Alimentation", "Secteur ou piles"), ("Usage", "Intérieur et jardin")]},
 {"name": "Lanceur longue portée (plusieurs marques)", "brand": "Plusieurs marques", "badge": "Grand jardin", "price": "€€", "table": ["Standard", "Extérieur"],
  "for": "les grands chiens et les grands espaces.",
  "pros": ["Lancers longs", "Balles standard", "Robuste"],
  "cons": ["Encombrant", "Pas adapté à l'intérieur"],
  "specs": [("Balles", "Standard"), ("Distance", "Longue"), ("Alimentation", "Batterie"), ("Usage", "Extérieur")]},
],
"criteria_title": "Ce qui compte pour un lanceur de balle",
"criteria_intro": "Choisissez la taille des balles selon votre chien : une balle trop petite peut être avalée par un grand chien.",
"criteria": [
 ("Taille des balles", "Diamètre accepté", "Une balle trop petite est un risque d'étouffement."),
 ("Distance réglable", "Plusieurs portées", "Indispensable pour passer de l'intérieur au jardin."),
 ("Pause automatique", "Repos après une série de lancers", "Évite que le chien s'épuise."),
 ("Alimentation", "Batterie ou secteur", "La batterie permet de jouer au fond du jardin."),
],
"tip": {"title": "Apprendre au chien à recharger seul", "steps": [
 "Montrez au chien la balle qui sort, en le félicitant.",
 "Guidez-le pour déposer la balle dans l'entonnoir, avec une friandise.",
 "Répétez quelques minutes par jour jusqu'à ce qu'il le fasse seul."]},
"mistakes": [
 ("Laisser jouer sans limite", "Certains chiens ne s'arrêtent jamais : programmez des pauses."),
 ("Balles trop petites", "Vérifiez la taille selon la gueule du chien."),
 ("Le laisser sans surveillance au début", "Assurez-vous que le chien joue sans risque."),
],
"faq": [
 ("Tous les chiens comprennent-ils ?", "Les chiens joueurs apprennent souvent en quelques jours. D'autres ne s'y intéressent jamais."),
 ("Peut-on l'utiliser en appartement ?", "Oui avec une distance courte et un modèle adapté à l'intérieur."),
 ("Remplace-t-il la promenade ?", "Non. Il complète les sorties et occupe le chien quand vous êtes occupé."),
],
},
]
